CC      = g++
CFLAGS  = -Wall -g0 -O3 -DENV_QNX -D_REENTRANT -DOAPC_EXT_API="" -D_DEBUG -L/usr/lib -L/usr/local/lib/ -L/opt/X11R6/lib/ -I .. -I ../../

LDFLAGS  = -lsocket -loapc -lm  -lph $(shell wx-config --libs)

PNAME=iserver_example1

OBJ = iserver_example1.o
SRC = iserver_example1.c

all: $(OBJ)
	$(CC) $(CFLAGS) -o $(PNAME) $(OBJ) $(LDFLAGS)
	strip $(PNAME)
	cp $(PNAME) ~
	chmod 755 ~/$(PNAME)

clean:
	rm *.o
	rm $(PNAME)
