CC      = g++
CFLAGS  = -Wall -g0 -O3 -DENV_QNX -D_REENTRANT -DOAPC_EXT_API="" -D_DEBUG -L/usr/lib -L/usr/local/lib/ -L/opt/X11R6/lib/ -I ../../liboapc/ -I ../../plugins/

LDFLAGS  = -lsocket -loapc -lph $(shell wx-config --libs)

PNAME=iswatcher

OBJ = iswatcher.o
SRC = iswatcher.c

all: $(OBJ)
	$(CC) $(CFLAGS) -o $(PNAME) $(OBJ) $(LDFLAGS)

clean:
	rm *.o
	rm $(PNAME)
