/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE1"
 * 	found in "../isoAcseLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_RLRQapdu_H_
#define	_RLRQapdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Releaserequestreason.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Associationinformation;

/* RLRQapdu */
typedef struct RLRQapdu {
	Releaserequestreason_t	*reason	/* OPTIONAL */;
	struct Associationinformation	*userinformation	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RLRQapdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RLRQapdu;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Associationinformation.h"

#endif	/* _RLRQapdu_H_ */
