/**********************************************************************
--- Qt Architect generated file ---
File: ReportDirData.h
Last generated: Fri Feb 16 15:12:08 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef ReportDirData_included
#define ReportDirData_included
#include <qt.h>
class ReportDirData : public QDialog
{
	Q_OBJECT
	public:
	ReportDirData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~ReportDirData();
	QListBox *List;
	QPushButton *OkButton;
};
#endif // ReportDirData_included

