############################
# Part 1: LOCAL DEFINITIONS

      TOP  = ../..

#############################
# Part 2: COMMON MAKE PARAMETERS

include $(TOP)/make.proj

#############################
# Part 3: LOCAL SOURCES 

   DIRS = src test

##############################
# Part 4: LOCAL TARGETS  

include $(CONFIG_DIR)/NormalNodeTargets

#############################
# Part 5: COMMON RULES and 
#     and default Targets

include $(CONFIG_DIR)/make.rules

#############################
# Part 6: DEPENDENCIES














