/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE1"
 * 	found in "../isoAcseLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_ACSErequirements_H_
#define	_ACSErequirements_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ACSErequirements {
	ACSErequirements_authentication	= 0,
	ACSErequirements_applicationcontextnegotiation	= 1
} e_ACSErequirements;

/* ACSErequirements */
typedef BIT_STRING_t	 ACSErequirements_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ACSErequirements;
asn_struct_free_f ACSErequirements_free;
asn_struct_print_f ACSErequirements_print;
asn_constr_check_f ACSErequirements_constraint;
ber_type_decoder_f ACSErequirements_decode_ber;
der_type_encoder_f ACSErequirements_encode_der;
xer_type_decoder_f ACSErequirements_decode_xer;
xer_type_encoder_f ACSErequirements_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ACSErequirements_H_ */
