/**********************************************************************
--- Qt Architect generated file ---
File: DateNavigatorData.h
Last generated: Mon Sep 18 16:02:38 2000
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef DateNavigatorData_included
#define DateNavigatorData_included
#include <qt.h>
#include "datenav.h"
class DateNavigatorData : public QDialog
{
	Q_OBJECT
	public:
	DateNavigatorData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~DateNavigatorData();
	protected:
	dateNav *TheDate;
};
#endif // DateNavigatorData_included

