/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE1"
 * 	found in "../isoAcseLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Applicationcontextname_H_
#define	_Applicationcontextname_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Applicationcontextname */
typedef OBJECT_IDENTIFIER_t	 Applicationcontextname_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Applicationcontextname;
asn_struct_free_f Applicationcontextname_free;
asn_struct_print_f Applicationcontextname_print;
asn_constr_check_f Applicationcontextname_constraint;
ber_type_decoder_f Applicationcontextname_decode_ber;
der_type_encoder_f Applicationcontextname_encode_der;
xer_type_decoder_f Applicationcontextname_decode_xer;
xer_type_encoder_f Applicationcontextname_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Applicationcontextname_H_ */
