all: build 

build: pydax.c
	python setup.py build

install: pydax.c
	python setup.py install

clean: pydax.c
	python setup.py clean

dist: pydax.c
	python setup.py sdist

.PHONY: build install clean dist
