CUSTLIBRARIES= 

CUSTINCLUDES= -I../libio_coherent_avia/ -fexceptions

CUSTOBJECTS= FocusAPC.o ../libio_coherent_avia/FException.o ../libio_coherent_avia/FLib.o \
				../libio_coherent_avia/FSocket.o

include ../linux.mk
