/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823PRESENTATION"
 * 	found in "../isoPresentationLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Callingpresentationselector_H_
#define	_Callingpresentationselector_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Presentationselector.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Callingpresentationselector */
typedef Presentationselector_t	 Callingpresentationselector_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Callingpresentationselector;
asn_struct_free_f Callingpresentationselector_free;
asn_struct_print_f Callingpresentationselector_print;
asn_constr_check_f Callingpresentationselector_constraint;
ber_type_decoder_f Callingpresentationselector_decode_ber;
der_type_encoder_f Callingpresentationselector_encode_der;
xer_type_decoder_f Callingpresentationselector_decode_xer;
xer_type_encoder_f Callingpresentationselector_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Callingpresentationselector_H_ */
