/**********************************************************************
--- Qt Architect generated file ---
File: InspectFrameDlgData.h
Last generated: Mon Jun 26 14:49:44 2000
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef InspectFrameDlgData_included
#define InspectFrameDlgData_included
#include <qt.h>
#include "valedit.h"
class InspectFrameDlgData : public QFrame
{
	Q_OBJECT
	public:
	InspectFrameDlgData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~InspectFrameDlgData();
	protected slots:
	virtual void GetData() =0;
	protected:
	DATEEDIT *FromDate;
	TIMEEDIT *FromTime;
	TIMEEDIT *ToTime;
	DATEEDIT *ToDate;
};
#endif // InspectFrameDlgData_included

