/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE1"
 * 	found in "../isoAcseLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_AEtitleform2_H_
#define	_AEtitleform2_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AEtitleform2 */
typedef OBJECT_IDENTIFIER_t	 AEtitleform2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AEtitleform2;
asn_struct_free_f AEtitleform2_free;
asn_struct_print_f AEtitleform2_print;
asn_constr_check_f AEtitleform2_constraint;
ber_type_decoder_f AEtitleform2_decode_ber;
der_type_encoder_f AEtitleform2_encode_der;
xer_type_decoder_f AEtitleform2_decode_xer;
xer_type_encoder_f AEtitleform2_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AEtitleform2_H_ */
