/**********************************************************************

	--- Qt Architect generated file ---

	File: ReceipeCfgData.cpp
	Last generated: Fri Dec 28 10:26:42 2001

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "ReceipeCfgData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qpushbutton.h>
#include <common.h>

ReceipeCfgData::ReceipeCfgData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 208 )
{
	QLabel* qtarch_Label_32;
	qtarch_Label_32 = new QLabel( this, "Label_32" );
	qtarch_Label_32->setGeometry( 20, 20, 90, 30 );
	qtarch_Label_32->setMinimumSize( 0, 0 );
	qtarch_Label_32->setMaximumSize( 32767, 32767 );
	qtarch_Label_32->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_32->setBackgroundMode( QWidget::PaletteBackground );
#if QT_VERSION < 300
	qtarch_Label_32->setFontPropagation( QWidget::SameFont );
	qtarch_Label_32->setPalettePropagation( QWidget::SameFont );
		#endif
	qtarch_Label_32->setFrameStyle( 0 );
	qtarch_Label_32->setLineWidth( 1 );
	qtarch_Label_32->setMidLineWidth( 0 );
	qtarch_Label_32->QFrame::setMargin( 0 );
	qtarch_Label_32->setText( tr("Name") );
	qtarch_Label_32->setAlignment( 0 );
	qtarch_Label_32->setMargin( 0 );

	Name = new QComboBox( FALSE, this, "ComboBox_14" );
	Name->setGeometry( 120, 20, 480, 30 );
	Name->setMinimumSize( 0, 0 );
	Name->setMaximumSize( 32767, 32767 );
	connect( Name, SIGNAL(activated(int)), SLOT(SelChanged(int)) );
	connect( Name, SIGNAL(highlighted(int)), SLOT(SelChanged(int)) );
	Name->setFocusPolicy( QWidget::StrongFocus );
	Name->setBackgroundMode( QWidget::NoBackground );
#if QT_VERSION < 300
	Name->setFontPropagation( QWidget::SameFont );
	Name->setPalettePropagation( QWidget::SameFont );
		#endif
	Name->setSizeLimit( 10 );
	Name->setAutoResize( FALSE );
	Name->setMaxCount( 2147483647 );
	Name->setAutoCompletion( FALSE );

	QLabel* qtarch_Label_33;
	qtarch_Label_33 = new QLabel( this, "Label_33" );
	qtarch_Label_33->setGeometry( 20, 60, 90, 30 );
	qtarch_Label_33->setMinimumSize( 0, 0 );
	qtarch_Label_33->setMaximumSize( 32767, 32767 );
	qtarch_Label_33->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_33->setBackgroundMode( QWidget::PaletteBackground );
#if QT_VERSION < 300
	qtarch_Label_33->setFontPropagation( QWidget::SameFont );
	qtarch_Label_33->setPalettePropagation( QWidget::SameFont );
		#endif
	qtarch_Label_33->setFrameStyle( 0 );
	qtarch_Label_33->setLineWidth( 1 );
	qtarch_Label_33->setMidLineWidth( 0 );
	qtarch_Label_33->QFrame::setMargin( 0 );
	qtarch_Label_33->setText( tr("Comment") );
	qtarch_Label_33->setAlignment( 0 );
	qtarch_Label_33->setMargin( 0 );

	Comment = new QLineEdit( this, "LineEdit_14" );
	Comment->setGeometry( 120, 60, 480, 30 );
	Comment->setMinimumSize( 0, 0 );
	Comment->setMaximumSize( 32767, 32767 );
	Comment->setFocusPolicy( QWidget::StrongFocus );
	Comment->setBackgroundMode( QWidget::PaletteBase );
#if QT_VERSION < 300
	Comment->setFontPropagation( QWidget::SameFont );
	Comment->setPalettePropagation( QWidget::SameFont );
		#endif
	Comment->setText( tr(NONE_STR));
	Comment->setMaxLength( 128 );
	Comment->setFrame( QLineEdit::Normal );
	Comment->setFrame( TRUE );

	UnitsList = new QListView( this, "ListView_2" );
	UnitsList->setGeometry( 120, 100, 480, 100 );
	UnitsList->setMinimumSize( 0, 0 );
	UnitsList->setMaximumSize( 32767, 32767 );
	UnitsList->setFocusPolicy( QWidget::StrongFocus );
	UnitsList->setBackgroundMode( QWidget::PaletteBackground );
#if QT_VERSION < 300
	UnitsList->setFontPropagation( QWidget::SameFont );
	UnitsList->setPalettePropagation( QWidget::SameFont );
		#endif
	UnitsList->setFrameStyle( 50 );
	UnitsList->setLineWidth( 2 );
	UnitsList->setMidLineWidth( 0 );
	UnitsList->QFrame::setMargin( 0 );
	UnitsList->setResizePolicy( QScrollView::Manual );
	UnitsList->setVScrollBarMode( QScrollView::Auto );
	UnitsList->setHScrollBarMode( QScrollView::Auto );
	UnitsList->setTreeStepSize( 20 );
	UnitsList->setMultiSelection( FALSE );
	UnitsList->setAllColumnsShowFocus( FALSE );
	UnitsList->setItemMargin( 1 );
	UnitsList->setRootIsDecorated( FALSE );
	UnitsList->addColumn( tr("Unit"), -1 );
	UnitsList->setColumnWidthMode( 0, QListView::Maximum );
	UnitsList->setColumnAlignment( 0, 1 );
	UnitsList->addColumn(tr("Comment"), -1 );
	UnitsList->setColumnWidthMode( 1, QListView::Maximum );
	UnitsList->setColumnAlignment( 1, 1 );

	QLabel* qtarch_Label_34;
	qtarch_Label_34 = new QLabel( this, "Label_34" );
	qtarch_Label_34->setGeometry( 20, 110, 90, 30 );
	qtarch_Label_34->setMinimumSize( 0, 0 );
	qtarch_Label_34->setMaximumSize( 32767, 32767 );
	qtarch_Label_34->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_34->setBackgroundMode( QWidget::PaletteBackground );
#if QT_VERSION < 300
	qtarch_Label_34->setFontPropagation( QWidget::SameFont );
	qtarch_Label_34->setPalettePropagation( QWidget::SameFont );
		#endif
	qtarch_Label_34->setFrameStyle( 0 );
	qtarch_Label_34->setLineWidth( 1 );
	qtarch_Label_34->setMidLineWidth( 0 );
	qtarch_Label_34->QFrame::setMargin( 0 );
	qtarch_Label_34->setText( tr("Units") );
	qtarch_Label_34->setAlignment( 0 );
	qtarch_Label_34->setMargin( 0 );

	UnitButton = new QPushButton( this, "PushButton_30" );
	UnitButton->setGeometry( 620, 120, 100, 30 );
	UnitButton->setMinimumSize( 0, 0 );
	UnitButton->setMaximumSize( 32767, 32767 );
	connect( UnitButton, SIGNAL(clicked()), SLOT(ConfigureUnit()) );
	UnitButton->setFocusPolicy( QWidget::TabFocus );
	UnitButton->setBackgroundMode( QWidget::PaletteBackground );
#if QT_VERSION < 300
	UnitButton->setFontPropagation( QWidget::SameFont );
	UnitButton->setPalettePropagation( QWidget::SameFont );
		#endif
	UnitButton->setText( tr("Configure...") );
	UnitButton->setAutoRepeat( FALSE );
	UnitButton->setAutoResize( FALSE );
	UnitButton->setToggleButton( FALSE );
	UnitButton->setDefault( FALSE );
	UnitButton->setAutoDefault( FALSE );
	UnitButton->setIsMenuButton( FALSE );

	SampleList = new QListView( this, "ListView_3" );
	SampleList->setGeometry( 120, 210, 480, 300 );
	SampleList->setMinimumSize( 0, 0 );
	SampleList->setMaximumSize( 32767, 32767 );
	SampleList->setFocusPolicy( QWidget::StrongFocus );
	SampleList->setBackgroundMode( QWidget::PaletteBackground );
#if QT_VERSION < 300
	SampleList->setFontPropagation( QWidget::SameFont );
	SampleList->setPalettePropagation( QWidget::SameFont );
		#endif
	SampleList->setFrameStyle( 50 );
	SampleList->setLineWidth( 2 );
	SampleList->setMidLineWidth( 0 );
	SampleList->QFrame::setMargin( 0 );
	SampleList->setResizePolicy( QScrollView::Manual );
	SampleList->setVScrollBarMode( QScrollView::Auto );
	SampleList->setHScrollBarMode( QScrollView::Auto );
	SampleList->setTreeStepSize( 20 );
	SampleList->setMultiSelection( FALSE );
	SampleList->setAllColumnsShowFocus( FALSE );
	SampleList->setItemMargin( 1 );
	SampleList->setRootIsDecorated( FALSE );
	SampleList->addColumn( tr("Sample Points"), -1 );
	SampleList->setColumnWidthMode( 0, QListView::Maximum );
	SampleList->setColumnAlignment( 0, 1 );
	SampleList->addColumn(tr("Comment"), -1 );
	SampleList->setColumnWidthMode( 1, QListView::Maximum );
	SampleList->setColumnAlignment( 1, 1 );

	QLabel* qtarch_Label_35;
	qtarch_Label_35 = new QLabel( this, "Label_35" );
	qtarch_Label_35->setGeometry( 20, 220, 100, 30 );
	qtarch_Label_35->setMinimumSize( 0, 0 );
	qtarch_Label_35->setMaximumSize( 32767, 32767 );
	qtarch_Label_35->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_35->setBackgroundMode( QWidget::PaletteBackground );
#if QT_VERSION < 300
	qtarch_Label_35->setFontPropagation( QWidget::SameFont );
	qtarch_Label_35->setPalettePropagation( QWidget::SameFont );
		#endif
	qtarch_Label_35->setFrameStyle( 0 );
	qtarch_Label_35->setLineWidth( 1 );
	qtarch_Label_35->setMidLineWidth( 0 );
	qtarch_Label_35->QFrame::setMargin( 0 );
	qtarch_Label_35->setText( tr("Sample Points") );
	qtarch_Label_35->setAlignment( 0 );
	qtarch_Label_35->setMargin( 0 );

	ApplyButton = new QPushButton( this, "PushButton_31" );
	ApplyButton->setGeometry( 20, 520, 100, 30 );
	ApplyButton->setMinimumSize( 0, 0 );
	ApplyButton->setMaximumSize( 32767, 32767 );
	connect( ApplyButton, SIGNAL(clicked()), SLOT(Apply()) );
	ApplyButton->setFocusPolicy( QWidget::TabFocus );
	ApplyButton->setBackgroundMode( QWidget::PaletteBackground );
#if QT_VERSION < 300
	ApplyButton->setFontPropagation( QWidget::SameFont );
	ApplyButton->setPalettePropagation( QWidget::SameFont );
		#endif
	ApplyButton->setText( tr("Apply") );
	ApplyButton->setAutoRepeat( FALSE );
	ApplyButton->setAutoResize( FALSE );
	ApplyButton->setToggleButton( FALSE );
	ApplyButton->setDefault( FALSE );
	ApplyButton->setAutoDefault( FALSE );
	ApplyButton->setIsMenuButton( FALSE );

	NewButton = new QPushButton( this, "PushButton_32" );
	NewButton->setGeometry( 140, 520, 100, 30 );
	NewButton->setMinimumSize( 0, 0 );
	NewButton->setMaximumSize( 32767, 32767 );
	connect( NewButton, SIGNAL(clicked()), SLOT(New()) );
	NewButton->setFocusPolicy( QWidget::TabFocus );
	NewButton->setBackgroundMode( QWidget::PaletteBackground );
#if QT_VERSION < 300
	NewButton->setFontPropagation( QWidget::SameFont );
	NewButton->setPalettePropagation( QWidget::SameFont );
		#endif
	NewButton->setText( tr("New...") );
	NewButton->setAutoRepeat( FALSE );
	NewButton->setAutoResize( FALSE );
	NewButton->setToggleButton( FALSE );
	NewButton->setDefault( FALSE );
	NewButton->setAutoDefault( FALSE );
	NewButton->setIsMenuButton( FALSE );

	DeleteButton = new QPushButton( this, "PushButton_33" );
	DeleteButton->setGeometry( 260, 520, 100, 30 );
	DeleteButton->setMinimumSize( 0, 0 );
	DeleteButton->setMaximumSize( 32767, 32767 );
	connect( DeleteButton, SIGNAL(clicked()), SLOT(Delete()) );
	DeleteButton->setFocusPolicy( QWidget::TabFocus );
	DeleteButton->setBackgroundMode( QWidget::PaletteBackground );
#if QT_VERSION < 300
	DeleteButton->setFontPropagation( QWidget::SameFont );
	DeleteButton->setPalettePropagation( QWidget::SameFont );
		#endif
	DeleteButton->setText( tr("Delete"));
	DeleteButton->setAutoRepeat( FALSE );
	DeleteButton->setAutoResize( FALSE );
	DeleteButton->setToggleButton( FALSE );
	DeleteButton->setDefault( FALSE );
	DeleteButton->setAutoDefault( FALSE );
	DeleteButton->setIsMenuButton( FALSE );

	QPushButton* qtarch_PushButton_34;
	qtarch_PushButton_34 = new QPushButton( this, "PushButton_34" );
	qtarch_PushButton_34->setGeometry( 380, 520, 100, 30 );
	qtarch_PushButton_34->setMinimumSize( 0, 0 );
	qtarch_PushButton_34->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_34, SIGNAL(clicked()), SLOT(Help()) );
	qtarch_PushButton_34->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_34->setBackgroundMode( QWidget::PaletteBackground );
#if QT_VERSION < 300
	qtarch_PushButton_34->setFontPropagation( QWidget::SameFont );
	qtarch_PushButton_34->setPalettePropagation( QWidget::SameFont );
		#endif
	qtarch_PushButton_34->setText( tr("Help") );
	qtarch_PushButton_34->setAutoRepeat( FALSE );
	qtarch_PushButton_34->setAutoResize( FALSE );
	qtarch_PushButton_34->setToggleButton( FALSE );
	qtarch_PushButton_34->setDefault( FALSE );
	qtarch_PushButton_34->setAutoDefault( FALSE );
	qtarch_PushButton_34->setIsMenuButton( FALSE );

	
	ExitButton = new QPushButton( this, "PushButton_35" );
	ExitButton->setGeometry( 500, 520, 100, 30 );
	ExitButton->setMinimumSize( 0, 0 );
	ExitButton->setMaximumSize( 32767, 32767 );
	connect( ExitButton, SIGNAL(clicked()), SLOT(Exit()) );
	ExitButton->setFocusPolicy( QWidget::TabFocus );
	ExitButton->setBackgroundMode( QWidget::PaletteBackground );
#if QT_VERSION < 300
	ExitButton->setFontPropagation( QWidget::SameFont );
	ExitButton->setPalettePropagation( QWidget::SameFont );
		#endif
	ExitButton->setText( tr("Exit") );
	ExitButton->setAutoRepeat( FALSE );
	ExitButton->setAutoResize( FALSE );
	ExitButton->setToggleButton( FALSE );
	ExitButton->setDefault( FALSE );
	ExitButton->setAutoDefault( FALSE );
	ExitButton->setIsMenuButton( FALSE );

	LimitsButton = new QPushButton( this, "PushButton_36" );
	LimitsButton->setGeometry( 620, 240, 100, 30 );
	LimitsButton->setMinimumSize( 0, 0 );
	LimitsButton->setMaximumSize( 32767, 32767 );
	connect( LimitsButton, SIGNAL(clicked()), SLOT(AlarmLimits()) );
	LimitsButton->setFocusPolicy( QWidget::TabFocus );
	LimitsButton->setBackgroundMode( QWidget::PaletteBackground );
#if QT_VERSION < 300
	LimitsButton->setFontPropagation( QWidget::SameFont );
	LimitsButton->setPalettePropagation( QWidget::SameFont );
		#endif
	LimitsButton->setText( tr("Alarm Limits...") );
	LimitsButton->setAutoRepeat( FALSE );
	LimitsButton->setAutoResize( FALSE );
	LimitsButton->setToggleButton( FALSE );
	LimitsButton->setDefault( FALSE );
	LimitsButton->setAutoDefault( FALSE );
	LimitsButton->setIsMenuButton( FALSE );

	QPushButton* qtarch_PushButton_37;
	qtarch_PushButton_37 = new QPushButton( this, "PushButton_37" );
	qtarch_PushButton_37->setGeometry( 620, 340, 100, 30 );
	qtarch_PushButton_37->setMinimumSize( 0, 0 );
	qtarch_PushButton_37->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_37, SIGNAL(clicked()), SLOT(SetAll()) );
	qtarch_PushButton_37->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_37->setBackgroundMode( QWidget::PaletteBackground );
#if QT_VERSION < 300
	qtarch_PushButton_37->setFontPropagation( QWidget::SameFont );
	qtarch_PushButton_37->setPalettePropagation( QWidget::SameFont );
		#endif
	qtarch_PushButton_37->setText( tr("Set All") );
	qtarch_PushButton_37->setAutoRepeat( FALSE );
	qtarch_PushButton_37->setAutoResize( FALSE );
	qtarch_PushButton_37->setToggleButton( FALSE );
	qtarch_PushButton_37->setDefault( FALSE );
	qtarch_PushButton_37->setAutoDefault( FALSE );
	qtarch_PushButton_37->setIsMenuButton( FALSE );

	QPushButton* qtarch_PushButton_38;
	qtarch_PushButton_38 = new QPushButton( this, "PushButton_38" );
	qtarch_PushButton_38->setGeometry( 620, 390, 100, 30 );
	qtarch_PushButton_38->setMinimumSize( 0, 0 );
	qtarch_PushButton_38->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_38, SIGNAL(clicked()), SLOT(ClearAll()) );
	qtarch_PushButton_38->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_38->setBackgroundMode( QWidget::PaletteBackground );
#if QT_VERSION < 300
	qtarch_PushButton_38->setFontPropagation( QWidget::SameFont );
	qtarch_PushButton_38->setPalettePropagation( QWidget::SameFont );
		#endif
	qtarch_PushButton_38->setText( tr("Clear All") );
	qtarch_PushButton_38->setAutoRepeat( FALSE );
	qtarch_PushButton_38->setAutoResize( FALSE );
	qtarch_PushButton_38->setToggleButton( FALSE );
	qtarch_PushButton_38->setDefault( FALSE );
	qtarch_PushButton_38->setAutoDefault( FALSE );
	qtarch_PushButton_38->setIsMenuButton( FALSE );

	resize( 740,560 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


ReceipeCfgData::~ReceipeCfgData()
{
}


