/**********************************************************************
--- Qt Architect generated file ---
File: SampleCfgData.cpp
Last generated: Thu Jan 4 15:59:55 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#include <qt.h>
#include "SampleCfgData.h"
#include <common.h>

SampleCfgData::SampleCfgData(QWidget *parent, const char *name)
: QDialog(parent, name, TRUE, 208)
{
	QFrame *qtarch_Frame_6 = new QFrame(this, "Frame_6");
	qtarch_Frame_6->setGeometry(400, 300, 460, 90);
	qtarch_Frame_6->setMinimumSize(0, 0);
	qtarch_Frame_6->setMaximumSize(32767, 32767);
	qtarch_Frame_6->setFocusPolicy(QWidget::NoFocus);
	qtarch_Frame_6->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Frame_6->setFontPropagation(QWidget::SameFont);
	qtarch_Frame_6->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_Frame_6->setFrameStyle( 51 );
	qtarch_Frame_6->setLineWidth( 1 );
	qtarch_Frame_6->setMidLineWidth( 0 );
	qtarch_Frame_6->QFrame::setMargin( 0 );
	QFrame *qtarch_Frame_3 = new QFrame(this, "Frame_3");
	qtarch_Frame_3->setGeometry(400, 50, 460, 250);
	qtarch_Frame_3->setMinimumSize(0, 0);
	qtarch_Frame_3->setMaximumSize(32767, 32767);
	qtarch_Frame_3->setFocusPolicy(QWidget::NoFocus);
	qtarch_Frame_3->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Frame_3->setFontPropagation(QWidget::SameFont);
	qtarch_Frame_3->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_Frame_3->setFrameStyle( 51 );
	qtarch_Frame_3->setLineWidth( 2 );
	qtarch_Frame_3->setMidLineWidth( 0 );
	qtarch_Frame_3->QFrame::setMargin( 0 );
	ApplyButton = new QPushButton(this, "PushButton_13");
	ApplyButton->setGeometry(20, 540, 100, 30);
	ApplyButton->setMinimumSize(0, 0);
	ApplyButton->setMaximumSize(32767, 32767);
	ApplyButton->setFocusPolicy(QWidget::TabFocus);
	ApplyButton->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	ApplyButton->setFontPropagation(QWidget::SameFont);
	ApplyButton->setPalettePropagation(QWidget::SameFont);
		#endif
	ApplyButton->setText( tr( "Apply" ) );
	ApplyButton->setAutoRepeat( FALSE );
	ApplyButton->setAutoResize( FALSE );
	ApplyButton->setToggleButton( FALSE );
	ApplyButton->setDefault( FALSE );
	ApplyButton->setAutoDefault( FALSE );
	ApplyButton->setIsMenuButton( FALSE );
	connect(ApplyButton, SIGNAL(clicked()), SLOT(Apply()));
	NewButton = new QPushButton(this, "PushButton_14");
	NewButton->setGeometry(140, 540, 100, 30);
	NewButton->setMinimumSize(0, 0);
	NewButton->setMaximumSize(32767, 32767);
	NewButton->setFocusPolicy(QWidget::TabFocus);
	NewButton->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	NewButton->setFontPropagation(QWidget::SameFont);
	NewButton->setPalettePropagation(QWidget::SameFont);
		#endif
	NewButton->setText( tr( "New..." ) );
	NewButton->setAutoRepeat( FALSE );
	NewButton->setAutoResize( FALSE );
	NewButton->setToggleButton( FALSE );
	NewButton->setDefault( FALSE );
	NewButton->setAutoDefault( FALSE );
	NewButton->setIsMenuButton( FALSE );
	connect(NewButton, SIGNAL(clicked()), SLOT(New()));
	DeleteButton = new QPushButton(this, "PushButton_15");
	DeleteButton->setGeometry(260, 540, 100, 30);
	DeleteButton->setMinimumSize(0, 0);
	DeleteButton->setMaximumSize(32767, 32767);
	DeleteButton->setFocusPolicy(QWidget::TabFocus);
	DeleteButton->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	DeleteButton->setFontPropagation(QWidget::SameFont);
	DeleteButton->setPalettePropagation(QWidget::SameFont);
		#endif
	DeleteButton->setText( tr( "Delete" ) );
	DeleteButton->setAutoRepeat( FALSE );
	DeleteButton->setAutoResize( FALSE );
	DeleteButton->setToggleButton( FALSE );
	DeleteButton->setDefault( FALSE );
	DeleteButton->setAutoDefault( FALSE );
	DeleteButton->setIsMenuButton( FALSE );
	connect(DeleteButton, SIGNAL(clicked()), SLOT(Delete()));
	QPushButton *qtarch_PushButton_16 = new QPushButton(this, "PushButton_16");
	qtarch_PushButton_16->setGeometry(760, 540, 100, 30);
	qtarch_PushButton_16->setMinimumSize(0, 0);
	qtarch_PushButton_16->setMaximumSize(32767, 32767);
	qtarch_PushButton_16->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_16->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_16->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_16->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_PushButton_16->setText( tr( "Exit" ) );
	qtarch_PushButton_16->setAutoRepeat( FALSE );
	qtarch_PushButton_16->setAutoResize( FALSE );
	qtarch_PushButton_16->setToggleButton( FALSE );
	qtarch_PushButton_16->setDefault( FALSE );
	qtarch_PushButton_16->setAutoDefault( FALSE );
	qtarch_PushButton_16->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_16, SIGNAL(clicked()), SLOT(reject()));
	QPushButton *qtarch_PushButton_17 = new QPushButton(this, "PushButton_17");
	qtarch_PushButton_17->setGeometry(630, 540, 100, 30);
	qtarch_PushButton_17->setMinimumSize(0, 0);
	qtarch_PushButton_17->setMaximumSize(32767, 32767);
	qtarch_PushButton_17->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_17->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_17->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_17->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_PushButton_17->setText( tr( "Help" ) );
	qtarch_PushButton_17->setAutoRepeat( FALSE );
	qtarch_PushButton_17->setAutoResize( FALSE );
	qtarch_PushButton_17->setToggleButton( FALSE );
	qtarch_PushButton_17->setDefault( FALSE );
	qtarch_PushButton_17->setAutoDefault( FALSE );
	qtarch_PushButton_17->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_17, SIGNAL(clicked()), SLOT(Help()));
	Name = new QLabel(this, "Label_13");
	Name->setGeometry(400, 10, 460, 40);
	Name->setMinimumSize(0, 0);
	Name->setMaximumSize(32767, 32767);
	Name->setFocusPolicy(QWidget::NoFocus);
	Name->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	Name->setFontPropagation(QWidget::SameFont);
	Name->setPalettePropagation(QWidget::SameFont);
		#endif
	Name->setFrameStyle( 51 );
	Name->setLineWidth( 2 );
	Name->setMidLineWidth( 0 );
	Name->QFrame::setMargin( 0 );
	Name->setText( "" );
	Name->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	Name->setMargin( 0 );
	QLabel *qtarch_Label_14 = new QLabel(this, "Label_14");
	qtarch_Label_14->setGeometry(420, 110, 70, 30);
	qtarch_Label_14->setMinimumSize(0, 0);
	qtarch_Label_14->setMaximumSize(32767, 32767);
	qtarch_Label_14->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_14->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_14->setFontPropagation(QWidget::SameFont);
	qtarch_Label_14->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_Label_14->setFrameStyle( 0 );
	qtarch_Label_14->setLineWidth( 1 );
	qtarch_Label_14->setMidLineWidth( 0 );
	qtarch_Label_14->QFrame::setMargin( 0 );
	qtarch_Label_14->setText( tr( "Unit" ) );
	qtarch_Label_14->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_14->setMargin( 0 );
	Unit = new QComboBox(FALSE, this, "ComboBox_6");
	Unit->setGeometry(500, 110, 340, 30);
	Unit->setMinimumSize(0, 0);
	Unit->setMaximumSize(32767, 32767);
	Unit->setFocusPolicy(QWidget::StrongFocus);
	Unit->setBackgroundMode(QWidget::NoBackground);
#if QT_VERSION < 300
	Unit->setFontPropagation(QWidget::SameFont);
	Unit->setPalettePropagation(QWidget::SameFont);
		#endif
	Unit->setSizeLimit( 10 );
	Unit->setAutoResize( FALSE );
	Unit->setMaxCount( 2147483647 );
	Unit->setAutoCompletion( FALSE );
	connect(Unit, SIGNAL(activated(int)), SLOT(UnitChanged(int)));
	connect(Unit, SIGNAL(highlighted(int)), SLOT(UnitChanged(int)));
	QLabel *qtarch_Label_16 = new QLabel(this, "Label_16");
	qtarch_Label_16->setGeometry(420, 60, 70, 30);
	qtarch_Label_16->setMinimumSize(0, 0);
	qtarch_Label_16->setMaximumSize(32767, 32767);
	qtarch_Label_16->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_16->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_16->setFontPropagation(QWidget::SameFont);
	qtarch_Label_16->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_Label_16->setFrameStyle( 0 );
	qtarch_Label_16->setLineWidth( 1 );
	qtarch_Label_16->setMidLineWidth( 0 );
	qtarch_Label_16->QFrame::setMargin( 0 );
	qtarch_Label_16->setText( tr( "Comment" ) );
	qtarch_Label_16->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_16->setMargin( 0 );
	Comment = new QLineEdit(this, "LineEdit_5");
	Comment->setGeometry(500, 60, 340, 30);
	Comment->setMinimumSize(0, 0);
	Comment->setMaximumSize(32767, 32767);
	Comment->setFocusPolicy(QWidget::StrongFocus);
	Comment->setBackgroundMode(QWidget::PaletteBase);
#if QT_VERSION < 300
	Comment->setFontPropagation(QWidget::SameFont);
	Comment->setPalettePropagation(QWidget::SameFont);
		#endif
	Comment->setText( tr(NONE_STR) );
	Comment->setMaxLength( 128 );
	Comment->setFrame( QLineEdit::Normal );
	Comment->setFrame( TRUE );
	Comment->setAlignment( AlignLeft );
	QLabel *qtarch_Label_17 = new QLabel(this, "Label_17");
	qtarch_Label_17->setGeometry(420, 160, 70, 30);
	qtarch_Label_17->setMinimumSize(0, 0);
	qtarch_Label_17->setMaximumSize(32767, 32767);
	qtarch_Label_17->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_17->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_17->setFontPropagation(QWidget::SameFont);
	qtarch_Label_17->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_Label_17->setFrameStyle( 0 );
	qtarch_Label_17->setLineWidth( 1 );
	qtarch_Label_17->setMidLineWidth( 0 );
	qtarch_Label_17->QFrame::setMargin( 0 );
	qtarch_Label_17->setText( tr( "Type" ) );
	qtarch_Label_17->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_17->setMargin( 0 );
	Type = new QComboBox(FALSE, this, "ComboBox_7");
	Type->setGeometry(500, 160, 340, 30);
	Type->setMinimumSize(0, 0);
	Type->setMaximumSize(32767, 32767);
	Type->setFocusPolicy(QWidget::StrongFocus);
	Type->setBackgroundMode(QWidget::NoBackground);
#if QT_VERSION < 300
	Type->setFontPropagation(QWidget::SameFont);
	Type->setPalettePropagation(QWidget::SameFont);
		#endif
	Type->setSizeLimit( 10 );
	Type->setAutoResize( FALSE );
	Type->setMaxCount( 2147483647 );
	Type->setAutoCompletion( FALSE );
	connect(Type, SIGNAL(activated(int)), SLOT(TypeChanged(int)));
	connect(Type, SIGNAL(highlighted(int)), SLOT(TypeChanged(int)));
	QLabel *qtarch_Label_18 = new QLabel(this, "Label_18");
	qtarch_Label_18->setGeometry(420, 210, 80, 30);
	qtarch_Label_18->setMinimumSize(0, 0);
	qtarch_Label_18->setMaximumSize(32767, 32767);
	qtarch_Label_18->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_18->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_18->setFontPropagation(QWidget::SameFont);
	qtarch_Label_18->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_Label_18->setFrameStyle( 0 );
	qtarch_Label_18->setLineWidth( 1 );
	qtarch_Label_18->setMidLineWidth( 0 );
	qtarch_Label_18->QFrame::setMargin( 0 );
	qtarch_Label_18->setText( tr( "Input Index" ) );
	qtarch_Label_18->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_18->setMargin( 0 );
	InputIndex = new QComboBox(FALSE, this, "ComboBox_8");
	InputIndex->setGeometry(500, 210, 140, 30);
	InputIndex->setMinimumSize(0, 0);
	InputIndex->setMaximumSize(32767, 32767);
	InputIndex->setFocusPolicy(QWidget::StrongFocus);
	InputIndex->setBackgroundMode(QWidget::NoBackground);
#if QT_VERSION < 300
	InputIndex->setFontPropagation(QWidget::SameFont);
	InputIndex->setPalettePropagation(QWidget::SameFont);
		#endif
	InputIndex->setSizeLimit( 10 );
	InputIndex->setAutoResize( FALSE );
	InputIndex->setMaxCount( 2147483647 );
	InputIndex->setAutoCompletion( FALSE );
	connect(InputIndex, SIGNAL(activated(int)), SLOT(IpIndexChanged(int)));
	connect(InputIndex, SIGNAL(highlighted(int)), SLOT(IpIndexChanged(int)));
	QLabel *qtarch_Label_19 = new QLabel(this, "Label_19");
	qtarch_Label_19->setGeometry(420, 260, 70, 30);
	qtarch_Label_19->setMinimumSize(0, 0);
	qtarch_Label_19->setMaximumSize(32767, 32767);
	qtarch_Label_19->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_19->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_19->setFontPropagation(QWidget::SameFont);
	qtarch_Label_19->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_Label_19->setFrameStyle( 0 );
	qtarch_Label_19->setLineWidth( 1 );
	qtarch_Label_19->setMidLineWidth( 0 );
	qtarch_Label_19->QFrame::setMargin( 0 );
	qtarch_Label_19->setText( tr( "Units" ) );
	qtarch_Label_19->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_19->setMargin( 0 );
	Units = new QComboBox(TRUE, this, "ComboBox_9");
	Units->setGeometry(500, 260, 140, 30);
	Units->setMinimumSize(0, 0);
	Units->setMaximumSize(32767, 32767);
	Units->setFocusPolicy(QWidget::StrongFocus);
	Units->setBackgroundMode(QWidget::NoBackground);
#if QT_VERSION < 300
	Units->setFontPropagation(QWidget::SameFont);
	Units->setPalettePropagation(QWidget::SameFont);
		#endif
	Units->setInsertionPolicy( QComboBox::AtBottom );
	Units->setSizeLimit( 10 );
	Units->setAutoResize( FALSE );
	Units->insertItem( tr( "spi" ) );
	Units->insertItem( tr( "dpi" ) );
	Units->insertItem( tr( "mA" ) );
	Units->insertItem( tr( "A" ) );
	Units->insertItem( tr( "Volts" ) );
	Units->insertItem( tr( "N/cuft" ) );
	Units->insertItem( tr( "N/m3" ) );
	Units->insertItem( tr( "Pa" ) );
	Units->insertItem( tr( "C" ) );
	Units->insertItem( tr( "F" ) );
	Units->insertItem( tr( "%" ) );
	Units->insertItem( tr( "m/s" ) );
	Units->insertItem( tr( "g/l" ) );
	Units->insertItem( tr( "l" ) );
	Units->insertItem( tr( "" ) ); //Nessuna unita' di misura
	Units->setMaxCount( 2147483647 );
	Units->setAutoCompletion( TRUE );
	Enabled = new QCheckBox(this, "CheckBox_6");
	Enabled->setGeometry(410, 310, 100, 30);
	Enabled->setMinimumSize(0, 0);
	Enabled->setMaximumSize(32767, 32767);
	Enabled->setFocusPolicy(QWidget::TabFocus);
	Enabled->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	Enabled->setFontPropagation(QWidget::SameFont);
	Enabled->setPalettePropagation(QWidget::SameFont);
		#endif
	Enabled->setText( tr( "Enabled" ) );
	Enabled->setAutoRepeat( FALSE );
	Enabled->setAutoResize( FALSE );
	Enabled->setChecked( FALSE );
	Fileable = new QCheckBox(this, "CheckBox_7");
	Fileable->setGeometry(590, 310, 100, 30);
	Fileable->setMinimumSize(0, 0);
	Fileable->setMaximumSize(32767, 32767);
	Fileable->setFocusPolicy(QWidget::TabFocus);
	Fileable->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	Fileable->setFontPropagation(QWidget::SameFont);
	Fileable->setPalettePropagation(QWidget::SameFont);
	#endif
	Fileable->setText( tr( "Fileable" ) );
	Fileable->setAutoRepeat( FALSE );
	Fileable->setAutoResize( FALSE );
	Fileable->setChecked( FALSE );
	QPushButton *qtarch_PushButton_18 = new QPushButton(this, "PushButton_18");
	qtarch_PushButton_18->setGeometry(740, 210, 100, 30);
	qtarch_PushButton_18->setMinimumSize(0, 0);
	qtarch_PushButton_18->setMaximumSize(32767, 32767);
	qtarch_PushButton_18->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_18->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_18->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_18->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_18->setText( tr( "Limits..." ) );
	qtarch_PushButton_18->setAutoRepeat( FALSE );
	qtarch_PushButton_18->setAutoResize( FALSE );
	qtarch_PushButton_18->setToggleButton( FALSE );
	qtarch_PushButton_18->setDefault( FALSE );
	qtarch_PushButton_18->setAutoDefault( FALSE );
	qtarch_PushButton_18->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_18, SIGNAL(clicked()), SLOT(Limits()));
	QPushButton *qtarch_PushButton_19 = new QPushButton(this, "PushButton_19");
	qtarch_PushButton_19->setGeometry(740, 260, 100, 30);
	qtarch_PushButton_19->setMinimumSize(0, 0);
	qtarch_PushButton_19->setMaximumSize(32767, 32767);
	qtarch_PushButton_19->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_19->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_19->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_19->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_19->setText( tr( "Actions..." ) );
	qtarch_PushButton_19->setAutoRepeat( FALSE );
	qtarch_PushButton_19->setAutoResize( FALSE );
	qtarch_PushButton_19->setToggleButton( FALSE );
	qtarch_PushButton_19->setDefault( FALSE );
	qtarch_PushButton_19->setAutoDefault( FALSE );
	qtarch_PushButton_19->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_19, SIGNAL(clicked()), SLOT(Actions()));
	ConfigFrame = new QFrame(this, "Frame_5");
	ConfigFrame->setGeometry(410, 400, 450, 120);
	ConfigFrame->setMinimumSize(0, 0);
	ConfigFrame->setMaximumSize(32767, 32767);
	ConfigFrame->setFocusPolicy(QWidget::TabFocus);
	ConfigFrame->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	ConfigFrame->setFontPropagation(QWidget::SameFont);
	ConfigFrame->setPalettePropagation(QWidget::SameFont);
	#endif
	ConfigFrame->setFrameStyle( 0 );
	ConfigFrame->setLineWidth( 1 );
	ConfigFrame->setMidLineWidth( 0 );
	ConfigFrame->QFrame::setMargin( 0 );
	LogMode = new QCheckBox(this, "CheckBox_8");
	LogMode->setGeometry(410, 350, 180, 30);
	LogMode->setMinimumSize(0, 0);
	LogMode->setMaximumSize(32767, 32767);
	LogMode->setFocusPolicy(QWidget::TabFocus);
	LogMode->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	LogMode->setFontPropagation(QWidget::SameFont);
	LogMode->setPalettePropagation(QWidget::SameFont);
	#endif
	LogMode->setText( tr( "Use Log Graph Scales" ) );
	LogMode->setAutoRepeat( FALSE );
	LogMode->setAutoResize( FALSE );
	LogMode->setChecked( FALSE );
	Retrigger = new QCheckBox(this, "CheckBox_9");
	Retrigger->setGeometry(590, 350, 170, 30);
	Retrigger->setMinimumSize(0, 0);
	Retrigger->setMaximumSize(32767, 32767);
	Retrigger->setFocusPolicy(QWidget::TabFocus);
	Retrigger->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	Retrigger->setFontPropagation(QWidget::SameFont);
	Retrigger->setPalettePropagation(QWidget::SameFont);
	#endif
	Retrigger->setText( tr( "Retriggerable Alarms" ) );
	Retrigger->setAutoRepeat( FALSE );
	Retrigger->setAutoResize( FALSE );
	Retrigger->setChecked( FALSE );
	AlarmThreshold = new QSpinBox(this, "SpinBox_1");
	AlarmThreshold->setGeometry(770, 350, 50, 30);
	AlarmThreshold->setMinimumSize(0, 0);
	AlarmThreshold->setMaximumSize(32767, 32767);
	AlarmThreshold->setFocusPolicy(QWidget::StrongFocus);
	AlarmThreshold->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	AlarmThreshold->setFontPropagation(QWidget::SameFont);
	AlarmThreshold->setPalettePropagation(QWidget::SameFont);
	AlarmThreshold->setFrameStyle( 50 );
	AlarmThreshold->setLineWidth( 2 );
	AlarmThreshold->setMidLineWidth( 0 );
	AlarmThreshold->QFrame::setMargin( 0 );
		#endif
	AlarmThreshold->setRange( 0, 10 );
	AlarmThreshold->setSteps( 1, 0 );
	AlarmThreshold->setPrefix( "" );
	AlarmThreshold->setSuffix( "" );
	AlarmThreshold->setSpecialValueText( "" );
	AlarmThreshold->setWrapping( TRUE );
	QLabel *qtarch_Label_21 = new QLabel(this, "Label_21");
	qtarch_Label_21->setGeometry(730, 310, 120, 30);
	qtarch_Label_21->setMinimumSize(0, 0);
	qtarch_Label_21->setMaximumSize(32767, 32767);
	qtarch_Label_21->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_21->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_21->setFontPropagation(QWidget::SameFont);
	qtarch_Label_21->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_21->setFrameStyle( 0 );
	qtarch_Label_21->setLineWidth( 1 );
	qtarch_Label_21->setMidLineWidth( 0 );
	qtarch_Label_21->QFrame::setMargin( 0 );
	qtarch_Label_21->setText( tr( "Alarm Threshold" ) );
	qtarch_Label_21->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_21->setMargin( 0 );
	List = new QListView(this, "ListView_1");
	List->setGeometry(10, 10, 370, 510);
	List->setMinimumSize(0, 0);
	List->setMaximumSize(32767, 32767);
	List->setFocusPolicy( QWidget::StrongFocus );
	List->setBackgroundMode(QWidget::PaletteBackground);//
#if QT_VERSION < 300
	List->setFontPropagation(QWidget::SameFont);//
	List->setPalettePropagation(QWidget::SameFont);//
	#endif
	List->setFrameStyle( 50 );
	List->setLineWidth( 2 );
	List->setMidLineWidth( 0 );
	List->QFrame::setMargin( 0 );
	List->setResizePolicy( QScrollView::Manual );//
	List->setVScrollBarMode( QScrollView::Auto );//
	List->setHScrollBarMode( QScrollView::Auto );//
	List->setTreeStepSize( 20 );
	List->setMultiSelection( FALSE );
	List->setAllColumnsShowFocus( FALSE );
	List->setItemMargin( 1 );
	List->setRootIsDecorated( FALSE );
	List->addColumn( tr( "Name" ), -1 );
	List->setColumnWidthMode( 0, QListView::Maximum );
	List->setColumnAlignment( 0, 1 );
	List->addColumn( tr( "Comment" ), -1 );
	List->setColumnWidthMode( 1, QListView::Maximum );
	List->setColumnAlignment( 1, 1 );
	//connect(List, SIGNAL(currentChanged(QListViewItem*)),this, SLOT(Changed(QListViewItem*)));
	connect (List,SIGNAL (mouseButtonClicked(int, QListViewItem*, const QPoint &, int)),
	this, SLOT (ListClicked(int, QListViewItem*, const QPoint &, int)));

	connect (List,SIGNAL (returnPressed(QListViewItem*)),this, SLOT (Changed(QListViewItem*)));

	RenameButton = new QPushButton(this, "PushButton_20");
	RenameButton->setGeometry(430, 540, 100, 30);
	RenameButton->setMinimumSize(0, 0);
	RenameButton->setMaximumSize(32767, 32767);
	RenameButton->setFocusPolicy(QWidget::TabFocus);
	RenameButton->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	RenameButton->setFontPropagation(QWidget::SameFont);
	RenameButton->setPalettePropagation(QWidget::SameFont);
	#endif
	RenameButton->setText( tr( "Rename" ) );
	RenameButton->setAutoRepeat( FALSE );
	RenameButton->setAutoResize( FALSE );
	RenameButton->setToggleButton( FALSE );
	RenameButton->setDefault( FALSE );
	RenameButton->setAutoDefault( FALSE );
	RenameButton->setIsMenuButton( FALSE );
	connect(RenameButton, SIGNAL(clicked()), SLOT(Rename()));
	resize(880,590);
	setMinimumSize(0, 0);
	setMaximumSize(32767, 32767);
}
SampleCfgData::~SampleCfgData()
{
}

