/**********************************************************************
--- Qt Architect generated file ---
File: SystemConfigureData.cpp
Last generated: Thu Jan 4 16:20:37 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#include <qpixmap.h>
#include <qlayout.h>
#include "SystemConfigureData.h"
#include <qlabel.h>
#include <qpushbutton.h>
SystemConfigureData::SystemConfigureData(QWidget *parent, const char *name)
: QDialog(parent, name, TRUE, 208)
{
	QPushButton *qtarch_PushButton_1 = new QPushButton(this, "PushButton_1");
	qtarch_PushButton_1->setGeometry(20, 100, 100, 30);
	qtarch_PushButton_1->setMinimumSize(0, 0);
	qtarch_PushButton_1->setMaximumSize(32767, 32767);
	qtarch_PushButton_1->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_1->setBackgroundMode(QWidget::PaletteButton);
	#if QT_VERSION < 300
	qtarch_PushButton_1->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_1->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_1->setText( tr( "Ok" ) );
	qtarch_PushButton_1->setAutoRepeat( FALSE );
	qtarch_PushButton_1->setAutoResize( FALSE );
	qtarch_PushButton_1->setToggleButton( FALSE );
	qtarch_PushButton_1->setDefault( FALSE );
	qtarch_PushButton_1->setAutoDefault( FALSE );
	qtarch_PushButton_1->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_1, SIGNAL(clicked()), SLOT(OkClicked()));
	QPushButton *qtarch_PushButton_2 = new QPushButton(this, "PushButton_2");
	qtarch_PushButton_2->setGeometry(340, 100, 100, 30);
	qtarch_PushButton_2->setMinimumSize(0, 0);
	qtarch_PushButton_2->setMaximumSize(32767, 32767);
	qtarch_PushButton_2->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_2->setBackgroundMode(QWidget::PaletteButton);
	#if QT_VERSION < 300
	qtarch_PushButton_2->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_2->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_2->setText( tr( "Cancel" ) );
	qtarch_PushButton_2->setAutoRepeat( FALSE );
	qtarch_PushButton_2->setAutoResize( FALSE );
	qtarch_PushButton_2->setToggleButton( FALSE );
	qtarch_PushButton_2->setDefault( FALSE );
	qtarch_PushButton_2->setAutoDefault( FALSE );
	qtarch_PushButton_2->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_2, SIGNAL(clicked()), SLOT(reject()));
	QLabel *qtarch_Label_1 = new QLabel(this, "Label_1");
	qtarch_Label_1->setGeometry(20, 30, 150, 30);
	qtarch_Label_1->setMinimumSize(0, 0);
	qtarch_Label_1->setMaximumSize(32767, 32767);
	qtarch_Label_1->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_1->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	qtarch_Label_1->setFontPropagation(QWidget::SameFont);
	qtarch_Label_1->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_1->setFrameStyle( 0 );
	qtarch_Label_1->setLineWidth( 1 );
	qtarch_Label_1->setMidLineWidth( 0 );
	qtarch_Label_1->QFrame::setMargin( 0 );
	qtarch_Label_1->setText( tr( "Min. Disc Space (Mb)" ) );
	qtarch_Label_1->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_1->setMargin( 0 );
	MinDiskSpace = new QSpinBox(this, "SpinBox_1");
	MinDiskSpace->setGeometry(170, 30, 90, 30);
	MinDiskSpace->setMinimumSize(0, 0);
	MinDiskSpace->setMaximumSize(32767, 32767);
	MinDiskSpace->setFocusPolicy(QWidget::StrongFocus);
	MinDiskSpace->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	MinDiskSpace->setFontPropagation(QWidget::SameFont);
	MinDiskSpace->setPalettePropagation(QWidget::SameFont);
	MinDiskSpace->setFrameStyle( 50 );
	MinDiskSpace->setLineWidth( 2 );
	MinDiskSpace->setMidLineWidth( 0 );
	MinDiskSpace->QFrame::setMargin( 0 );
	#endif
	MinDiskSpace->setRange( 100, 1000 );
	MinDiskSpace->setSteps( 100, 0 );
	MinDiskSpace->setPrefix( "" );
	MinDiskSpace->setSuffix( "" );
	MinDiskSpace->setSpecialValueText( "" );
	MinDiskSpace->setWrapping( TRUE );
	QLabel *qtarch_Label_3 = new QLabel(this, "Label_3");
	qtarch_Label_3->setGeometry(270, 30, 50, 30);
	qtarch_Label_3->setMinimumSize(0, 0);
	qtarch_Label_3->setMaximumSize(32767, 32767);
	qtarch_Label_3->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_3->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	qtarch_Label_3->setFontPropagation(QWidget::SameFont);
	qtarch_Label_3->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_3->setFrameStyle( 0 );
	qtarch_Label_3->setLineWidth( 1 );
	qtarch_Label_3->setMidLineWidth( 0 );
	qtarch_Label_3->QFrame::setMargin( 0 );
	qtarch_Label_3->setText( tr( "Drive " ) );
	qtarch_Label_3->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_3->setMargin( 0 );
	Drive = new QComboBox(FALSE, this, "ComboBox_1");
	Drive->setGeometry(330, 30, 100, 30);
	Drive->setMinimumSize(0, 0);
	Drive->setMaximumSize(32767, 32767);
	Drive->setFocusPolicy(QWidget::StrongFocus);
	Drive->setBackgroundMode(QWidget::PaletteButton);
	#if QT_VERSION < 300
	Drive->setFontPropagation(QWidget::SameFont);
	Drive->setPalettePropagation(QWidget::SameFont);
	#endif
	Drive->setSizeLimit( 10 );
	Drive->setAutoResize( FALSE );
	Drive->insertItem( tr( "hda1" ) );
	Drive->insertItem( tr( "hda2" ) );
	Drive->insertItem( tr( "hda3" ) );
	Drive->insertItem( tr( "hda4" ) );
	Drive->insertItem( tr( "hdb1" ) );
	Drive->insertItem( tr( "hdb2" ) );
	Drive->insertItem( tr( "hdb3" ) );
	Drive->insertItem( tr( "hdb4" ) );
	Drive->insertItem( tr( "hdc1" ) );
	Drive->insertItem( tr( "hdc2" ) );
	Drive->insertItem( tr( "hdc3" ) );
	Drive->insertItem( tr( "hdc4" ) );
	Drive->insertItem( tr( "hdd1" ) );
	Drive->insertItem( tr( "hdd2" ) );
	Drive->insertItem( tr( "hdd3" ) );
	Drive->insertItem( tr( "hdd4" ) );
	Drive->setMaxCount( 2147483647 );
	Drive->setAutoCompletion( FALSE );
	QPushButton *qtarch_PushButton_3 = new QPushButton(this, "PushButton_3");
	qtarch_PushButton_3->setGeometry(190, 100, 100, 30);
	qtarch_PushButton_3->setMinimumSize(0, 0);
	qtarch_PushButton_3->setMaximumSize(32767, 32767);
	qtarch_PushButton_3->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_3->setBackgroundMode(QWidget::PaletteButton);
	#if QT_VERSION < 300
	qtarch_PushButton_3->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_3->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_3->setText( tr( "Help..." ) );
	qtarch_PushButton_3->setAutoRepeat( FALSE );
	qtarch_PushButton_3->setAutoResize( FALSE );
	qtarch_PushButton_3->setToggleButton( FALSE );
	qtarch_PushButton_3->setDefault( FALSE );
	qtarch_PushButton_3->setAutoDefault( FALSE );
	qtarch_PushButton_3->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_3, SIGNAL(clicked()), SLOT(Help()));
	resize(450,150);
	setMinimumSize(0, 0);
	setMaximumSize(32767, 32767);
}
SystemConfigureData::~SystemConfigureData()
{
}

