/**********************************************************************
--- Qt Architect generated file ---
File: LoginDlgData.cpp
Last generated: Fri Feb 16 15:10:17 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#include <qt.h>
#include "LoginDlgData.h"
LoginDlgData::LoginDlgData(QWidget *parent, const char *name)
: QDialog(parent, name, TRUE, 208)
{
	QFrame *qtarch_Frame_1 = new QFrame(this, "Frame_1");
	qtarch_Frame_1->setGeometry(10, 20, 310, 130);
	qtarch_Frame_1->setMinimumSize(0, 0);
	qtarch_Frame_1->setMaximumSize(32767, 32767);
	qtarch_Frame_1->setFocusPolicy(QWidget::NoFocus);
	qtarch_Frame_1->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Frame_1->setFontPropagation(QWidget::SameFont);
	qtarch_Frame_1->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Frame_1->setFrameStyle( 50 );
	qtarch_Frame_1->setLineWidth( 1 );
	qtarch_Frame_1->setMidLineWidth( 0 );
	qtarch_Frame_1->QFrame::setMargin( 0 );
	OkButton = new QPushButton(this, "PushButton_1");
	OkButton->setGeometry(10, 180, 100, 30);
	OkButton->setMinimumSize(0, 0);
	OkButton->setMaximumSize(32767, 32767);
	OkButton->setFocusPolicy(QWidget::TabFocus);
	OkButton->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	OkButton->setFontPropagation(QWidget::SameFont);
	OkButton->setPalettePropagation(QWidget::SameFont);
	#endif
	OkButton->setText( tr( "Ok" ) );
	OkButton->setAutoRepeat( FALSE );
	OkButton->setAutoResize( FALSE );
	OkButton->setToggleButton( FALSE );
	OkButton->setDefault( TRUE );
	OkButton->setAutoDefault( TRUE );
	OkButton->setIsMenuButton( FALSE );
	connect(OkButton, SIGNAL(clicked()), SLOT(Okclicked()));
	QPushButton *qtarch_PushButton_2 = new QPushButton(this, "PushButton_2");
	qtarch_PushButton_2->setGeometry(220, 180, 100, 30);
	qtarch_PushButton_2->setMinimumSize(0, 0);
	qtarch_PushButton_2->setMaximumSize(32767, 32767);
	qtarch_PushButton_2->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_2->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_2->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_2->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_2->setText( tr( "Cancel" ) );
	qtarch_PushButton_2->setAutoRepeat( FALSE );
	qtarch_PushButton_2->setAutoResize( FALSE );
	qtarch_PushButton_2->setToggleButton( FALSE );
	qtarch_PushButton_2->setDefault( FALSE );
	qtarch_PushButton_2->setAutoDefault( TRUE );
	qtarch_PushButton_2->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_2, SIGNAL(clicked()), SLOT(reject()));
	Username = new QLineEdit(this, "LineEdit_1");
	Username->setGeometry(120, 30, 170, 30);
	Username->setMinimumSize(0, 0);
	Username->setMaximumSize(32767, 32767);
	Username->setFocusPolicy(QWidget::StrongFocus);
	Username->setBackgroundMode(QWidget::PaletteBase);
#if QT_VERSION < 300
	Username->setFontPropagation(QWidget::SameFont);
	Username->setPalettePropagation(QWidget::SameFont);
	#endif
	Username->setText( "" );
	Username->setMaxLength( 32 );
	Username->setFrame( QLineEdit::Normal );
	Username->setFrame( TRUE );
	Username->setAlignment( AlignLeft );
	connect(Username, SIGNAL(textChanged(const QString&)), SLOT(NameChanged(const QString&)));
	QLabel *qtarch_Label_1 = new QLabel(this, "Label_1");
	qtarch_Label_1->setGeometry(30, 30, 80, 30);
	qtarch_Label_1->setMinimumSize(0, 0);
	qtarch_Label_1->setMaximumSize(32767, 32767);
	qtarch_Label_1->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_1->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_1->setFontPropagation(QWidget::SameFont);
	qtarch_Label_1->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_1->setFrameStyle( 0 );
	qtarch_Label_1->setLineWidth( 1 );
	qtarch_Label_1->setMidLineWidth( 0 );
	qtarch_Label_1->QFrame::setMargin( 0 );
	qtarch_Label_1->setText( tr( "Name" ) );
	qtarch_Label_1->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_1->setMargin( 0 );
	QLabel *qtarch_Label_2 = new QLabel(this, "Label_2");
	qtarch_Label_2->setGeometry(30, 80, 80, 30);
	qtarch_Label_2->setMinimumSize(0, 0);
	qtarch_Label_2->setMaximumSize(32767, 32767);
	qtarch_Label_2->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_2->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_2->setFontPropagation(QWidget::SameFont);
	qtarch_Label_2->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_2->setFrameStyle( 0 );
	qtarch_Label_2->setLineWidth( 1 );
	qtarch_Label_2->setMidLineWidth( 0 );
	qtarch_Label_2->QFrame::setMargin( 0 );
	qtarch_Label_2->setText( tr( "Password" ) );
	qtarch_Label_2->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_2->setMargin( 0 );
	Password = new QLineEdit(this, "LineEdit_2");
	Password->setGeometry(120, 80, 170, 30);
	Password->setMinimumSize(0, 0);
	Password->setMaximumSize(32767, 32767);
	Password->setFocusPolicy(QWidget::StrongFocus);
	Password->setBackgroundMode(QWidget::PaletteBase);
#if QT_VERSION < 300
	Password->setFontPropagation(QWidget::SameFont);
	Password->setPalettePropagation(QWidget::SameFont);
	#endif
	Password->setText( "" );
	Password->setMaxLength( 12 );
	Password->setFrame( QLineEdit::NoEcho );
	Password->setFrame( TRUE );
	Password->setAlignment( AlignLeft );
	resize(330,220);
	setMinimumSize(0, 0);
	setMaximumSize(32767, 32767);
}
LoginDlgData::~LoginDlgData()
{
}

