/**********************************************************************
--- Qt Architect generated file ---
File: MultiTraceDlgData.h
Last generated: Wed Jun 28 13:48:36 2000
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef MultiTraceDlgData_included
#define MultiTraceDlgData_included
#include <qt.h>
class MultiTraceDlgData : public QWidget
{
	Q_OBJECT
	public:
	MultiTraceDlgData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~MultiTraceDlgData();
	protected:
	QListView *List;
};
#endif // MultiTraceDlgData_included

