/**********************************************************************
--- Qt Architect generated file ---
File: NewPasswordData.cpp
Last generated: Fri Feb 16 15:11:34 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#include <qt.h>
#include "NewPasswordData.h"
NewPasswordData::NewPasswordData(QWidget *parent, const char *name)
: QDialog(parent, name, TRUE, 208)
{
	QLabel *qtarch_Label_1 = new QLabel(this, "Label_1");
	qtarch_Label_1->setGeometry(20, 20, 110, 30);
	qtarch_Label_1->setMinimumSize(0, 0);
	qtarch_Label_1->setMaximumSize(32767, 32767);
	qtarch_Label_1->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_1->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_1->setFontPropagation(QWidget::SameFont);
	qtarch_Label_1->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_1->setFrameStyle( 0 );
	qtarch_Label_1->setLineWidth( 1 );
	qtarch_Label_1->setMidLineWidth( 0 );
	qtarch_Label_1->QFrame::setMargin( 0 );
	qtarch_Label_1->setText( tr( "New Password" ) );
	qtarch_Label_1->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_1->setMargin( 0 );
	QLabel *qtarch_Label_2 = new QLabel(this, "Label_2");
	qtarch_Label_2->setGeometry(20, 60, 110, 30);
	qtarch_Label_2->setMinimumSize(0, 0);
	qtarch_Label_2->setMaximumSize(32767, 32767);
	qtarch_Label_2->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_2->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_2->setFontPropagation(QWidget::SameFont);
	qtarch_Label_2->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_2->setFrameStyle( 0 );
	qtarch_Label_2->setLineWidth( 1 );
	qtarch_Label_2->setMidLineWidth( 0 );
	qtarch_Label_2->QFrame::setMargin( 0 );
	qtarch_Label_2->setText( tr( "Confirm" ) );
	qtarch_Label_2->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_2->setMargin( 0 );
	Password1 = new QLineEdit(this, "LineEdit_1");
	Password1->setGeometry(130, 20, 150, 30);
	Password1->setMinimumSize(0, 0);
	Password1->setMaximumSize(32767, 32767);
	Password1->setFocusPolicy(QWidget::StrongFocus);
	Password1->setBackgroundMode(QWidget::PaletteBase);
#if QT_VERSION < 300
	Password1->setFontPropagation(QWidget::SameFont);
	Password1->setPalettePropagation(QWidget::SameFont);
	#endif
	Password1->setText( "" );
	Password1->setMaxLength( 12 );
	Password1->setFrame( QLineEdit::NoEcho );
	Password1->setFrame( TRUE );
	Password1->setAlignment( AlignLeft );
	Password2 = new QLineEdit(this, "LineEdit_2");
	Password2->setGeometry(130, 60, 150, 30);
	Password2->setMinimumSize(0, 0);
	Password2->setMaximumSize(32767, 32767);
	Password2->setFocusPolicy(QWidget::StrongFocus);
	Password2->setBackgroundMode(QWidget::PaletteBase);
#if QT_VERSION < 300
	Password2->setFontPropagation(QWidget::SameFont);
	Password2->setPalettePropagation(QWidget::SameFont);
	#endif
	Password2->setText( "" );
	Password2->setMaxLength( 12 );
	Password2->setFrame( QLineEdit::NoEcho );
	Password2->setFrame( TRUE );
	Password2->setAlignment( AlignLeft );
	OkButton = new QPushButton(this, "PushButton_1");
	OkButton->setGeometry(20, 110, 100, 30);
	OkButton->setMinimumSize(0, 0);
	OkButton->setMaximumSize(32767, 32767);
	OkButton->setFocusPolicy(QWidget::TabFocus);
	OkButton->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	OkButton->setFontPropagation(QWidget::SameFont);
	OkButton->setPalettePropagation(QWidget::SameFont);
	#endif
	OkButton->setText( tr( "Ok" ) );
	OkButton->setAutoRepeat( FALSE );
	OkButton->setAutoResize( FALSE );
	OkButton->setToggleButton( FALSE );
	OkButton->setDefault( TRUE );
	OkButton->setAutoDefault( TRUE );
	OkButton->setIsMenuButton( FALSE );
	connect(OkButton, SIGNAL(clicked()), SLOT(OkClicked()));
	QPushButton *qtarch_PushButton_2 = new QPushButton(this, "PushButton_2");
	qtarch_PushButton_2->setGeometry(210, 110, 100, 30);
	qtarch_PushButton_2->setMinimumSize(0, 0);
	qtarch_PushButton_2->setMaximumSize(32767, 32767);
	qtarch_PushButton_2->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_2->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_2->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_2->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_2->setText( tr( "Cancel" ) );
	qtarch_PushButton_2->setAutoRepeat( FALSE );
	qtarch_PushButton_2->setAutoResize( FALSE );
	qtarch_PushButton_2->setToggleButton( FALSE );
	qtarch_PushButton_2->setDefault( FALSE );
	qtarch_PushButton_2->setAutoDefault( FALSE );
	qtarch_PushButton_2->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_2, SIGNAL(clicked()), SLOT(reject()));
	resize(330,150);
	setMinimumSize(0, 0);
	setMaximumSize(32767, 32767);
}
NewPasswordData::~NewPasswordData()
{
}

