/**********************************************************************
--- Qt Architect generated file ---
File: ReportDirData.cpp
Last generated: Fri Feb 16 15:12:08 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#include <qt.h>
#include "ReportDirData.h"
ReportDirData::ReportDirData(QWidget *parent, const char *name)
: QDialog(parent, name, TRUE, 208)
{
	List = new QListBox(this, "ListBox_1");
	List->setGeometry(20, 30, 430, 330);
	List->setMinimumSize(0, 0);
	List->setMaximumSize(32767, 32767);
	List->setFocusPolicy(QWidget::TabFocus);
	List->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	List->setFontPropagation(QWidget::SameFont);
	List->setPalettePropagation(QWidget::SameFont);
	#endif
	List->setFrameStyle( 50 );
	List->setLineWidth( 2 );
	List->setMidLineWidth( 0 );
	List->QFrame::setMargin( 0 );
	List->setDragSelect( TRUE );
	List->setAutoScroll( TRUE );
	List->setScrollBar( TRUE );
	List->setAutoScrollBar( TRUE );
	List->setBottomScrollBar( TRUE );
	List->setAutoBottomScrollBar( TRUE );
	List->setSmoothScrolling( FALSE );
	List->setMultiSelection( FALSE );
	List->setAutoUpdate( TRUE );
	OkButton = new QPushButton(this, "PushButton_1");
	OkButton->setGeometry(20, 370, 100, 30);
	OkButton->setMinimumSize(0, 0);
	OkButton->setMaximumSize(32767, 32767);
	OkButton->setFocusPolicy(QWidget::TabFocus);
	OkButton->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	OkButton->setFontPropagation(QWidget::SameFont);
	OkButton->setPalettePropagation(QWidget::SameFont);
	#endif
	OkButton->setText( tr( "Ok" ) );
	OkButton->setAutoRepeat( FALSE );
	OkButton->setAutoResize( FALSE );
	OkButton->setToggleButton( FALSE );
	OkButton->setDefault( TRUE );
	OkButton->setAutoDefault( TRUE );
	OkButton->setIsMenuButton( FALSE );
	connect(OkButton, SIGNAL(clicked()), SLOT(accept()));
	QPushButton *qtarch_PushButton_2 = new QPushButton(this, "PushButton_2");
	qtarch_PushButton_2->setGeometry(350, 370, 100, 30);
	qtarch_PushButton_2->setMinimumSize(0, 0);
	qtarch_PushButton_2->setMaximumSize(32767, 32767);
	qtarch_PushButton_2->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_2->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_2->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_2->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_2->setText( tr( "Cancel" ) );
	qtarch_PushButton_2->setAutoRepeat( FALSE );
	qtarch_PushButton_2->setAutoResize( FALSE );
	qtarch_PushButton_2->setToggleButton( FALSE );
	qtarch_PushButton_2->setDefault( FALSE );
	qtarch_PushButton_2->setAutoDefault( FALSE );
	qtarch_PushButton_2->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_2, SIGNAL(clicked()), SLOT(reject()));
	resize(470,430);
	setMinimumSize(0, 0);
	setMaximumSize(32767, 32767);
}
ReportDirData::~ReportDirData()
{
}

