/**********************************************************************
--- Qt Architect generated file ---
File: ReportSelectData.h
Last generated: Fri Feb 16 15:37:31 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef ReportSelectData_included
#define ReportSelectData_included
#include <qt.h>
class ReportSelectData : public QDialog
{
	Q_OBJECT
	public:
	ReportSelectData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~ReportSelectData();
	QListBox *List;
	QPushButton *OkButton;
};
#endif // ReportSelectData_included

