/**********************************************************************
--- Qt Architect generated file ---
File: SelectPrinterDlgData.h
Last generated: Wed Feb 28 12:05:38 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef SelectPrinterDlgData_included
#define SelectPrinterDlgData_included
#include <qt.h>
class SelectPrinterDlgData : public QDialog
{
	Q_OBJECT
	public:
	SelectPrinterDlgData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~SelectPrinterDlgData();
	protected slots:
	virtual void OkClicked() =0;
	protected:
	QListBox *List;
};
#endif // SelectPrinterDlgData_included

