//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mod_RSsim.rc
//
#define IDS_PORTTOGGLE                  3
#define IDS_UPDATE_AVAILABLE            4
#define IDS_UPDATE_NO                   5
#define IDS_UPDATE_NOCHECK              6
#define IDM_ABOUTBOX                    0x0010
#define IDM_ALPHA_60                    0x0020
#define IDB_ALPHABLEND                  0x0020
#define IDM_ALPHA                       0x0030
#define IDM_ALPHA_70                    0x0040
#define IDM_ONTOP                       0x0050
#define IDM_TOGGLEPORT                  0x0060
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TI_SIM_DIALOG               102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_TITLE                       104
#define IDS_ALPHA_60                    105
#define IDS_ALPHA_70                    106
#define IDS_ALPHA                       107
#define IDS_SYNC_WRITTING               108
#define IDS_SYNC_READING                109
#define IDS_MNU_ONTOP                   110
#define CG_IDR_POPUP_APPMENU            111
#define IDM_SETTINGS                    0x0070
#define IDC_PORT                        121
#define IDC_BAUDRATE                    122
#define IDC_PARITY                      123
#define IDC_STOP_BITS                   124
#define IDC_DATA_BITS                   125
#define IDC_RTS_COMBO                   126
#define IDM_EMULATE                     0x0080
#define IDR_MAINFRAME                   128
#define IDD_SERVERSETTINGS_232          129
#define IDR_MAINZETH                    129
#define IDD_EDITMEMCELL                 130
#define IDR_MAINZDF1                    131
#define IDD_ANIMATE                     132
#define IDR_MAINJOY                     133
#define IDC_MYHANDCURSOR                135
#define IDD_FAULTSDLG                   138
#define IDR_TOOLBAR1                    139
#define IDD_EASTEREGG                   141
#define IDD_ADVEMULATION                142
#define IDD_SERVERSETTINGS_ETH          144
#define IDM_CSVIMPORT                   0x0090
#define IDB_SPLASH                      146
#define IDD_TRAININGSIM                 147
#define IDR_HELPHTM                     149
#define IDR_HELPSHOT1                   150
#define IDR_HELPSHOT2                   151
#define IDR_HELPANIM                    152
#define IDR_HELPJUICE                   153
#define IDR_HELPPORTA                   154
#define IDB_DRAGSE                      154
#define IDD_JOYSCC_EMULATION            155
#define IDR_JOYSHOT                     156
#define IDR_ADVMBUS                     157
#define IDR_TOOLBARSHOT                 158
#define IDB_MULTISLAVEMODE              160
#define IDM_READONLY                    0x00A0
#define IDB_SINGLESLAVEMODE             161
#define IDD_CSV_IMPORTDLG               161
#define IDD_REGISTRATIONDLG             164
#define IDC_DATALIST                    1000
#define IDC_COMBOAREA                   1001
#define IDC_SETTINGS                    1002
#define IDC_SIMULATE                    1003
#define IDC_LOCALIP                     1003
#define IDC_REMOTEIP                    1004
#define IDC_LOCALPORT                   1005
#define IDC_RESPONSEDELAY               1006
#define IDC_SERVERSTATS                 1007
#define IDC_NUMSERVERS                  1007
#define IDC_VIEWHEX                     1008
#define IDC_LOCALID                     1008
#define IDC_VIEWDEC                     1009
#define IDC_LOCALPORT2                  1009
#define IDC_VALUE                       1010
#define IDC_LINGER                      1012
#define IDC_SERVERLINE                  1014
#define IDC_NOANIMATE                   1015
#define IDC_ANIMATEBYTES                1016
#define IDC_ANIMATEWORDS                1017
#define IDC_TRAINING                    1018
#define IDC_ZEROES                      1019
#define IDC_LOAD                        1020
#define IDC_SAVE                        1021
#define IDC_ACTIVESTATIONS              1022
#define IDC_MENU                        1022
#define IDC_STATION00                   1023
#define IDC_STATION01                   1024
#define IDC_STATION02                   1025
#define IDC_STATION03                   1026
#define IDC_STATION04                   1027
#define IDC_STATION05                   1028
#define IDC_STATION06                   1029
#define IDC_STATION07                   1030
#define IDC_STATION08                   1031
#define IDC_STATION09                   1032
#define IDC_STATION10                   1033
#define IDC_STATION11                   1034
#define IDC_STATION12                   1035
#define IDC_STATION13                   1036
#define IDC_STATION14                   1037
#define IDC_STATION15                   1038
#define IDC_STATION16                   1039
#define IDC_STATION17                   1040
#define IDC_STATION18                   1041
#define IDC_STATION19                   1042
#define IDC_STATION20                   1043
#define IDC_STATION21                   1044
#define IDC_ANIMATION_ON                1045
#define IDC_STATION22                   1045
#define IDC_STATION23                   1046
#define IDC_HTML_UPDATERATE             1046
#define IDC_STATION24                   1047
#define IDC_STATION25                   1048
#define IDC_STATION26                   1049
#define IDC_STATION27                   1050
#define IDC_STATION28                   1051
#define IDC_STATION29                   1052
#define IDC_STATION30                   1053
#define IDC_STATION31                   1054
#define IDC_STATION32                   1055
#define IDC_STATION33                   1056
#define IDC_STATION34                   1057
#define IDC_STATION35                   1058
#define IDC_STATION36                   1059
#define IDC_STATION37                   1060
#define IDC_STATION38                   1061
#define IDC_STATION39                   1062
#define IDC_STATION40                   1063
#define IDC_STATION41                   1064
#define IDC_STATION42                   1065
#define IDC_STATION43                   1066
#define IDC_STATION44                   1067
#define IDC_STATION45                   1068
#define IDC_STATION46                   1069
#define IDC_STATION47                   1070
#define IDC_STATION48                   1071
#define IDC_STATION49                   1072
#define IDC_STATION50                   1073
#define IDC_STATION51                   1074
#define IDC_STATION52                   1075
#define IDC_STATION53                   1076
#define IDC_STATION54                   1077
#define IDC_STATION55                   1078
#define IDC_STATION56                   1079
#define IDC_STATION57                   1080
#define IDC_STATION58                   1081
#define IDC_STATION59                   1082
#define IDC_STATION60                   1083
#define IDC_STATION61                   1084
#define IDC_STATION62                   1085
#define IDC_STATION63                   1086
#define IDC_STATION64                   1087
#define IDC_STATION65                   1088
#define IDC_STATION66                   1089
#define IDC_STATION67                   1090
#define IDC_STATION68                   1091
#define IDC_STATION69                   1092
#define IDC_STATION70                   1093
#define IDC_STATION71                   1094
#define IDC_STATION72                   1095
#define IDC_STATION73                   1096
#define IDC_STATION74                   1097
#define IDC_STATION75                   1098
#define IDC_STATION77                   1100
#define IDC_STATION78                   1101
#define IDC_STATION79                   1102
#define IDC_STATION80                   1103
#define IDC_STATION81                   1104
#define IDC_STATION82                   1105
#define IDC_STATION83                   1106
#define IDC_STATION84                   1107
#define IDC_STATION85                   1108
#define IDC_STATION76                   1109
#define IDC_STATION87                   1110
#define IDC_STATION88                   1111
#define IDC_STATION89                   1112
#define IDC_STATION90                   1113
#define IDC_STATION91                   1114
#define IDC_STATION92                   1115
#define IDC_WWWLINK                     1115
#define IDC_STATICICN                   1116
#define IDB_TOOLBARID                   1116
#define IDC_EMAILLINK                   1117
#define IDC_ABOUTHEADDING               1118
#define IDC_STATION86                   1119
#define IDC_MODICONLINK                 1119
#define IDC_STATICICN2                  1120
#define IDC_STATICICN3                  1121
#define IDC_STN_ENABLED                 1125
#define IDC_STN_DISABLED                1126
#define IDC_STN_ACTIVE                  1127
#define IDC_STN_INACTIVE                1128
#define IDC_STN_TEXT                    1129
#define IDC_DEMOCHECK                   1130
#define IDC_CLONE                       1131
#define IDC_DATAFORMAT                  1132
#define IDC_PROTOCOL                    1133
#define IDC_ENABLE                      1134
#define IDC_INSERTS                     1135
#define IDC_DELETES                     1136
#define IDC_CORRUPTS                    1137
#define IDC_MISFRAMES                   1138
#define IDC_IGNORES                     1139
#define IDC_DELAYS                      1140
#define IDC_DELAYPERIOD                 1141
#define IDC_FREQ                        1142
#define IDC_BEEP                        1143
#define IDC_REFRESHES                   1144
#define IDC_STN_DISTEXT                 1146
#define IDC_MOSCAD                      1147
#define IDC_AUTOLOAD                    1148
#define IDC_MODIFY_FIRST                1148
#define IDC_SINKSTAT2                   1149
#define IDC_STARTOFF                    1149
#define IDC_STARTSCTRL                  1149
#define IDC_DISABLEWRITES               1149
#define IDC_LAMPRX                      1150
#define IDC_ABMASTER                    1150
#define IDC_LAMPTX                      1151
#define IDC_OUTPUTS                     1151
#define IDC_INPUTS                      1152
#define IDC_PLANTSIM                    1152
#define IDC_ANALOGS                     1153
#define IDC_LAMPCTS                     1153
#define IDC_HOLDING                     1154
#define IDC_LAMPDSR                     1154
#define IDC_EXTENDED                    1155
#define IDC_LAMPRING                    1155
#define IDC_DEFAULTS                    1156
#define IDC_MAXIMUM                     1157
#define IDC_PDUSIZE                     1159
#define IDC_COMMSLIST                   1160
#define IDB_TOGGLEDISP                  1162
#define IDC_STATIC_1                    1163
#define IDC_STATIC_2                    1164
#define IDC_STATIC_3                    1165
#define IDC_PAUSECOMMS                  1166
#define IDC_TRACKCOMMS                  1167
#define IDC_VSCROLLSTATIONS             1168
#define IDC_STATIC_4                    1169
#define IDC_STATIC1                     1169
#define IDC_STATIC2                     1170
#define IDC_CLEARCOMMS                  1170
#define IDC_STATIC3                     1171
#define IDC_RULER                       1172
#define IDC_REGISTERNAME                1174
#define IDC_SPLASH                      1177
#define IDC_CHECK1                      1178
#define IDC_CHECK2                      1179
#define IDC_CHECK3                      1180
#define IDC_CHECK4                      1181
#define IDC_CHECK5                      1182
#define IDC_CHECK6                      1183
#define IDC_CHECK7                      1184
#define IDC_CHECK8                      1185
#define IDC_CHECK9                      1186
#define IDC_CHECK10                     1187
#define IDC_CHECK11                     1188
#define IDC_CHECK12                     1189
#define IDC_CHECK13                     1190
#define IDC_CHECK14                     1191
#define IDC_CHECK15                     1192
#define IDC_CHECK16                     1193
#define IDC_CBREGISTERNAMES             1194
#define IDC_REGVALUE                    1195
#define IDC_SET                         1196
#define IDC_REGVALUESET                 1197
#define IDC_SCRIPTNAME                  1198
#define IDC_STATIC5                     1199
#define IDC_STATUSLINE                  1200
#define IDC_INPUT_HTMLNAME              1200
#define IDC_TRAININGSIM                 1201
#define IDC_STATIC4                     1202
#define IDC_OUTPUT_HTMLNAME             1202
#define IDC_CHECKTYPE                   1204
#define IDC_CREDITSTATIC                1205
#define IDC_DRAG                        1206
#define IDC_REGISTRATIONINFO            1207
#define IDC_EMU                         1208
#define IDC_SCC_DEST                    1209
#define IDC_SCC_SOURCE                  1210
#define IDC_NUMSHIELDS                  1211
#define IDC_RUN                         1212
#define IDC_READVARIABLES               1213
#define IDC_WRITEVARIABLES              1214
#define IDC_IDLE                        1215
#define IDC_TIMEOUT                     1216
#define IDC_NEEDSSTATION                1216
#define IDC_SEPERATED                   1217
#define IDC_NUMSEPERATE                 1218
#define IDC_BMPMODE                     1219
#define IDS_SEPERATED                   1220
#define IDC_ENABLEHTMLGUI               1220
#define IDC_IMPORTFOLDER                1221
#define IDC_IMPORTLOGNAME               1222
#define IDC_IMPORTENABLED               1223
#define IDC_QUICKIMPORT                 1224
#define IDB_CHECKUPDATES                1225
#define IDC_USERNAME                    1226
#define IDB_CHECKUPDATES2               1226
#define IDB_EDITREGISTRATION            1226
#define IDC_REGISTRATION_KEY            1227
#define IDC_SHOWCOMMSTIME               1300
#define IDB_ALPHABLEND60                32779
#define IDB_ALPHABLEND70                32780
#define IDC_NOISE                       32781
#define IDC_NOISY                       32782
#define IDS_ADROITWEBURL                32782
#define IDC_EMULATION                   32783
#define IDS_EMULATION                   32784
#define IDH_EMULATION                   32784
#define IDH_LOAD                        32785
#define IDS_NOTSUPPORTEDETH             32785
#define IDH_SAVE                        32786
#define IDS_ABDF1SETUPTITLE             32786
#define IDH_NOISE                       32787
#define IDS_JOYSETUPTITLE               32787
#define IDH_ERASE                       32788
#define IDH_ABOUT                       32789
#define IDH_HELPKEY                     32790
#define IDH_TRANSPARENCY                32791
#define IDH_TOGGLEDISP                  32792
#define IDH_INJECTERROR                 32793
#define IDC_CLOSE                       32794
#define IDS_CLOSE                       32795
#define IDC_OPEN                        32796
#define IDS_OPEN                        32797
#define IDC_CSVIMPORT                   32798
#define IDS_MSGCSVSTARTPROCESSING       32799
#define ID_BUTTONHELP                   32799
#define IDS_MSGCSVSTARTPROCESSING_MAN   32800
#define ID_COPYCLIP                     32800
#define IDH_COPYCLIP                    32800
#define IDS_MYBLOGURL                   32801
#define IDS_HOMEPAGEURL                 32802
#define IDH_SETTINGS                    57664

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32802
#define _APS_NEXT_CONTROL_VALUE         1227
#define _APS_NEXT_SYMED_VALUE           117
#endif
#endif
