/**********************************************************************
--- Qt Architect generated file ---
File: AlarmGroupCfgData.h
Last generated: Tue Sep 26 13:17:45 2000
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef AlarmGroupCfgData_included
#define AlarmGroupCfgData_included
#include <qt.h>

class AlarmGroupCfgData : public QDialog
{
	Q_OBJECT
	public:
	AlarmGroupCfgData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~AlarmGroupCfgData();
	protected slots:
	virtual void Help() =0;
	virtual void Delete() =0;
	virtual void SelChanged(int) =0;
	virtual void Remove() =0;
	virtual void Apply() =0;
	virtual void New() =0;
	virtual void Add() =0;
	protected:
	QComboBox *Name;
	QLineEdit *Comment;
	QPushButton *ApplyButton;
	QPushButton *NewButton;
	QPushButton *DeleteButton;
	QListBox *SamplePoints;
	QListBox *GroupList;
};
#endif // AlarmGroupCfgData_included

