/**********************************************************************
--- Qt Architect generated file ---
File: MQTT_clientInputData.h
Last generated: Thu Jan 4 16:14:13 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef MQTT_clientInputData_included
#define MQTT_clientInputData_included
#include <qt.h>
#include "valedit.h"
class MQTT_clientInputData : public QWidget
{
	Q_OBJECT
	public:
	MQTT_clientInputData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~MQTT_clientInputData();
	protected:
	//QLineEdit *Low;
	//QLineEdit *High;
	//TIMEEDIT *Interval;
	QLineEdit *ItemID;
	QLineEdit *OPCType;
	QCheckBox *IsWriteble;
};
#endif // MQTT_clientInputData_included

