/**********************************************************************
--- Qt Architect generated file ---
File: AlarmGroupCfgData.cpp
Last generated: Tue Sep 26 13:17:45 2000
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#include <qt.h>
#include <common.h>
#include "AlarmGroupCfgData.h"

AlarmGroupCfgData::AlarmGroupCfgData(QWidget *parent, const char *name)
: QDialog(parent, name, TRUE, 208)
{
	QFrame *qtarch_Frame_1 = new QFrame(this, "Frame_1");
	qtarch_Frame_1->setGeometry(20, 10, 710, 510);
	qtarch_Frame_1->setMinimumSize(0, 0);
	qtarch_Frame_1->setMaximumSize(32767, 32767);
	qtarch_Frame_1->setFocusPolicy(QWidget::NoFocus);
	qtarch_Frame_1->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Frame_1->setFontPropagation(QWidget::SameFont);
	qtarch_Frame_1->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_Frame_1->setFrameStyle( 51 );
	qtarch_Frame_1->setLineWidth( 2 );
	qtarch_Frame_1->setMidLineWidth( 0 );
	qtarch_Frame_1->QFrame::setMargin( 0 );
	QLabel *qtarch_Label_1 = new QLabel(this, "Label_1");
	qtarch_Label_1->setGeometry(40, 40, 40, 30);
	qtarch_Label_1->setMinimumSize(0, 0);
	qtarch_Label_1->setMaximumSize(32767, 32767);
	qtarch_Label_1->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_1->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_1->setFontPropagation(QWidget::SameFont);
	qtarch_Label_1->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_Label_1->setFrameStyle( 0 );
	qtarch_Label_1->setLineWidth( 1 );
	qtarch_Label_1->setMidLineWidth( 0 );
	qtarch_Label_1->QFrame::setMargin( 0 );
	qtarch_Label_1->setText( tr( "Name" ) );
	qtarch_Label_1->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_1->setMargin( 0 );
	QLabel *qtarch_Label_2 = new QLabel(this, "Label_2");
	qtarch_Label_2->setGeometry(40, 80, 60, 30);
	qtarch_Label_2->setMinimumSize(0, 0);
	qtarch_Label_2->setMaximumSize(32767, 32767);
	qtarch_Label_2->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_2->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_2->setFontPropagation(QWidget::SameFont);
	qtarch_Label_2->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_Label_2->setFrameStyle( 0 );
	qtarch_Label_2->setLineWidth( 1 );
	qtarch_Label_2->setMidLineWidth( 0 );
	qtarch_Label_2->QFrame::setMargin( 0 );
	qtarch_Label_2->setText( tr( "Comment" ) );
	qtarch_Label_2->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_2->setMargin( 0 );
	Name = new QComboBox(FALSE, this, "ComboBox_1");
	Name->setGeometry(120, 40, 590, 30);
	Name->setMinimumSize(0, 0);
	Name->setMaximumSize(32767, 32767);
	Name->setFocusPolicy(QWidget::StrongFocus);
	Name->setBackgroundMode(QWidget::NoBackground);
#if QT_VERSION < 300
	Name->setFontPropagation(QWidget::SameFont);
	Name->setPalettePropagation(QWidget::SameFont);
		#endif
	Name->setSizeLimit( 10 );
	Name->setAutoResize( FALSE );
	Name->setMaxCount( 2147483647 );
	Name->setAutoCompletion( FALSE );
	connect(Name, SIGNAL(activated(int)), SLOT(SelChanged(int)));
	connect(Name, SIGNAL(highlighted(int)), SLOT(SelChanged(int)));
	Comment = new QLineEdit(this, "LineEdit_1");
	Comment->setGeometry(120, 80, 590, 30);
	Comment->setMinimumSize(0, 0);
	Comment->setMaximumSize(32767, 32767);
	Comment->setFocusPolicy(QWidget::StrongFocus);
	Comment->setBackgroundMode(QWidget::PaletteBase);
#if QT_VERSION < 300
	Comment->setFontPropagation(QWidget::SameFont);
	Comment->setPalettePropagation(QWidget::SameFont);
		#endif
	Comment->setText( tr(NONE_STR) );
	Comment->setMaxLength( 128 );
	Comment->setFrame( QLineEdit::Normal );
	Comment->setFrame( TRUE );
	Comment->setAlignment( AlignLeft );
	ApplyButton = new QPushButton(this, "PushButton_1");
	ApplyButton->setGeometry(20, 530, 100, 30);
	ApplyButton->setMinimumSize(0, 0);
	ApplyButton->setMaximumSize(32767, 32767);
	ApplyButton->setFocusPolicy(QWidget::TabFocus);
	ApplyButton->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	ApplyButton->setFontPropagation(QWidget::SameFont);
	ApplyButton->setPalettePropagation(QWidget::SameFont);
		#endif
	ApplyButton->setText( tr( "Apply" ) );
	ApplyButton->setAutoRepeat( FALSE );
	ApplyButton->setAutoResize( FALSE );
	ApplyButton->setToggleButton( FALSE );
	ApplyButton->setDefault( FALSE );
	ApplyButton->setAutoDefault( FALSE );
	ApplyButton->setIsMenuButton( FALSE );
	connect(ApplyButton, SIGNAL(clicked()), SLOT(Apply()));
	NewButton = new QPushButton(this, "PushButton_2");
	NewButton->setGeometry(140, 530, 100, 30);
	NewButton->setMinimumSize(0, 0);
	NewButton->setMaximumSize(32767, 32767);
	NewButton->setFocusPolicy(QWidget::TabFocus);
	NewButton->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	NewButton->setFontPropagation(QWidget::SameFont);
	NewButton->setPalettePropagation(QWidget::SameFont);
		#endif
	NewButton->setText( tr( "New..." ) );
	NewButton->setAutoRepeat( FALSE );
	NewButton->setAutoResize( FALSE );
	NewButton->setToggleButton( FALSE );
	NewButton->setDefault( FALSE );
	NewButton->setAutoDefault( FALSE );
	NewButton->setIsMenuButton( FALSE );
	connect(NewButton, SIGNAL(clicked()), SLOT(New()));
	DeleteButton = new QPushButton(this, "PushButton_3");
	DeleteButton->setGeometry(260, 530, 100, 30);
	DeleteButton->setMinimumSize(0, 0);
	DeleteButton->setMaximumSize(32767, 32767);
	DeleteButton->setFocusPolicy(QWidget::TabFocus);
	DeleteButton->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	DeleteButton->setFontPropagation(QWidget::SameFont);
	DeleteButton->setPalettePropagation(QWidget::SameFont);
		#endif
	DeleteButton->setText( tr( "Delete" ) );
	DeleteButton->setAutoRepeat( FALSE );
	DeleteButton->setAutoResize( FALSE );
	DeleteButton->setToggleButton( FALSE );
	DeleteButton->setDefault( FALSE );
	DeleteButton->setAutoDefault( FALSE );
	DeleteButton->setIsMenuButton( FALSE );
	connect(DeleteButton, SIGNAL(clicked()), SLOT(Delete()));
	QPushButton *qtarch_PushButton_4 = new QPushButton(this, "PushButton_4");
	qtarch_PushButton_4->setGeometry(380, 530, 100, 30);
	qtarch_PushButton_4->setMinimumSize(0, 0);
	qtarch_PushButton_4->setMaximumSize(32767, 32767);
	qtarch_PushButton_4->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_4->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_4->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_4->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_PushButton_4->setText( tr( "Help" ) );
	qtarch_PushButton_4->setAutoRepeat( FALSE );
	qtarch_PushButton_4->setAutoResize( FALSE );
	qtarch_PushButton_4->setToggleButton( FALSE );
	qtarch_PushButton_4->setDefault( FALSE );
	qtarch_PushButton_4->setAutoDefault( FALSE );
	qtarch_PushButton_4->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_4, SIGNAL(clicked()), SLOT(Help()));
	QPushButton *qtarch_PushButton_5 = new QPushButton(this, "PushButton_5");
	qtarch_PushButton_5->setGeometry(630, 530, 100, 30);
	qtarch_PushButton_5->setMinimumSize(0, 0);
	qtarch_PushButton_5->setMaximumSize(32767, 32767);
	qtarch_PushButton_5->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_5->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_5->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_5->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_PushButton_5->setText( tr( "Exit" ) );
	qtarch_PushButton_5->setAutoRepeat( FALSE );
	qtarch_PushButton_5->setAutoResize( FALSE );
	qtarch_PushButton_5->setToggleButton( FALSE );
	qtarch_PushButton_5->setDefault( FALSE );
	qtarch_PushButton_5->setAutoDefault( FALSE );
	qtarch_PushButton_5->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_5, SIGNAL(clicked()), SLOT(reject()));
	SamplePoints = new QListBox(this, "ListBox_1");
	SamplePoints->setGeometry(40, 160, 230, 340);
	SamplePoints->setMinimumSize(0, 0);
	SamplePoints->setMaximumSize(32767, 32767);
	SamplePoints->setFocusPolicy(QWidget::StrongFocus );
	SamplePoints->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	SamplePoints->setFontPropagation(QWidget::SameFont);
	SamplePoints->setPalettePropagation(QWidget::SameFont);
		#endif
	SamplePoints->setFrameStyle( 49 );
	SamplePoints->setLineWidth( 2 );
	SamplePoints->setMidLineWidth( 0 );
	SamplePoints->QFrame::setMargin( 0 );
	SamplePoints->setDragSelect( TRUE );
	SamplePoints->setAutoScroll( TRUE );
	SamplePoints->setScrollBar( TRUE );
	SamplePoints->setAutoScrollBar( TRUE );
	SamplePoints->setBottomScrollBar( TRUE );
	SamplePoints->setAutoBottomScrollBar( TRUE );
	SamplePoints->setSmoothScrolling( FALSE );
	SamplePoints->setMultiSelection( TRUE );
	SamplePoints->setAutoUpdate( TRUE );
	GroupList = new QListBox(this, "ListBox_2");
	GroupList->setGeometry(450, 160, 260, 340);
	GroupList->setMinimumSize(0, 0);
	GroupList->setMaximumSize(32767, 32767);
	GroupList->setFocusPolicy(QWidget::StrongFocus );
	GroupList->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	GroupList->setFontPropagation(QWidget::SameFont);
	GroupList->setPalettePropagation(QWidget::SameFont);
		#endif
	GroupList->setFrameStyle( 50 );
	GroupList->setLineWidth( 2 );
	GroupList->setMidLineWidth( 0 );
	GroupList->QFrame::setMargin( 0 );
	GroupList->setDragSelect( TRUE );
	GroupList->setAutoScroll( TRUE );
	GroupList->setScrollBar( TRUE );
	GroupList->setAutoScrollBar( TRUE );
	GroupList->setBottomScrollBar( TRUE );
	GroupList->setAutoBottomScrollBar( TRUE );
	GroupList->setSmoothScrolling( FALSE );
	GroupList->setMultiSelection( TRUE );
	GroupList->setAutoUpdate( TRUE );
	QPushButton *qtarch_PushButton_6 = new QPushButton(this, "PushButton_6");
	qtarch_PushButton_6->setGeometry(310, 180, 100, 30);
	qtarch_PushButton_6->setMinimumSize(0, 0);
	qtarch_PushButton_6->setMaximumSize(32767, 32767);
	qtarch_PushButton_6->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_6->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_6->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_6->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_PushButton_6->setText( tr( "Add >>" ) );
	qtarch_PushButton_6->setAutoRepeat( FALSE );
	qtarch_PushButton_6->setAutoResize( FALSE );
	qtarch_PushButton_6->setToggleButton( FALSE );
	qtarch_PushButton_6->setDefault( FALSE );
	qtarch_PushButton_6->setAutoDefault( FALSE );
	qtarch_PushButton_6->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_6, SIGNAL(clicked()), SLOT(Add()));
	QPushButton *qtarch_PushButton_7 = new QPushButton(this, "PushButton_7");
	qtarch_PushButton_7->setGeometry(310, 240, 100, 30);
	qtarch_PushButton_7->setMinimumSize(0, 0);
	qtarch_PushButton_7->setMaximumSize(32767, 32767);
	qtarch_PushButton_7->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_7->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_7->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_7->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_PushButton_7->setText( tr( "<< Remove" ) );
	qtarch_PushButton_7->setAutoRepeat( FALSE );
	qtarch_PushButton_7->setAutoResize( FALSE );
	qtarch_PushButton_7->setToggleButton( FALSE );
	qtarch_PushButton_7->setDefault( FALSE );
	qtarch_PushButton_7->setAutoDefault( FALSE );
	qtarch_PushButton_7->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_7, SIGNAL(clicked()), SLOT(Remove()));
	QLabel *qtarch_Label_4 = new QLabel(this, "Label_4");
	qtarch_Label_4->setGeometry(50, 120, 100, 30);
	qtarch_Label_4->setMinimumSize(0, 0);
	qtarch_Label_4->setMaximumSize(32767, 32767);
	qtarch_Label_4->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_4->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_4->setFontPropagation(QWidget::SameFont);
	qtarch_Label_4->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_Label_4->setFrameStyle( 0 );
	qtarch_Label_4->setLineWidth( 1 );
	qtarch_Label_4->setMidLineWidth( 0 );
	qtarch_Label_4->QFrame::setMargin( 0 );
	qtarch_Label_4->setText( tr( "Sample Points" ) );
	qtarch_Label_4->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_4->setMargin( 0 );
	QLabel *qtarch_Label_5 = new QLabel(this, "Label_5");
	qtarch_Label_5->setGeometry(460, 120, 100, 30);
	qtarch_Label_5->setMinimumSize(0, 0);
	qtarch_Label_5->setMaximumSize(32767, 32767);
	qtarch_Label_5->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_5->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	qtarch_Label_5->setFontPropagation(QWidget::SameFont);
	qtarch_Label_5->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_Label_5->setFrameStyle( 0 );
	qtarch_Label_5->setLineWidth( 1 );
	qtarch_Label_5->setMidLineWidth( 0 );
	qtarch_Label_5->QFrame::setMargin( 0 );
	qtarch_Label_5->setText( tr( "Points In Group" ) );
	qtarch_Label_5->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_5->setMargin( 0 );
	resize(750,580);
	setMinimumSize(0, 0);
	setMaximumSize(32767, 32767);
}
AlarmGroupCfgData::~AlarmGroupCfgData()
{
}

