/**********************************************************************
--- Qt Architect generated file ---
File: NewDlgData.cpp
Last generated: Fri Feb 16 15:16:37 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#include <qt.h>
#include "NewDlgData.h"

NewDlgData::NewDlgData(QWidget *parent, const char *name)
: QDialog(parent, name, TRUE, 464)
{
	QFrame *qtarch_Frame_1 = new QFrame(this, "Frame_1");
	qtarch_Frame_1->setGeometry(10, 10, 340, 260);
	qtarch_Frame_1->setMinimumSize(0, 0);
	qtarch_Frame_1->setMaximumSize(32767, 32767);
	qtarch_Frame_1->setFocusPolicy(QWidget::NoFocus);
	qtarch_Frame_1->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Frame_1->setFontPropagation(QWidget::SameFont);
	qtarch_Frame_1->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_Frame_1->setFrameStyle( 50 );
	qtarch_Frame_1->setLineWidth( 1 );
	qtarch_Frame_1->setMidLineWidth( 0 );
	qtarch_Frame_1->QFrame::setMargin( 0 );
	OkButton = new QPushButton(this, "PushButton_1");
	OkButton->setGeometry(10, 280, 100, 30);
	OkButton->setMinimumSize(0, 0);
	OkButton->setMaximumSize(32767, 32767);
	OkButton->setFocusPolicy(QWidget::TabFocus);
	OkButton->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	OkButton->setFontPropagation(QWidget::SameFont);
	OkButton->setPalettePropagation(QWidget::SameFont);
		#endif
	OkButton->setText( tr( "Ok" ) );
	OkButton->setAutoRepeat( FALSE );
	OkButton->setAutoResize( FALSE );
	OkButton->setToggleButton( FALSE );
	OkButton->setDefault( TRUE );
	OkButton->setAutoDefault( TRUE );
	OkButton->setIsMenuButton( FALSE );
	connect(OkButton, SIGNAL(clicked()), SLOT(accept()));
	QPushButton *qtarch_PushButton_2 = new QPushButton(this, "PushButton_2");
	qtarch_PushButton_2->setGeometry(250, 280, 100, 30);
	qtarch_PushButton_2->setMinimumSize(0, 0);
	qtarch_PushButton_2->setMaximumSize(32767, 32767);
	qtarch_PushButton_2->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_2->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_2->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_2->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_PushButton_2->setText( tr( "Cancel" ) );
	qtarch_PushButton_2->setAutoRepeat( FALSE );
	qtarch_PushButton_2->setAutoResize( FALSE );
	qtarch_PushButton_2->setToggleButton( FALSE );
	qtarch_PushButton_2->setDefault( FALSE );
	qtarch_PushButton_2->setAutoDefault( TRUE );
	qtarch_PushButton_2->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_2, SIGNAL(clicked()), SLOT(reject()));
	List = new QListBox(this, "ListBox_1");
	List->setGeometry(90, 80, 230, 170);
	List->setMinimumSize(0, 0);
	List->setMaximumSize(32767, 32767);
	List->setFocusPolicy(QWidget::TabFocus);
	List->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	List->setFontPropagation(QWidget::SameFont);
	List->setPalettePropagation(QWidget::SameFont);
		#endif
	List->setFrameStyle( 50 );
	List->setLineWidth( 2 );
	List->setMidLineWidth( 0 );
	List->QFrame::setMargin( 0 );
	List->setDragSelect( TRUE );
	List->setAutoScroll( TRUE );
	List->setScrollBar( TRUE );
	List->setAutoScrollBar( TRUE );
	List->setBottomScrollBar( TRUE );
	List->setAutoBottomScrollBar( TRUE );
	List->setSmoothScrolling( FALSE );
	List->setMultiSelection( FALSE );
	List->setAutoUpdate( TRUE );
	QLabel *qtarch_Label_1 = new QLabel(this, "Label_1");
	qtarch_Label_1->setGeometry(30, 30, 50, 30);
	qtarch_Label_1->setMinimumSize(0, 0);
	qtarch_Label_1->setMaximumSize(32767, 32767);
	qtarch_Label_1->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_1->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_1->setFontPropagation(QWidget::SameFont);
	qtarch_Label_1->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_Label_1->setFrameStyle( 0 );
	qtarch_Label_1->setLineWidth( 1 );
	qtarch_Label_1->setMidLineWidth( 0 );
	qtarch_Label_1->QFrame::setMargin( 0 );
	qtarch_Label_1->setText( tr( "Name" ) );
	qtarch_Label_1->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_1->setMargin( 0 );
	Name = new NAMEEDIT(this, "User_1");
	Name->setGeometry(90, 30, 230, 30);
	Name->setMinimumSize(0, 0);
	Name->setMaximumSize(32767, 32767);
	Name->setFocusPolicy(QWidget::StrongFocus);
	Name->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	Name->setFontPropagation(QWidget::SameFont);
	Name->setPalettePropagation(QWidget::SameFont);
		#endif
	QPushButton *qtarch_PushButton_3 = new QPushButton(this, "PushButton_3");
	qtarch_PushButton_3->setGeometry(130, 280, 100, 30);
	qtarch_PushButton_3->setMinimumSize(0, 0);
	qtarch_PushButton_3->setMaximumSize(32767, 32767);
	qtarch_PushButton_3->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_3->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_3->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_3->setPalettePropagation(QWidget::SameFont);
		#endif
	qtarch_PushButton_3->setText( tr( "Help" ) );
	qtarch_PushButton_3->setAutoRepeat( FALSE );
	qtarch_PushButton_3->setAutoResize( FALSE );
	qtarch_PushButton_3->setToggleButton( FALSE );
	qtarch_PushButton_3->setDefault( FALSE );
	qtarch_PushButton_3->setAutoDefault( TRUE );
	qtarch_PushButton_3->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_3, SIGNAL(clicked()), SLOT(Help()));
	resize(360,320);
	setMinimumSize(0, 0);
	setMaximumSize(32767, 32767);
}
NewDlgData::~NewDlgData()
{
}

