/**********************************************************************
--- Qt Architect generated file ---
File: TagCfgData.h
Last generated: Thu Jan 4 16:04:27 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef TagCfgData_included
#define TagCfgData_included
#include <qt.h>

class TagCfgData : public QDialog
{
	Q_OBJECT
	public:
	TagCfgData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~TagCfgData();
	protected slots:
	virtual void Help() =0;
	virtual void SelChanged(int) =0;
	virtual void Apply() =0;
	protected:
	QComboBox *Name;
	QCheckBox *UAEnabled;
	QLineEdit *UpperAlarm;
	QLineEdit *UpperWarning;
	QCheckBox *UWEnabled;
	QLineEdit *LowerWarning;
	QCheckBox *LWEnabled;
	QLineEdit *LowerAlarm;
	QCheckBox *LAEnabled;
	QPushButton *ApplyButton;
};
#endif // TagCfgData_included

