/**********************************************************************
--- Qt Architect generated file ---
File: MQTT_clientCommandData.h
Last generated: Thu Jan 4 16:13:32 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef MQTT_clientCommandData_included
#define MQTT_clientCommandData_included

#include <qt.h>
#include "valedit.h"

class MQTT_clientCommandData : public QDialog
{
	Q_OBJECT
	public:
	MQTT_clientCommandData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~MQTT_clientCommandData();
	protected slots:
	virtual void Help() =0;
	virtual void OkClicked() =0;
	protected:
	QLabel *Name;
	QLineEdit *Value;
};
#endif // MQTT_clientCommandData_included

