GCC=i686-pc-mingw32-g++

CCOMPILER=$(GCC) -Wall -pedantic -fPIC -Wno-unused -g0 -O2 -D_REENTRANT -DENV_WINDOWS -DEXCLUDE_WX -I .  -I../liboapc/ -I../plugins/ -I..

LIBS = -lws2_32 -L../ -loapc

EXECUTABLE=OpenIServer.exe

LINK=$(GCC)

OBJECTS = OpenIServerInc.o

default: $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(LINK) $(SYSLDFLAGS) $(LDFLAGS) -o $(EXECUTABLE) $(OBJECTS) $(LIBS) 

%.o: %.cpp
	$(CCOMPILER) -c $< -o $@

clean:
	rm -f $(OBJECTS) $(EXECUTABLE)

