/**********************************************************************
--- Qt Architect generated file ---
File: MQTT_clientConfigurationData.cpp
Last generated: Thu Jan 4 16:13:32 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#include <qt.h>
#include "MQTT_clientConfigurationData.h"
MQTT_clientConfigurationData::MQTT_clientConfigurationData(QWidget *parent, const char *name)
: QDialog(parent, name, TRUE, 208)
{
	QLabel *qtarch_Label_7 = new QLabel(this, "Label_7");
	qtarch_Label_7->setGeometry(10, 0, 90, 30);
	qtarch_Label_7->setMinimumSize(0, 0);
	qtarch_Label_7->setMaximumSize(32767, 32767);
	qtarch_Label_7->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_7->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	qtarch_Label_7->setFontPropagation(QWidget::SameFont);
	qtarch_Label_7->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_7->setFrameStyle( 0 );
	qtarch_Label_7->setLineWidth( 1 );
	qtarch_Label_7->setMidLineWidth( 0 );
	qtarch_Label_7->QFrame::setMargin( 0 );
	qtarch_Label_7->setText( tr( "Name" ) );
	qtarch_Label_7->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_7->setMargin( 0 );
	Name = new QLabel(this, "Label_8");
	Name->setGeometry(200, 0, 250, 30);
	Name->setMinimumSize(0, 0);
	Name->setMaximumSize(32767, 32767);
	Name->setFocusPolicy(QWidget::NoFocus);
	Name->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	Name->setFontPropagation(QWidget::SameFont);
	Name->setPalettePropagation(QWidget::SameFont);
	#endif
	Name->setFrameStyle( 50 );
	Name->setLineWidth( 1 );
	Name->setMidLineWidth( 0 );
	Name->QFrame::setMargin( 0 );
	Name->setText( "" );
	Name->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	Name->setMargin( 0 );
	/////////////////////////////////////////////////////////////////////////
	MqttBrokerHostNameText = new QLineEdit(this, "LineEdit_7");
	MqttBrokerHostNameText->setGeometry(200, 40, 250, 30);
	MqttBrokerHostNameText->setMinimumSize(0, 0);
	MqttBrokerHostNameText->setMaximumSize(32767, 32767);
	MqttBrokerHostNameText->setFocusPolicy(QWidget::StrongFocus);
	MqttBrokerHostNameText->setBackgroundMode(QWidget::PaletteBase);
#if QT_VERSION < 300
	MqttBrokerHostNameText->setFontPropagation(QWidget::SameFont);
	MqttBrokerHostNameText->setPalettePropagation(QWidget::SameFont);
	#endif
	MqttBrokerHostNameText->setText( tr( "" ) );
	MqttBrokerHostNameText->setMaxLength( 100 );
	MqttBrokerHostNameText->setFrame( QLineEdit::Normal );
	MqttBrokerHostNameText->setFrame( TRUE );
	MqttBrokerHostNameText->setAlignment( AlignLeft );
	QLabel *qtarch_Label_21 = new QLabel(this, "Label_21");
	qtarch_Label_21->setGeometry(10, 40, 150, 30);
	qtarch_Label_21->setMinimumSize(0, 0);
	qtarch_Label_21->setMaximumSize(32767, 32767);
	qtarch_Label_21->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_21->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	qtarch_Label_21->setFontPropagation(QWidget::SameFont);
	qtarch_Label_21->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_21->setFrameStyle( 0 );
	qtarch_Label_21->setLineWidth( 1 );
	qtarch_Label_21->setMidLineWidth( 0 );
	qtarch_Label_21->QFrame::setMargin( 0 );
	qtarch_Label_21->setText( tr( "MQTT broker name" ) );
	qtarch_Label_21->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_21->setMargin( 0 );

	SubscribeTopicNameText = new QLineEdit(this, "LineEdit_8");
	SubscribeTopicNameText->setGeometry(200, 80, 250, 30);
	SubscribeTopicNameText->setMinimumSize(0, 0);
	SubscribeTopicNameText->setMaximumSize(32767, 32767);
	SubscribeTopicNameText->setFocusPolicy(QWidget::StrongFocus);
	SubscribeTopicNameText->setBackgroundMode(QWidget::PaletteBase);
#if QT_VERSION < 300
	SubscribeTopicNameText->setFontPropagation(QWidget::SameFont);
	SubscribeTopicNameText->setPalettePropagation(QWidget::SameFont);
	#endif
	SubscribeTopicNameText->setText( tr( "" ) );
	SubscribeTopicNameText->setMaxLength( 100 );
	SubscribeTopicNameText->setFrame( QLineEdit::Normal );
	SubscribeTopicNameText->setFrame( TRUE );
	SubscribeTopicNameText->setAlignment( AlignLeft );
	QLabel *qtarch_Label_22 = new QLabel(this, "Label_22");
	qtarch_Label_22->setGeometry(10, 80, 150, 30);
	qtarch_Label_22->setMinimumSize(0, 0);
	qtarch_Label_22->setMaximumSize(32767, 32767);
	qtarch_Label_22->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_22->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	qtarch_Label_22->setFontPropagation(QWidget::SameFont);
	qtarch_Label_22->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_22->setFrameStyle( 0 );
	qtarch_Label_22->setLineWidth( 1 );
	qtarch_Label_22->setMidLineWidth( 0 );
	qtarch_Label_22->QFrame::setMargin( 0 );
	qtarch_Label_22->setText( tr( "Subscribe topic name" ) );
	qtarch_Label_22->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_22->setMargin( 0 );

	UserNameText = new QLineEdit(this, "LineEdit_9");
	UserNameText->setGeometry(200, 120, 250, 30);
	UserNameText->setMinimumSize(0, 0);
	UserNameText->setMaximumSize(32767, 32767);
	UserNameText->setFocusPolicy(QWidget::StrongFocus);
	UserNameText->setBackgroundMode(QWidget::PaletteBase);
#if QT_VERSION < 300
	UserNameText->setFontPropagation(QWidget::SameFont);
	UserNameText->setPalettePropagation(QWidget::SameFont);
	#endif
	UserNameText->setText( tr( "" ) );
	UserNameText->setMaxLength( 100 );
	UserNameText->setFrame( QLineEdit::Normal );
	UserNameText->setFrame( TRUE );
	UserNameText->setAlignment( AlignLeft );
	QLabel *qtarch_Label_23 = new QLabel(this, "Label_23");
	qtarch_Label_23->setGeometry(10, 120, 150, 30);
	qtarch_Label_23->setMinimumSize(0, 0);
	qtarch_Label_23->setMaximumSize(32767, 32767);
	qtarch_Label_23->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_23->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	qtarch_Label_23->setFontPropagation(QWidget::SameFont);
	qtarch_Label_23->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_23->setFrameStyle( 0 );
	qtarch_Label_23->setLineWidth( 1 );
	qtarch_Label_23->setMidLineWidth( 0 );
	qtarch_Label_23->QFrame::setMargin( 0 );
	qtarch_Label_23->setText( tr( "User name" ) );
	qtarch_Label_23->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_23->setMargin( 0 );

	PasswordText = new QLineEdit(this, "LineEdit_10");
	PasswordText->setGeometry(200, 160, 250, 30);
	PasswordText->setMinimumSize(0, 0);
	PasswordText->setMaximumSize(32767, 32767);
	PasswordText->setFocusPolicy(QWidget::StrongFocus);
	PasswordText->setBackgroundMode(QWidget::PaletteBase);
#if QT_VERSION < 300
	PasswordText->setFontPropagation(QWidget::SameFont);
	PasswordText->setPalettePropagation(QWidget::SameFont);
	#endif
	PasswordText->setText( tr( "" ) );
	PasswordText->setMaxLength( 100 );
	PasswordText->setFrame( QLineEdit::Normal );
	PasswordText->setFrame( TRUE );
	PasswordText->setAlignment( AlignLeft );
	QLabel *qtarch_Label_24 = new QLabel(this, "Label_24");
	qtarch_Label_24->setGeometry(10, 160, 150, 30);
	qtarch_Label_24->setMinimumSize(0, 0);
	qtarch_Label_24->setMaximumSize(32767, 32767);
	qtarch_Label_24->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_24->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	qtarch_Label_24->setFontPropagation(QWidget::SameFont);
	qtarch_Label_24->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_24->setFrameStyle( 0 );
	qtarch_Label_24->setLineWidth( 1 );
	qtarch_Label_24->setMidLineWidth( 0 );
	qtarch_Label_24->QFrame::setMargin( 0 );
	qtarch_Label_24->setText( tr( "Password" ) );
	qtarch_Label_24->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_24->setMargin( 0 );

	PortText = new QLineEdit(this, "LineEdit_11");
	PortText->setGeometry(200, 200, 250, 30);
	PortText->setMinimumSize(0, 0);
	PortText->setMaximumSize(32767, 32767);
	PortText->setFocusPolicy(QWidget::StrongFocus);
	PortText->setBackgroundMode(QWidget::PaletteBase);
#if QT_VERSION < 300
	PortText->setFontPropagation(QWidget::SameFont);
	PortText->setPalettePropagation(QWidget::SameFont);
	#endif
	PortText->setText( tr( "" ) );
	PortText->setMaxLength( 100 );
	PortText->setFrame( QLineEdit::Normal );
	PortText->setFrame( TRUE );
	PortText->setAlignment( AlignLeft );
	QLabel *qtarch_Label_25 = new QLabel(this, "Label_25");
	qtarch_Label_25->setGeometry(10, 200, 150, 30);
	qtarch_Label_25->setMinimumSize(0, 0);
	qtarch_Label_25->setMaximumSize(32767, 32767);
	qtarch_Label_25->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_25->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	qtarch_Label_25->setFontPropagation(QWidget::SameFont);
	qtarch_Label_25->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_25->setFrameStyle( 0 );
	qtarch_Label_25->setLineWidth( 1 );
	qtarch_Label_25->setMidLineWidth( 0 );
	qtarch_Label_25->QFrame::setMargin( 0 );
	qtarch_Label_25->setText( tr( "Port" ) );
	qtarch_Label_25->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_25->setMargin( 0 );
/////////////////////////////////////////////////////////////////////////
	
/////////////////////////////////////////////////////////////////////////
	QLabel *qtarch_Label_10 = new QLabel(this, "Label_10");
	qtarch_Label_10->setGeometry(10, 240, 100, 30);
	qtarch_Label_10->setMinimumSize(0, 0);
	qtarch_Label_10->setMaximumSize(32767, 32767);
	qtarch_Label_10->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_10->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	qtarch_Label_10->setFontPropagation(QWidget::SameFont);
	qtarch_Label_10->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_10->setFrameStyle( 0 );
	qtarch_Label_10->setLineWidth( 1 );
	qtarch_Label_10->setMidLineWidth( 0 );
	qtarch_Label_10->QFrame::setMargin( 0 );
	qtarch_Label_10->setText( tr( "N Items" ) );
	qtarch_Label_10->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_10->setMargin( 0 );

	NItems = new QSpinBox(this, "SpinBox_3");
	NItems->setGeometry(200, 240, 100, 30);
	NItems->setMinimumSize(0, 0);
	NItems->setMaximumSize(32767, 32767);
	NItems->setFocusPolicy(QWidget::StrongFocus);
	NItems->setBackgroundMode(QWidget::PaletteBackground);
	#if QT_VERSION < 300
	NItems->setFontPropagation(QWidget::SameFont);
	NItems->setPalettePropagation(QWidget::SameFont);
	NItems->setFrameStyle( 50 );
	NItems->setLineWidth( 2 );
	NItems->setMidLineWidth( 0 );
	NItems->QFrame::setMargin( 0 );
	#endif
	NItems->setRange(0, 5000);
	NItems->setSteps(1, 0);
	NItems->setPrefix( "" );
	NItems->setSuffix( "" );
	NItems->setSpecialValueText( "" );
	NItems->setWrapping( FALSE );
	
	///////////////////////////////////////////////////////////////////////////

	QPushButton *qtarch_PushButton_1 = new QPushButton(this, "PushButton_1");
	qtarch_PushButton_1->setGeometry(20, 280, 100, 30);
	qtarch_PushButton_1->setMinimumSize(0, 0);
	qtarch_PushButton_1->setMaximumSize(32767, 32767);
	qtarch_PushButton_1->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_1->setBackgroundMode(QWidget::PaletteButton);
	#if QT_VERSION < 300
	qtarch_PushButton_1->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_1->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_1->setText( tr( "Ok" ) );
	qtarch_PushButton_1->setAutoRepeat( FALSE );
	qtarch_PushButton_1->setAutoResize( FALSE );
	qtarch_PushButton_1->setToggleButton( FALSE );
	qtarch_PushButton_1->setDefault( FALSE );
	qtarch_PushButton_1->setAutoDefault( FALSE );
	qtarch_PushButton_1->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_1, SIGNAL(clicked()), SLOT(OkClicked()));
	QPushButton *qtarch_PushButton_2 = new QPushButton(this, "PushButton_2");
	qtarch_PushButton_2->setGeometry(210, 280, 100, 30);
	qtarch_PushButton_2->setMinimumSize(0, 0);
	qtarch_PushButton_2->setMaximumSize(32767, 32767);
	qtarch_PushButton_2->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_2->setBackgroundMode(QWidget::PaletteButton);
	#if QT_VERSION < 300
	qtarch_PushButton_2->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_2->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_2->setText( tr( "&Help" ) );
	qtarch_PushButton_2->setAutoRepeat( FALSE );
	qtarch_PushButton_2->setAutoResize( FALSE );
	qtarch_PushButton_2->setToggleButton( FALSE );
	qtarch_PushButton_2->setDefault( FALSE );
	qtarch_PushButton_2->setAutoDefault( FALSE );
	qtarch_PushButton_2->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_2, SIGNAL(clicked()), SLOT(Help()));
	QPushButton *qtarch_PushButton_3 = new QPushButton(this, "PushButton_3");
	qtarch_PushButton_3->setGeometry(360, 280, 100, 30);
	qtarch_PushButton_3->setMinimumSize(0, 0);
	qtarch_PushButton_3->setMaximumSize(32767, 32767);
	qtarch_PushButton_3->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_3->setBackgroundMode(QWidget::PaletteButton);
	#if QT_VERSION < 300
	qtarch_PushButton_3->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_3->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_3->setText( tr( "Cancel" ) );
	qtarch_PushButton_3->setAutoRepeat( FALSE );
	qtarch_PushButton_3->setAutoResize( FALSE );
	qtarch_PushButton_3->setToggleButton( FALSE );
	qtarch_PushButton_3->setDefault( FALSE );
	qtarch_PushButton_3->setAutoDefault( FALSE );
	qtarch_PushButton_3->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_3, SIGNAL(clicked()), SLOT(reject()));

	resize(480,330);
	setMinimumSize(0, 0);
	setMaximumSize(32767, 32767);
}
MQTT_clientConfigurationData::~MQTT_clientConfigurationData()
{
}

