/**********************************************************************
--- Qt Architect generated file ---
File: Opc_client_daInputData.h
Last generated: Thu Jan 4 16:14:13 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef Opc_client_daInputData_included
#define Opc_client_daInputData_included
#include <qt.h>
#include "valedit.h"
class Opc_client_daInputData : public QWidget
{
	Q_OBJECT
	public:
	Opc_client_daInputData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~Opc_client_daInputData();
	protected:
	//QLineEdit *Low;
	//QLineEdit *High;
	//TIMEEDIT *Interval;
	QLineEdit *ItemID;
	QLineEdit *OPCType;
	QCheckBox *IsWriteble;
};
#endif // Opc_client_daInputData_included

