/**********************************************************************
--- Qt Architect generated file ---
File: Opc_client_daCommandData.h
Last generated: Thu Jan 4 16:13:32 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef Opc_client_daCommandData_included
#define Opc_client_daCommandData_included

#include <qt.h>
#include "valedit.h"

class Opc_client_daCommandData : public QDialog
{
	Q_OBJECT
	public:
	Opc_client_daCommandData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~Opc_client_daCommandData();
	protected slots:
	virtual void Help() =0;
	virtual void OkClicked() =0;
	protected:
	QLabel *Name;
	QLineEdit *Value;
};
#endif // Opc_client_daCommandData_included

