/*								*/
/* testlexerr.c - written by Martin Gonda, 30-11-95             */
/* 								*/
/* code to test the lexer - ie. get as many errors as possible  */
/* generated by the lexan.c, lexer.c modules                    */
/*								*/ 

char a = 'a;			/* error: missing single quote    */

char b = '\0777';		/* error: illegal char oct value  */
                                /* this gets chewed up due to err */
				/* above */

char c = '\x1ff';               /* error: illegal char hex value  */

char d = '\078';

char e[10]="abcdef ;		/* error: unbalanced double quote */
                                /* error: string literal error    */

