//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Designer.rc
//
#define IDD_ABOUTBOX                    100
#define ID_ACTION_MOVER                 103
#define ID_ACTION_SIZER                 104
#define ID_ACTION_ROTATE                105
#define ID_ACTION_VISUAL                106
#define ID_ADD_SIMPLE_VARIABLE          107
#define ID_ADD_OPC_VARIABLE             108
#define ID_ACTION_PLAY_SOUND            109
#define ID_ACTION_CHANGE_IMAGE          110
#define ID_ACTION_COLOR                 111
#define ID_IMPORT_OPC_CHANNELS          112
#define ID_ACTION_CURVE                 113
#define IDR_MAINFRAME                   128
#define IDR_PRIMITIVES                  201
#define IDR_ACTIONS                     202
#define IDB_BITMAP1                     203
#define IDD_PROJECT_IMAGES              205
#define IDD_INPUT_BOX                   207
#define IDD_SCHEMAS                     208
#define IDD_SCHEMA_SETTINGS             209
#define IDD_VARIABLE_DIALOG             210
#define IDR_VARIABLES                   211
#define IDD_SIMLPE_VARIABLE             213
#define IDD_OPC_VARIABLE                215
#define IDD_SELECT_CHANNEL              217
#define IDB_ICONS                       219
#define IDD_PROJECT_SETTINGS            220
#define IDD_DELETE_SCHEMA               221
#define IDD_OBJECTS                     224
#define IDR_ALIGN                       225
#define IDD_PROJECT_SOUNDS              227
#define IDD_IMPORT_OPC_CHANNELS         228
#define IDC_IMAGE_LIST                  1001
#define IDC_LOAD_FROM_FILE              1002
#define IDC_RENAME                      1003
#define IDC_BUTTON3                     1004
#define IDC_DELETE                      1004
#define IDC_BROWSE_COLOR                1004
#define IDC_PREVIEW                     1005
#define IDC_WIDTH                       1006
#define IDC_HEIGHT                      1007
#define IDC_GROUP                       1008
#define IDC_STATIC_W                    1009
#define IDC_STATIC_H                    1010
#define IDC_EDIT1                       1011
#define IDC_VARIABLE_NAME               1012
#define IDC_SCHEMAS                     1013
#define IDC_SCHEMA_NAME                 1014
#define IDC_FIXED_SIZE                  1018
#define IDC_IMAGE_BACKGRD               1019
#define IDC_IMAGE_NAMES                 1022
#define IDC_STRETCH_IMAGE               1023
#define IDC_VARIABLE_LIST               1029
#define IDC_VALUE_SIMPLE_VARIABLE       1031
#define IDC_NAME_SIMPLE_VARIABLE        1032
#define IDC_TYPE_VARIABLE               1035
#define IDC_ADD_VAR                     1037
#define IDC_DEL_VAR                     1038
#define IDC_CHANGE_VAR                  1039
#define IDC_BROWSE_COMPUTER             1040
#define IDC_BROWSE_CHANNEL              1041
#define IDC_NAME_SERVER                 1042
#define IDC_NAME_CHANNEL                1043
#define IDC_NAME_OPC_VARIABLE           1044
#define IDC_NAME_COMPUTER               1045
#define IDC_TREE_CHANNEL                1048
#define IDC_INTERVAL_OPC                1049
#define IDC_COMBO1                      1052
#define IDC_COMBO_NAMES                 1052
#define IDC_RADIO1                      1053
#define IDC_RADIO2                      1054
#define IDC_COLOR_BGD                   1056
#define IDC_LIST_OBJECTS                1058
#define IDC_PLAY                        1060
#define IDC_BUTTON1                     1061
#define IDC_STOP                        1061
#define IDC_VARIABLE_PREFIX             1062
#define ID_VIEW_PROPERTY                32773
#define ID_POLYLINE                     32775
#define ID_RECTANGLE                    32777
#define ID_ELIPSE                       32780
#define ID_VIEW_PRIMITIVES              32782
#define ID_BUTTON32783                  32783
#define ID_EMPTY                        32783
#define IDB_                            32784
#define IDB_BACKGRND                    32784
#define ID_ADD_ACTION                   32784
#define ID_BUTTON32785                  32785
#define ID_DEL_ACTION                   32785
#define ID_CHANGE_                      32788
#define ID_CHANGE_ACTION                32788
#define ID_IMAGE                        32788
#define ID_IMAGES                       32790
#define ID_BUTTON32791                  32791
#define ID_Menu                         32792
#define ID_NEW_SCHEMA                   32794
#define ID_SCHEMAS                      32796
#define ID_SAVE_CURRENT                 32799
#define ID_SETTING_CURRENT              32801
#define ID_VARIABLES                    32803
#define ID_ADD_VARIABLE                 32804
#define ID_DEL_VARIABLE                 32805
#define ID_PROJECT_SETTINGS             32806
#define ID_DELETE_SCHEMA                32808
#define ID_TEXT                         32809
#define ID_BUTTON                       32810
#define ID_BUTTON32812                  32812
#define ID_INPUT                        32812
#define ID_OBJECTS                      32814
#define ID_BACK                         32815
#define ID_FRONT                        32816
#define ID_SELECT                       32818
#define ID_FILE_SAVEAS                  32820
#define ID_SOUND                        32822
#define ID_SOUNDS                       32824
#define ID_USE_GRID                     32827
#define ID_GRAPH                        32828
#define ID_EDIT_COPY32829               32829
#define ID_EDIT_PASTE32830              32830
#define ID_EDIT_CUT32831                32831
#define ID_COPY                         32832
#define ID_CUT                          32833
#define ID_PASTE                        32834

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        228
#define _APS_NEXT_COMMAND_VALUE         32835
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
