/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823PRESENTATION"
 * 	found in "../isoPresentationLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#include <asn_internal.h>

#include "PDVlist.h"

static asn_TYPE_member_t asn_MBR_presentationdatavalues_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct presentationdatavalues, choice.singleASN1type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ANY,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"singleASN1type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct presentationdatavalues, choice.octetaligned),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"octetaligned"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct presentationdatavalues, choice.arbitrary),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"arbitrary"
		},
};
static asn_TYPE_tag2member_t asn_MAP_presentationdatavalues_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* singleASN1type at 92 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* octetaligned at 94 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* arbitrary at 96 */
};
static asn_CHOICE_specifics_t asn_SPC_presentationdatavalues_specs_4 = {
	sizeof(struct presentationdatavalues),
	offsetof(struct presentationdatavalues, _asn_ctx),
	offsetof(struct presentationdatavalues, present),
	sizeof(((struct presentationdatavalues *)0)->present),
	asn_MAP_presentationdatavalues_tag2el_4,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_presentationdatavalues_4 = {
	"presentationdatavalues",
	"presentationdatavalues",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_presentationdatavalues_4,
	3,	/* Elements count */
	&asn_SPC_presentationdatavalues_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_PDVlist_1[] = {
	{ ATF_POINTER, 1, offsetof(struct PDVlist, transfersyntaxname),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_Transfersyntaxname,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"transfersyntaxname"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDVlist, presentationcontextidentifier),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Presentationcontextidentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"presentationcontextidentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDVlist, presentationdatavalues),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_presentationdatavalues_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"presentationdatavalues"
		},
};
static ber_tlv_tag_t asn_DEF_PDVlist_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_PDVlist_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* presentationcontextidentifier at 90 */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* transfersyntaxname at 89 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 }, /* singleASN1type at 92 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, 0, 0 }, /* octetaligned at 94 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* arbitrary at 96 */
};
static asn_SEQUENCE_specifics_t asn_SPC_PDVlist_specs_1 = {
	sizeof(struct PDVlist),
	offsetof(struct PDVlist, _asn_ctx),
	asn_MAP_PDVlist_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PDVlist = {
	"PDVlist",
	"PDVlist",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PDVlist_tags_1,
	sizeof(asn_DEF_PDVlist_tags_1)
		/sizeof(asn_DEF_PDVlist_tags_1[0]), /* 1 */
	asn_DEF_PDVlist_tags_1,	/* Same as above */
	sizeof(asn_DEF_PDVlist_tags_1)
		/sizeof(asn_DEF_PDVlist_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PDVlist_1,
	3,	/* Elements count */
	&asn_SPC_PDVlist_specs_1	/* Additional specs */
};

