/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE1"
 * 	found in "../isoAcseLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Authenticationvalue_H_
#define	_Authenticationvalue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <GraphicString.h>
#include <BIT_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Authenticationvalue_PR {
	Authenticationvalue_PR_NOTHING,	/* No components present */
	Authenticationvalue_PR_charstring,
	Authenticationvalue_PR_bitstring
} Authenticationvalue_PR;

/* Authenticationvalue */
typedef struct Authenticationvalue {
	Authenticationvalue_PR present;
	union Authenticationvalue_u {
		GraphicString_t	 charstring;
		BIT_STRING_t	 bitstring;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Authenticationvalue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Authenticationvalue;

#ifdef __cplusplus
}
#endif

#endif	/* _Authenticationvalue_H_ */
