#! /bin/sh
#
# usage runsent *.c

usage='
  echo ""
  echo "    usage: runsent C-files"
  echo " "

'

if [ $# -eq 0 ] ; then
  eval "$usage";
  exit 1;
fi

#cd ../main
#make sentinel
#cd ../test

for arg
do
        SE_ERROR_FILE="$arg.snt"
        export SE_ERROR_FILE
        rm -f $arg.snt
        echo $SE_ERROR_FILE
        echo "#include $arg" > runsent.in
        echo ":exit" >> runsent.in 
        eic -s < runsent.in 
done

#for arg
#do
#	MA_OUTPUT_MODE=ascii
#        MA_ERROR_FILE="$arg.snt"
#        export MA_ERROR_FILE
#	export MA_OUTPUT_MODE
#        rm -f $arg.snt
#        echo $MA_ERROR_FILE
#        echo "#include $arg" > runsent.in
#        echo ":exit" >> runsent.in 
#        eic -s < runsent.in 
#done

#rm -f runsent.in
#cd ../main
#rm eicc
#make eic





