/**********************************************************************
--- Qt Architect generated file ---
File: ActionConfigureData.h
Last generated: Thu Jan 4 15:52:11 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef ActionConfigureData_included
#define ActionConfigureData_included
#include <qt.h>
class ActionConfigureData : public QDialog
{
	Q_OBJECT
	public:
	ActionConfigureData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~ActionConfigureData();
	protected slots:
	virtual void Help() =0;
	virtual void OkClicked() =0;
	protected:
	QLabel *Name;
	QLineEdit *MeasureAction;
	QLineEdit *AlarmAction;
};
#endif // ActionConfigureData_included

