/**********************************************************************
--- Qt Architect generated file ---
File: SimulatorUnitData.h
Last generated: Wed May 10 09:34:43 2000
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef SimulatorUnitData_included
#define SimulatorUnitData_included
#include <qt.h>
class SimulatorUnitData : public QDialog
{
	Q_OBJECT
	public:
	SimulatorUnitData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~SimulatorUnitData();
};
#endif // SimulatorUnitData_included

