/**********************************************************************
--- Qt Architect generated file ---
File: SimulatorDigitalData.h
Last generated: Thu Jan 4 16:18:59 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef SimulatorDigitalData_included
#define SimulatorDigitalData_included
#include <qt.h>
#include "valedit.h"
class SimulatorDigitalData : public QWidget
{
	Q_OBJECT
	public:
	SimulatorDigitalData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~SimulatorDigitalData();
	protected:
	TIMEEDIT *Time;
	INTEDIT *Mean;
	INTEDIT *Variation;
};
#endif // SimulatorDigitalData_included

