/**********************************************************************
--- Qt Architect generated file ---
File: SampleCfgData.h
Last generated: Thu Jan 4 15:59:55 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef SampleCfgData_included
#define SampleCfgData_included
#include <qt.h>

class SampleCfgData : public QDialog
{
	Q_OBJECT
	public:
	SampleCfgData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~SampleCfgData();
	protected slots:
	virtual void Help() =0;
	virtual void Limits() =0;
	virtual void TypeChanged(int) =0;
	virtual void IpIndexChanged(int) =0;
	virtual void Rename() =0;
	virtual void Delete() =0;
	virtual void UnitChanged(int) =0;
	virtual void Changed(QListViewItem*) =0;
	virtual void ListClicked(int, QListViewItem*, const QPoint &, int) = 0;
	virtual void Actions() =0;
	virtual void Apply() =0;
	virtual void New() =0;
	protected:
	QPushButton *ApplyButton;
	QPushButton *NewButton;
	QPushButton *DeleteButton;
	QLabel *Name;
	QComboBox *Unit;
	QLineEdit *Comment;
	QComboBox *Type;
	QComboBox *InputIndex;
	QComboBox *Units;
	QCheckBox *Enabled;
	QCheckBox *Fileable;
	QFrame *ConfigFrame;
	QCheckBox *LogMode;
	QCheckBox *Retrigger;
	QSpinBox *AlarmThreshold;
	QListView *List;
	QPushButton *RenameButton;
};
#endif // SampleCfgData_included

