#########################
# Part 1: LOCAL DEFINITIONS

       TOP = 
     EXTRA = 
  WARNINGS = 
  INCLUDES = 
       LIB = 

  DEP_LIBS = 
      LIBS = 

      DIRS = 
  MODS_FILE=

#########################
# Part 2: COMMON MAKE PARAMETERS

#########################
# Part 3: LOCAL SOURCES 


#########################
# Part 4: LOCAL TARGETS  

#### scripts

all::
install::
clean::
clobber::
headers::

#########################
# Part 5: COMMON RULES and 
#     and default Targets

#########################
# Part 6: DEPENDENCIES

