CUSTLIBRARIES=$(shell wx-config --libs)

CUSTINCLUDES=$(shell wx-config --cflags) -DWXUSINGDLL -Wno-long-long -Wno-variadic-macros

CUSTOBJECTS=v4l2_capture.o convert.o

include ../linux.mk



