/**********************************************************************
--- Qt Architect generated file ---
File: Iec61850driverInputData.h
Last generated: Thu Jan 4 16:14:13 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef Iec61850driverInputData_included
#define Iec61850driverInputData_included
#include <qt.h>
#include "valedit.h"
class Iec61850driverInputData : public QWidget
{
	Q_OBJECT
	public:
	Iec61850driverInputData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~Iec61850driverInputData();
	protected:
	//TIMEEDIT *Time;
	//INTEDIT *Mean;
	//INTEDIT *Variation;
	INTEDIT *IOA;
};
#endif // Iec61850driverInputData_included

