/**********************************************************************
--- Qt Architect generated file ---
File: TagCfgDigitalData.cpp
Last generated: Thu Jan 4 16:04:27 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#include <qt.h>
#include "TagCfgDigitalData.h"

TagCfgDigitalData::TagCfgDigitalData(QWidget *parent, const char *name)
: QDialog(parent, name, TRUE, 208)
{
	QLabel *qtarch_Label_20 = new QLabel(this, "Label_20");
	qtarch_Label_20->setGeometry(30, 20, 60, 30);
	qtarch_Label_20->setMinimumSize(0, 0);
	qtarch_Label_20->setMaximumSize(32767, 32767);
	qtarch_Label_20->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_20->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_20->setFontPropagation(QWidget::SameFont);
	qtarch_Label_20->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_20->setFrameStyle( 0 );
	qtarch_Label_20->setLineWidth( 1 );
	qtarch_Label_20->setMidLineWidth( 0 );
	qtarch_Label_20->QFrame::setMargin( 0 );
	qtarch_Label_20->setText( tr( "Name" ) );
	qtarch_Label_20->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_20->setMargin( 0 );
	Name = new QComboBox(FALSE, this, "ComboBox_10");
	Name->setGeometry(100, 20, 360, 30);
	Name->setMinimumSize(0, 0);
	Name->setMaximumSize(32767, 32767);
	Name->setFocusPolicy(QWidget::StrongFocus);
	Name->setBackgroundMode(QWidget::NoBackground);
#if QT_VERSION < 300
	Name->setFontPropagation(QWidget::SameFont);
	Name->setPalettePropagation(QWidget::SameFont);
	#endif
	Name->setSizeLimit( 10 );
	Name->setAutoResize( FALSE );
	Name->setMaxCount( 2147483647 );
	Name->setAutoCompletion( FALSE );
	connect(Name, SIGNAL(activated(int)), SLOT(SelChanged(int)));
	connect(Name, SIGNAL(highlighted(int)), SLOT(SelChanged(int)));
	QFrame *qtarch_Frame_4 = new QFrame(this, "Frame_4");
	qtarch_Frame_4->setGeometry(30, 60, 430, 70);
	qtarch_Frame_4->setMinimumSize(0, 0);
	qtarch_Frame_4->setMaximumSize(32767, 32767);
	qtarch_Frame_4->setFocusPolicy(QWidget::NoFocus);
	qtarch_Frame_4->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Frame_4->setFontPropagation(QWidget::SameFont);
	qtarch_Frame_4->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Frame_4->setFrameStyle( 51 );
	qtarch_Frame_4->setLineWidth( 2 );
	qtarch_Frame_4->setMidLineWidth( 0 );
	qtarch_Frame_4->QFrame::setMargin( 0 );
	UAEnabled = new QCheckBox(this, "CheckBox_8");
	UAEnabled->setGeometry(340, 80, 80, 30);
	UAEnabled->setMinimumSize(0, 0);
	UAEnabled->setMaximumSize(32767, 32767);
	UAEnabled->setFocusPolicy(QWidget::TabFocus);
	UAEnabled->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	UAEnabled->setFontPropagation(QWidget::SameFont);
	UAEnabled->setPalettePropagation(QWidget::SameFont);
	#endif
	UAEnabled->setText( tr( "Enabled" ) );
	UAEnabled->setAutoRepeat( FALSE );
	UAEnabled->setAutoResize( FALSE );
	UAEnabled->setChecked( FALSE );
	UpperAlarm = new QLineEdit(this, "LineEdit_7");
	UpperAlarm->setGeometry(180, 80, 140, 30);
	UpperAlarm->setMinimumSize(0, 0);
	UpperAlarm->setMaximumSize(32767, 32767);
	UpperAlarm->setFocusPolicy(QWidget::StrongFocus);
	UpperAlarm->setBackgroundMode(QWidget::PaletteBase);
#if QT_VERSION < 300
	UpperAlarm->setFontPropagation(QWidget::SameFont);
	UpperAlarm->setPalettePropagation(QWidget::SameFont);
	#endif
	UpperAlarm->setText( tr( "0" ) );
	UpperAlarm->setMaxLength( 16 );
	UpperAlarm->setFrame( QLineEdit::Normal );
	UpperAlarm->setFrame( TRUE );
	UpperAlarm->setAlignment( AlignLeft );
	QLabel *qtarch_Label_21 = new QLabel(this, "Label_21");
	qtarch_Label_21->setGeometry(50, 80, 100, 30);
	qtarch_Label_21->setMinimumSize(0, 0);
	qtarch_Label_21->setMaximumSize(32767, 32767);
	qtarch_Label_21->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_21->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_21->setFontPropagation(QWidget::SameFont);
	qtarch_Label_21->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_21->setFrameStyle( 0 );
	qtarch_Label_21->setLineWidth( 1 );
	qtarch_Label_21->setMidLineWidth( 0 );
	qtarch_Label_21->QFrame::setMargin( 0 );
	qtarch_Label_21->setText( tr( "Alarm" ) );
	qtarch_Label_21->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_21->setMargin( 0 );
	
	ApplyButton = new QPushButton(this, "PushButton_20");
	ApplyButton->setGeometry(30, 140, 100, 30);
	ApplyButton->setMinimumSize(0, 0);
	ApplyButton->setMaximumSize(32767, 32767);
	ApplyButton->setFocusPolicy(QWidget::TabFocus);
	ApplyButton->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	ApplyButton->setFontPropagation(QWidget::SameFont);
	ApplyButton->setPalettePropagation(QWidget::SameFont);
	#endif
	ApplyButton->setText( tr( "Apply" ) );
	ApplyButton->setAutoRepeat( FALSE );
	ApplyButton->setAutoResize( FALSE );
	ApplyButton->setToggleButton( FALSE );
	ApplyButton->setDefault( FALSE );
	ApplyButton->setAutoDefault( FALSE );
	ApplyButton->setIsMenuButton( FALSE );
	connect(ApplyButton, SIGNAL(clicked()), SLOT(Apply()));
	QPushButton *qtarch_PushButton_21 = new QPushButton(this, "PushButton_21");
	qtarch_PushButton_21->setGeometry(200, 140, 100, 30);
	qtarch_PushButton_21->setMinimumSize(0, 0);
	qtarch_PushButton_21->setMaximumSize(32767, 32767);
	qtarch_PushButton_21->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_21->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_21->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_21->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_21->setText( tr( "Help" ) );
	qtarch_PushButton_21->setAutoRepeat( FALSE );
	qtarch_PushButton_21->setAutoResize( FALSE );
	qtarch_PushButton_21->setToggleButton( FALSE );
	qtarch_PushButton_21->setDefault( FALSE );
	qtarch_PushButton_21->setAutoDefault( FALSE );
	qtarch_PushButton_21->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_21, SIGNAL(clicked()), SLOT(Help()));
	QPushButton *qtarch_PushButton_22 = new QPushButton(this, "PushButton_22");
	qtarch_PushButton_22->setGeometry(360, 140, 100, 30);
	qtarch_PushButton_22->setMinimumSize(0, 0);
	qtarch_PushButton_22->setMaximumSize(32767, 32767);
	qtarch_PushButton_22->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_22->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_22->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_22->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_22->setText( tr( "Exit" ) );
	qtarch_PushButton_22->setAutoRepeat( FALSE );
	qtarch_PushButton_22->setAutoResize( FALSE );
	qtarch_PushButton_22->setToggleButton( FALSE );
	qtarch_PushButton_22->setDefault( FALSE );
	qtarch_PushButton_22->setAutoDefault( FALSE );
	qtarch_PushButton_22->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_22, SIGNAL(clicked()), SLOT(reject()));
	resize(490,190);
	setMinimumSize(0, 0);
	setMaximumSize(32767, 32767);
}
TagCfgDigitalData::~TagCfgDigitalData()
{
}

