/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823PRESENTATION"
 * 	found in "../isoPresentationLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Resultlist_H_
#define	_Resultlist_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "Result.h"
#include "Transfersyntaxname.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum providerreason {
	providerreason_reasonnotspecified	= 0,
	providerreason_abstractsyntaxnotsupported	= 1,
	providerreason_proposedtransfersyntaxesnotsupported	= 2,
	providerreason_locallimitonDCSexceeded	= 3
} e_providerreason;

/* Resultlist */
typedef struct Resultlist {
	A_SEQUENCE_OF(struct Member {
		Result_t	 result;
		Transfersyntaxname_t	*transfersyntaxname	/* OPTIONAL */;
		long	*providerreason	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Resultlist_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Resultlist;

#ifdef __cplusplus
}
#endif

#endif	/* _Resultlist_H_ */
