/**********************************************************************
--- Qt Architect generated file ---
File: Modbus_driverInputData.h
Last generated: Thu Jan 4 16:14:13 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef Modbus_driverInputData_included
#define Modbus_driverInputData_included
#include <qt.h>
#include "valedit.h"
class Modbus_driverInputData : public QWidget
{
	Q_OBJECT
	public:
	Modbus_driverInputData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~Modbus_driverInputData();
	protected:
	//TIMEEDIT *Time;
	//INTEDIT *Mean;
	//INTEDIT *Variation;
	INTEDIT *IOA;
};
#endif // Modbus_driverInputData_included

