/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE1"
 * 	found in "../isoAcseLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#include <asn_internal.h>

#include "AAREapdu.h"

static asn_TYPE_member_t asn_MBR_AAREapdu_1[] = {
	{ ATF_POINTER, 1, offsetof(struct AAREapdu, protocolversion),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"protocolversion"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AAREapdu, applicationcontextname),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"applicationcontextname"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AAREapdu, result),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Associateresult,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"result"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AAREapdu, resultsourcediagnostic),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Associatesourcediagnostic,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"resultsourcediagnostic"
		},
	{ ATF_POINTER, 7, offsetof(struct AAREapdu, respondingAPtitle),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_APtitle,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"respondingAPtitle"
		},
	{ ATF_POINTER, 6, offsetof(struct AAREapdu, respondingAEqualifier),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AEqualifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"respondingAEqualifier"
		},
	{ ATF_POINTER, 5, offsetof(struct AAREapdu, respondingAPinvocationidentifier),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_APinvocationidentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"respondingAPinvocationidentifier"
		},
	{ ATF_POINTER, 4, offsetof(struct AAREapdu, respondingAEinvocationidentifier),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_AEinvocationidentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"respondingAEinvocationidentifier"
		},
	{ ATF_POINTER, 3, offsetof(struct AAREapdu, applicationcontextnamelist),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Applicationcontextnamelist,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"applicationcontextnamelist"
		},
	{ ATF_POINTER, 2, offsetof(struct AAREapdu, implementationinformation),
		(ASN_TAG_CLASS_CONTEXT | (29 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Implementationdata,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"implementationinformation"
		},
	{ ATF_POINTER, 1, offsetof(struct AAREapdu, userinformation),
		(ASN_TAG_CLASS_CONTEXT | (30 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Associationinformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"userinformation"
		},
};
static ber_tlv_tag_t asn_DEF_AAREapdu_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_AAREapdu_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* protocolversion at 63 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* applicationcontextname at 64 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* result at 65 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* resultsourcediagnostic at 66 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* respondingAPtitle at 67 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* respondingAEqualifier at 68 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* respondingAPinvocationidentifier at 69 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* respondingAEinvocationidentifier at 70 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 8, 0, 0 }, /* applicationcontextnamelist at 79 */
    { (ASN_TAG_CLASS_CONTEXT | (29 << 2)), 9, 0, 0 }, /* implementationinformation at 82 */
    { (ASN_TAG_CLASS_CONTEXT | (30 << 2)), 10, 0, 0 } /* userinformation at 83 */
};
static asn_SEQUENCE_specifics_t asn_SPC_AAREapdu_specs_1 = {
	sizeof(struct AAREapdu),
	offsetof(struct AAREapdu, _asn_ctx),
	asn_MAP_AAREapdu_tag2el_1,
	11,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_AAREapdu = {
	"AAREapdu",
	"AAREapdu",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AAREapdu_tags_1,
	sizeof(asn_DEF_AAREapdu_tags_1)
		/sizeof(asn_DEF_AAREapdu_tags_1[0]) - 1, /* 1 */
	asn_DEF_AAREapdu_tags_1,	/* Same as above */
	sizeof(asn_DEF_AAREapdu_tags_1)
		/sizeof(asn_DEF_AAREapdu_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_AAREapdu_1,
	11,	/* Elements count */
	&asn_SPC_AAREapdu_specs_1	/* Additional specs */
};

