/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE1"
 * 	found in "../isoAcseLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_AARQapdu_H_
#define	_AARQapdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <OBJECT_IDENTIFIER.h>
#include "APinvocationidentifier.h"
#include "AEinvocationidentifier.h"
#include "ACSErequirements.h"
#include "Mechanismname.h"
#include "Implementationdata.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct APtitle;
struct AEqualifier;
struct Authenticationvalue;
struct Applicationcontextnamelist;
struct Associationinformation;

/* AARQapdu */
typedef struct AARQapdu {
	BIT_STRING_t	*protocolversion	/* OPTIONAL */;
	OBJECT_IDENTIFIER_t	 applicationcontextname;
	struct APtitle	*calledAPtitle	/* OPTIONAL */;
	struct AEqualifier	*calledAEqualifier	/* OPTIONAL */;
	APinvocationidentifier_t	*calledAPinvocationidentifier	/* OPTIONAL */;
	AEinvocationidentifier_t	*calledAEinvocationidentifier	/* OPTIONAL */;
	struct APtitle	*callingAPtitle	/* OPTIONAL */;
	struct AEqualifier	*callingAEqualifier	/* OPTIONAL */;
	APinvocationidentifier_t	*callingAPinvocationidentifier	/* OPTIONAL */;
	AEinvocationidentifier_t	*callingAEinvocationidentifier	/* OPTIONAL */;
	ACSErequirements_t	*senderacserequirements	/* OPTIONAL */;
	Mechanismname_t	*mechanismname	/* OPTIONAL */;
	struct Authenticationvalue	*callingauthenticationvalue	/* OPTIONAL */;
	struct Applicationcontextnamelist	*applicationcontextnamelist	/* OPTIONAL */;
	Implementationdata_t	*implementationinformation	/* OPTIONAL */;
	struct Associationinformation	*userinformation	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AARQapdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AARQapdu;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "APtitle.h"
#include "AEqualifier.h"
#include "Authenticationvalue.h"
#include "Applicationcontextnamelist.h"
#include "Associationinformation.h"

#endif	/* _AARQapdu_H_ */
