/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE1"
 * 	found in "../isoAcseLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Associatesourcediagnostic_H_
#define	_Associatesourcediagnostic_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Associatesourcediagnostic_PR {
	Associatesourcediagnostic_PR_NOTHING,	/* No components present */
	Associatesourcediagnostic_PR_acseserviceuser,
	Associatesourcediagnostic_PR_acseserviceprovider
} Associatesourcediagnostic_PR;
typedef enum acseserviceuser {
	acseserviceuser_null	= 0,
	acseserviceuser_noreasongiven	= 1,
	acseserviceuser_applicationcontextnamenotsupported	= 2,
	acseserviceuser_callingAPtitlenotrecognized	= 3,
	acseserviceuser_callingAPinvocationidentifiernotrecognized	= 4,
	acseserviceuser_callingAEqualifiernotrecognized	= 5,
	acseserviceuser_callingAEinvocationidentifiernotrecognized	= 6,
	acseserviceuser_calledAPtitlenotrecognized	= 7,
	acseserviceuser_calledAPinvocationidentifiernotrecognized	= 8,
	acseserviceuser_calledAEqualifiernotrecognized	= 9,
	acseserviceuser_calledAEinvocationidentifiernotrecognized	= 10,
	acseserviceuser_authenticationmechanismnamenotrecognized	= 11,
	acseserviceuser_authenticationmechanismnamerequired	= 12,
	acseserviceuser_authenticationfailure	= 13,
	acseserviceuser_authenticationrequired	= 14
} e_acseserviceuser;
typedef enum acseserviceprovider {
	acseserviceprovider_null	= 0,
	acseserviceprovider_noreasongiven	= 1,
	acseserviceprovider_nocommonacseversion	= 2
} e_acseserviceprovider;

/* Associatesourcediagnostic */
typedef struct Associatesourcediagnostic {
	Associatesourcediagnostic_PR present;
	union Associatesourcediagnostic_u {
		long	 acseserviceuser;
		long	 acseserviceprovider;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Associatesourcediagnostic_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Associatesourcediagnostic;

#ifdef __cplusplus
}
#endif

#endif	/* _Associatesourcediagnostic_H_ */
