/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE1"
 * 	found in "../isoAcseLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#include <asn_internal.h>

#include "Authenticationvalue.h"

static asn_TYPE_member_t asn_MBR_Authenticationvalue_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Authenticationvalue, choice.charstring),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GraphicString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"charstring"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Authenticationvalue, choice.bitstring),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bitstring"
		},
};
static asn_TYPE_tag2member_t asn_MAP_Authenticationvalue_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* charstring at 227 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* bitstring at 236 */
};
static asn_CHOICE_specifics_t asn_SPC_Authenticationvalue_specs_1 = {
	sizeof(struct Authenticationvalue),
	offsetof(struct Authenticationvalue, _asn_ctx),
	offsetof(struct Authenticationvalue, present),
	sizeof(((struct Authenticationvalue *)0)->present),
	asn_MAP_Authenticationvalue_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Authenticationvalue = {
	"Authenticationvalue",
	"Authenticationvalue",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_Authenticationvalue_1,
	2,	/* Elements count */
	&asn_SPC_Authenticationvalue_specs_1	/* Additional specs */
};

