/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE1"
 * 	found in "../isoAcseLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Implementationdata_H_
#define	_Implementationdata_H_


#include <asn_application.h>

/* Including external dependencies */
#include <GraphicString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Implementationdata */
typedef GraphicString_t	 Implementationdata_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Implementationdata;
asn_struct_free_f Implementationdata_free;
asn_struct_print_f Implementationdata_print;
asn_constr_check_f Implementationdata_constraint;
ber_type_decoder_f Implementationdata_decode_ber;
der_type_encoder_f Implementationdata_encode_der;
xer_type_decoder_f Implementationdata_decode_xer;
xer_type_encoder_f Implementationdata_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Implementationdata_H_ */
