/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE1"
 * 	found in "../isoAcseLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Releaserequestreason_H_
#define	_Releaserequestreason_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Releaserequestreason {
	Releaserequestreason_normal	= 0,
	Releaserequestreason_urgent	= 1,
	Releaserequestreason_userdefined	= 30
} e_Releaserequestreason;

/* Releaserequestreason */
typedef long	 Releaserequestreason_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Releaserequestreason;
asn_struct_free_f Releaserequestreason_free;
asn_struct_print_f Releaserequestreason_print;
asn_constr_check_f Releaserequestreason_constraint;
ber_type_decoder_f Releaserequestreason_decode_ber;
der_type_encoder_f Releaserequestreason_encode_der;
xer_type_decoder_f Releaserequestreason_decode_xer;
xer_type_encoder_f Releaserequestreason_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Releaserequestreason_H_ */
