/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823PRESENTATION"
 * 	found in "../isoPresentationLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Calledpresentationselector_H_
#define	_Calledpresentationselector_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Presentationselector.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Calledpresentationselector */
typedef Presentationselector_t	 Calledpresentationselector_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Calledpresentationselector;
asn_struct_free_f Calledpresentationselector_free;
asn_struct_print_f Calledpresentationselector_print;
asn_constr_check_f Calledpresentationselector_constraint;
ber_type_decoder_f Calledpresentationselector_decode_ber;
der_type_encoder_f Calledpresentationselector_encode_der;
xer_type_decoder_f Calledpresentationselector_decode_xer;
xer_type_encoder_f Calledpresentationselector_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Calledpresentationselector_H_ */
