/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823PRESENTATION"
 * 	found in "../isoPresentationLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_CPAPPDU_H_
#define	_CPAPPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Modeselector.h"
#include "Protocolversion.h"
#include "Respondingpresentationselector.h"
#include "Presentationrequirements.h"
#include "Usersessionrequirements.h"
#include <constr_SEQUENCE.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum CPAPPDU_PR {
	CPAPPDU_PR_modeselector,	/* Member modeselector is present */
	CPAPPDU_PR_normalmodeparameters,	/* Member normalmodeparameters is present */
} CPAPPDU_PR;

/* Forward declarations */
struct Resultlist;
struct Userdata;

/* CPAPPDU */
typedef struct CPAPPDU {
	Modeselector_t	 modeselector;
	struct normalmodeparameters {
		Protocolversion_t	*protocolversion	/* DEFAULT {version 1} */;
		Respondingpresentationselector_t	*respondingpresentationselector	/* OPTIONAL */;
		struct Resultlist	*presentationcontextdefinitionresultlist	/* OPTIONAL */;
		Presentationrequirements_t	*presentationrequirements	/* OPTIONAL */;
		Usersessionrequirements_t	*usersessionrequirements	/* OPTIONAL */;
		struct Userdata	*userdata	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *normalmodeparameters;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pCPAPPDU, CPAPPDU_PR_x) */
	unsigned int _presence_map
		[((2+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CPAPPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CPAPPDU;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Presentationcontextdefinitionresultlist.h"
#include "Userdata.h"

#endif	/* _CPAPPDU_H_ */
