/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823PRESENTATION"
 * 	found in "../isoPresentationLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Fullyencodeddata_H_
#define	_Fullyencodeddata_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PDVlist;

/* Fullyencodeddata */
typedef struct Fullyencodeddata {
	A_SEQUENCE_OF(struct PDVlist) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Fullyencodeddata_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Fullyencodeddata;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PDVlist.h"

#endif	/* _Fullyencodeddata_H_ */
