/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823PRESENTATION"
 * 	found in "../isoPresentationLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Presentationcontextidentifier_H_
#define	_Presentationcontextidentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Presentationcontextidentifier */
typedef long	 Presentationcontextidentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Presentationcontextidentifier;
asn_struct_free_f Presentationcontextidentifier_free;
asn_struct_print_f Presentationcontextidentifier_print;
asn_constr_check_f Presentationcontextidentifier_constraint;
ber_type_decoder_f Presentationcontextidentifier_decode_ber;
der_type_encoder_f Presentationcontextidentifier_encode_der;
xer_type_decoder_f Presentationcontextidentifier_decode_xer;
xer_type_encoder_f Presentationcontextidentifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Presentationcontextidentifier_H_ */
