/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823PRESENTATION"
 * 	found in "../isoPresentationLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Simplyencodeddata_H_
#define	_Simplyencodeddata_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Simplyencodeddata */
typedef OCTET_STRING_t	 Simplyencodeddata_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Simplyencodeddata;
asn_struct_free_f Simplyencodeddata_free;
asn_struct_print_f Simplyencodeddata_print;
asn_constr_check_f Simplyencodeddata_constraint;
ber_type_decoder_f Simplyencodeddata_decode_ber;
der_type_encoder_f Simplyencodeddata_encode_der;
xer_type_decoder_f Simplyencodeddata_decode_xer;
xer_type_encoder_f Simplyencodeddata_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Simplyencodeddata_H_ */
