/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823PRESENTATION"
 * 	found in "../isoPresentationLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Userdata_H_
#define	_Userdata_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Simplyencodeddata.h"
#include "Fullyencodeddata.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Userdata_PR {
	Userdata_PR_NOTHING,	/* No components present */
	Userdata_PR_simplyencodeddata,
	Userdata_PR_fullyencodeddata
} Userdata_PR;

/* Userdata */
typedef struct Userdata {
	Userdata_PR present;
	union Userdata_u {
		Simplyencodeddata_t	 simplyencodeddata;
		Fullyencodeddata_t	 fullyencodeddata;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Userdata_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Userdata;

#ifdef __cplusplus
}
#endif

#endif	/* _Userdata_H_ */
