#ifdef ENV_WINDOWS
//#pragma warning (disable: 4018)
//#pragma warning (disable: 4663)
 #pragma warning (disable: 4786)
 #pragma warning (disable: 4284)
#endif

#define G_RES

#include <wx/wx.h>
#include "common/oapcResourceBundle.h"
#include "globals.h"

oapcResourceBundle *__wxResBundleMe;

#include "globals.cpp"

#include "common/foldpanelbar.cpp"
#include "common/foldpanelitem.cpp"
#include "common/captionbar.cpp"

#include "kwxCtrl/AngularMeter.cpp"
#include "kwxCtrl/AngularRegulator.cpp"
#include "kwxCtrl/LCDWindow.cpp"
#include "common/oapcResourceBundle.cpp"
#include "wxFlatNotebook/renderer.cpp"
#include "wxFlatNotebook/wxFlatNotebook.cpp"

#include "DlgConfigflowBase.cpp"
#include "DlgConfigflowName.cpp"
#include "DlgConfigflowConvertNum2Char.cpp"
#include "DlgConfigflowConvertNum2Digi.cpp"
#include "DlgConfigflowConvertMixed2Char.cpp"
#include "DlgConfigflowConvert2Pair.cpp"
#include "DlgConfigflowLogic.cpp"
#include "DlgConfigflowDelay.cpp"
#include "DlgConfigflowStart.cpp"
#include "DlgConfigflowTimer.cpp"
#include "DlgConfigflowLogRecorder.cpp"
#include "DlgConfigflowGroup.cpp"
#include "DlgConfigflowConvertDigi2Num.cpp"
#include "DlgConfigflowConvertDigi2Char.cpp"
#include "DlgConfigflowConvertChar2Num.cpp"
#include "DlgConfigflowConvertChar2Digi.cpp"

#include "DlgConfigflowExternalIOLib.cpp"
#include "DlgDataFlowhmiHSlider.cpp"
#include "DlgControlSelector.cpp"
#include "DlgDataFlowhmiTextField.cpp"
#include "DlgProjectSettings.cpp"
#include "DlgUserpriviSettings.cpp"
#include "DlgUsers.cpp"
#include "DlgObjectProp.cpp"
#include "ChangePwdDlg.cpp"

#include "HMICanvas.cpp"
#include "FlowCanvas.cpp"
#include "PlugInPanel.cpp"

#include "MainApp.cpp"
#include "MainWin.cpp"
#include "ObjectList.cpp"
#include "UserList.cpp"
#include "UserData.cpp"
#include "FlowObjects.cpp"
#include "flowConnection.cpp"
#include "ExternalIOLibs.cpp"
#include "ExternalIOLib.cpp"
#include "ExternalMacros.cpp"
#include "ExternalMacro.cpp"
#include "IOElementDefinition.cpp"
#include "BasePanel.cpp"
#include "XMLDecoder.cpp"
#include "LogDefPanel.cpp"
#include "oapcNoSpaceCtrl.cpp"
#include "PCompiler.cpp"
#include "PrivilegePanel.cpp"
#include "oapcSpinCtrl.cpp"

#include "flowObject.cpp"
#include "flowConverterDigi2Num.cpp"
#include "flowConverter.cpp"
#include "flowConverter2Pair.cpp"
#include "flowConverterPair2.cpp"
#include "flowConverterDigi2Pair.cpp"
#include "flowConverterDigi2Char.cpp"
#include "flowConverterChar2Num.cpp"
#include "flowConverterChar2Digi.cpp"
#include "flowConverterChar2Pair.cpp"
#include "flowConverterNum2Char.cpp"
#include "flowConverterNum2Digi.cpp"
#include "flowConverterNum2Pair.cpp"
#include "flowConverterMixed2Char.cpp" 
#include "flowConverterBin2Pair.cpp"
#include "flowConverterPair2Digi.cpp"
#include "flowConverterPair2Char.cpp"
#include "flowConverterPair2Num.cpp"
#include "flowConverterPair2Bin.cpp"
#include "flowExternalIOLib.cpp"
#include "flowGroup.cpp"
#include "flowDigiTrigGate.cpp"
#include "flowDigiGate.cpp"
#include "flowNumTrigGate.cpp"
#include "flowNumGate.cpp"
#include "flowCharTrigGate.cpp"
#include "flowCharGate.cpp"
#include "flowBinTrigGate.cpp"
#include "flowBinGate.cpp"
#include "flowLogicDigiNOT.cpp"
#include "flowLogicDigiRSFF.cpp"
#include "flowLogicDigiTFF.cpp"
#include "flowLogicNumNOT.cpp"
#include "flowLogicDigiNOP.cpp"
#include "flowLogicNumNOP.cpp"
#include "flowLogicCharNOP.cpp"
#include "flowLogicBinNOP.cpp"
#include "flowLogicDigiShift.cpp"
#include "flowLogicNumShift.cpp"
#include "flowLogicCharShift.cpp"
#include "flowLogicBinShift.cpp"
#include "flowMathDigiCmp.cpp"
#include "flowMathNumCmp.cpp"
#include "flowMathCharCmp.cpp"
#include "flowMathDigiCtr.cpp"
#include "flowMathNumCtr.cpp"
#include "flowMathCharCtr.cpp"
#include "flowMathBinCtr.cpp"
#include "flowLog.cpp"
#include "flowLogRecorder.cpp"
#include "flowLogInUser.cpp"
#include "flowConverterNum2Bits.cpp"
#include "flowLogic.cpp"
#include "flowLogicNumConcat.cpp"
#include "flowLogicDigiConcat.cpp"
#include "flowTimer.cpp"
#include "flowStart.cpp"
#include "flowStop.cpp"
#include "flowDelay.cpp"
#include "flowISConnect.cpp"

#include "hmiMutex.cpp"
#include "hmiUserMgmntPanel.cpp"

#include "hmiObject.cpp"
#include "hmiPrimitive.cpp"
#include "hmiAdditionalPane.cpp"
#include "hmiAngularMeter.cpp"
#include "hmiAngularRegulator.cpp"
#include "hmiExternalIOLib.cpp"
#include "hmiFloatField.cpp"
#include "hmiHGauge.cpp"
#include "hmiHSlider.cpp"
#include "hmiImage.cpp"
#include "hmiImageButton.cpp"
#include "hmiLCDNumber.cpp"
#include "hmiLine.cpp"
#include "hmiNumField.cpp"
#include "hmiSimpleButton.cpp"
#include "hmiSinglePanel.cpp"
#include "hmiSpecialPanel.cpp"
#include "hmiStackedPane.cpp"
#include "hmiTabbedPane.cpp"
#include "hmiTextField.cpp"
#include "hmiTextLabel.cpp"
#include "hmiToggleButton.cpp"
#include "hmiRadioButton.cpp"
#include "hmiToggleImageButton.cpp"
#include "hmiVSlider.cpp"
#include "hmiVGauge.cpp"


