#ifdef ENV_WINDOWS
 #pragma warning (disable: 4018)
 #pragma warning (disable: 4284)
 #pragma warning (disable: 4663)
 #pragma warning (disable: 4786)
#endif

#define G_RES

#include <wx/wx.h>
#include "common/oapcResourceBundle.h"
#include "globals.h"

oapcResourceBundle *__wxResBundleMe;

#include "common/oapcBinHead.cpp"
#include "kwxCtrl/AngularMeter.cpp"
#include "kwxCtrl/AngularRegulator.cpp"
#include "kwxCtrl/LCDWindow.cpp"
#include "common/oapcResourceBundle.cpp"
#include "common/oapcMutexLocker.cpp"
#include "wxFlatNotebook/renderer.cpp"
#include "wxFlatNotebook/wxFlatNotebook.cpp"

#include "BasePanel.cpp"
#include "ExternalIOLibs.cpp"
#include "ExternalIOLib.cpp"
#include "LogDataCtrl.cpp"
#include "DebugWin.cpp"
#include "DlgDebugParams.cpp"
#include "FlowDataController.cpp"
#include "PCompiler.cpp"
#include "WatchWin.cpp"
#include "DBWatchWin.cpp"
#include "DlgControlSelector.cpp"
#include "ChangePwdDlg.cpp"

#include "UserData.cpp"
#include "UserList.cpp"

#include "flowWalkerPool.cpp"
#include "flowWalkerThread.cpp"
#include "FlowDispatcherThread.cpp"

#include "oapcSpinCtrl.cpp"

#include "OSKeyboard.cpp"
#include "OSNumpad.cpp"

#include "flowObject.cpp"
#include "hmiPrimitive.cpp"
#include "flowConnection.cpp"
#include "flowConverter.cpp"
#include "flowConverter2Pair.cpp"
#include "flowConverterPair2.cpp"
#include "flowConverterChar2Digi.cpp"
#include "flowConverterChar2Num.cpp"
#include "flowConverterChar2Pair.cpp"
#include "flowConverterPair2Char.cpp"
#include "flowConverterPair2Digi.cpp"
#include "flowConverterPair2Num.cpp"
#include "flowConverterPair2Bin.cpp"
#include "flowConverterDigi2Num.cpp"
#include "flowConverterDigi2Char.cpp"
#include "flowConverterDigi2Pair.cpp"
#include "flowConverterNum2Bits.cpp"
#include "flowConverterNum2Char.cpp"
#include "flowConverterNum2Digi.cpp"
#include "flowConverterNum2Pair.cpp"
#include "flowConverterBin2Pair.cpp"
#include "flowDelay.cpp"
#include "flowExternalIOLib.cpp"
#include "flowGroup.cpp"
#include "flowConverterMixed2Char.cpp"
#include "flowLog.cpp"
#include "flowLogRecorder.cpp"
#include "flowLogInUser.cpp"
#include "flowLogic.cpp"
#include "flowLogicDigiConcat.cpp"
#include "flowLogicDigiNOT.cpp"
#include "flowLogicDigiRSFF.cpp"
#include "flowLogicDigiTFF.cpp"
#include "flowLogicNumConcat.cpp"
#include "flowLogicNumNOT.cpp"
#include "flowLogicDigiNOP.cpp"
#include "flowLogicNumNOP.cpp"
#include "flowLogicCharNOP.cpp"
#include "flowLogicBinNOP.cpp"
#include "flowLogicDigiShift.cpp"
#include "flowLogicNumShift.cpp"
#include "flowLogicCharShift.cpp"
#include "flowLogicBinShift.cpp"
#include "flowMathDigiCmp.cpp"
#include "flowMathNumCmp.cpp"
#include "flowMathCharCmp.cpp"
#include "flowMathDigiCtr.cpp"
#include "flowMathNumCtr.cpp"
#include "flowMathCharCtr.cpp"
#include "flowMathBinCtr.cpp"
#include "flowStart.cpp"
#include "flowStop.cpp"
#include "flowDigiTrigGate.cpp"
#include "flowDigiGate.cpp"
#include "flowNumTrigGate.cpp"
#include "flowNumGate.cpp"
#include "flowCharTrigGate.cpp"
#include "flowCharGate.cpp"
#include "flowBinTrigGate.cpp"
#include "flowBinGate.cpp"
#include "flowTimer.cpp"
#include "flowISConnect.cpp"

#include "HMICanvas.cpp"

#include "hmiObject.cpp"
#include "hmiUserMgmntPanel.cpp"
#include "hmiMutex.cpp"
#include "hmiExternalIOLib.cpp"
#include "hmiSimpleButton.cpp"
#include "hmiTextField.cpp"
#include "hmiToggleButton.cpp"
#include "hmiRadioButton.cpp"
#include "hmiImageButton.cpp"
#include "hmiVSlider.cpp"
#include "hmiHSlider.cpp"
#include "hmiLine.cpp"
#include "hmiTextLabel.cpp"
#include "hmiImage.cpp"
#include "hmiHGauge.cpp"
#include "hmiVGauge.cpp"
#include "hmiNumField.cpp"
#include "hmiFloatField.cpp"
#include "hmiStackedPane.cpp"
#include "hmiTabbedPane.cpp"
#include "hmiAdditionalPane.cpp"
#include "hmiToggleImageButton.cpp"
#include "hmiSinglePanel.cpp"
#include "hmiSpecialPanel.cpp"
#include "hmiAngularMeter.cpp"
#include "hmiLCDNumber.cpp"
#include "hmiAngularRegulator.cpp"

#include "ObjectList.cpp"
#include "globals.cpp"
#include "IOElementDefinition.cpp"

#include "PlayerMainApp.cpp"

