/**********************************************************************
--- Qt Architect generated file ---
File: Rfc1006driverCommandData.h
Last generated: Thu Jan 4 16:13:32 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef Rfc1006driverCommandData_included
#define Rfc1006driverCommandData_included

#include <qt.h>
#include "valedit.h"

class Rfc1006driverCommandData : public QDialog
{
	Q_OBJECT
	public:
	Rfc1006driverCommandData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~Rfc1006driverCommandData();
	protected slots:
	virtual void Help() =0;
	virtual void OkClicked() =0;
	protected:
	QLabel *Name;
	QLineEdit *Value;
};
#endif // Rfc1006driverCommandData_included

