/**********************************************************************
--- Qt Architect generated file ---
File: TimeFrameDlgData.h
Last generated: Fri Feb 16 15:12:43 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef TimeFrameDlgData_included
#define TimeFrameDlgData_included
#include <qt.h>
#include "valedit.h"
class TimeFrameDlgData : public QDialog
{
	Q_OBJECT
	public:
	TimeFrameDlgData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~TimeFrameDlgData();
	DATEEDIT *FromDate;
	TIMEEDIT *FromTime;
	TIMEEDIT *ToTime;
	DATEEDIT *ToDate;
};
#endif // TimeFrameDlgData_included

