/**********************************************************************
--- Qt Architect generated file ---
File: Dnp3driverCommandData.h
Last generated: Thu Jan 4 16:13:32 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef Dnp3driverCommandData_included
#define Dnp3driverCommandData_included

#include <qt.h>
#include "valedit.h"

class Dnp3driverCommandData : public QDialog
{
	Q_OBJECT
	public:
	Dnp3driverCommandData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~Dnp3driverCommandData();
	protected slots:
	virtual void Help() =0;
	virtual void OkClicked() =0;
	protected:
	QLabel *Name;
	QLineEdit *Value;
};
#endif // Dnp3driverCommandData_included

