/**********************************************************************
--- Qt Architect generated file ---
File: Iec104driverConfigurationData.h
Last generated: Thu Jan 4 16:13:32 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef Iec104driverConfigurationData_included
#define Iec104driverConfigurationData_included

#include <qt.h>

class Iec104driverConfigurationData : public QDialog
{
	Q_OBJECT
	public:
	Iec104driverConfigurationData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~Iec104driverConfigurationData();
	protected slots:
	virtual void Help() =0;
	virtual void OkClicked() =0;
	protected:
	QLabel *Name;
	QSpinBox *NItems;
	QLineEdit *IEC104ServerIPAddressText;
	QLineEdit *IEC104ServerIPPortText;
	QLineEdit *IEC104ServerCASDUText;

};
#endif // Iec104driverConfigurationData_included

