//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MultyConfigurator.rc
//
#define IDD_ABOUTBOX                    100
#define ID_TREE                         101
#define IDD_EVENTVIEW                   101
#define ID_ADDITEM                      102
#define ID_ADDFOLDER                    103
#define ID_DELITEM                      104
#define IDR_MAINFRAME                   128
#define IDB_BITMAP1                     202
#define IDD_DB_SETTINGS                 212
#define IDD_SERVICES                    213
#define IDD_CHANNELS                    215
#define IDD_ENTER_USER_EX               217
#define IDD_ENTER_USER                  218
#define IDD_USERS_SETTINGS              219
#define IDD_CHANNEL_SETTINGS            220
#define IDD_DIALOG1                     221
#define IDD_EMPTY                       221
#define IDC_NAME                        1002
#define IDC_CALC                        1003
#define IDC_EXPRESSION                  1004
#define IDC_SERVER                      1005
#define IDC_PORT                        1007
#define IDC_TYPE                        1008
#define IDC_ADDRESS                     1009
#define IDB_ICONS                       1009
#define IDC_SPIN_ADDRESS                1010
#define IDC_CHANNEL                     1011
#define IDC_SPIN_CHANNEL                1013
#define IDC_CANONICAL_TYPE              1014
#define IDC_DTR                         1015
#define IDC_RTS                         1016
#define IDC_READ_INTERVAL               1017
#define IDC_READ_CONST                  1018
#define IDC_READ_MULTI                  1019
#define IDC_WRITE_CONST                 1020
#define IDC_WRITE_MULTI                 1021
#define IDC_WRITE_MULTI2                1022
#define IDC_RETRY                       1022
#define IDC_RADIO_ACCESS                1030
#define IDC_RADIO_MYSQL                 1031
#define IDC_NAME_ACCESS                 1032
#define IDC_PATH_ACCESS                 1033
#define IDC_NAME_MYSQL                  1034
#define IDC_SERVER_MYSQL                1035
#define IDC_START_UART                  1036
#define IDC_STOP_UART                   1037
#define IDC_START_OPC                   1038
#define IDC_STOP_OPC                    1039
#define IDC_START_ROUTER                1040
#define IDC_STOP_ROUTER                 1041
#define IDC_ARCHIVE                     1046
#define IDC_ADD                         1047
#define IDC_DEL                         1048
#define IDC_ARCH_COMPUTER               1049
#define IDC_BROWSE_COMP                 1050
#define IDC_ARCH_SERVER                 1055
#define IDC_ENTER_USER                  1060
#define IDC_ENTER_PASS                  1061
#define IDC_CREATE_ACCESS               1062
#define IDC_CREATE_MYSQL                1063
#define IDC_SET_USER                    1064
#define IDC_CHANNELS                    1065
#define IDC_STATIC1                     1067
#define IDC_RESTART_UART                1070
#define IDC_RESTART_ROUTER              1071
#define IDC_RESTART_OPC                 1072
#define IDC_USER                        1073
#define IDC_PASS                        1074
#define IDC_REPEAT_PASS                 1075
#define IDC_STATIC2                     1076
#define IDC_USERS                       1077
#define IDC_LAST_NAME                   1078
#define IDC_FIRST_NAME                  1079
#define IDC_MIDDLE_NAME                 1080
#define IDC_ADD_USER                    1084
#define IDC_CHANGE_USER                 1085
#define IDC_DEL_USER                    1086
#define IDC_CANEDITUSER                 1092
#define IDC_CANVIEWUSER                 1093
#define IDC_CANVIEWDATA                 1094
#define IDC_CANEDITDATA                 1095
#define IDC_CANEDITCHANNELS             1096
#define IDC_CANEDITEVENTS               1097
#define IDC_CANVIEWEVENTS               1098
#define IDC_STATIC3                     1099
#define IDC_STATIC4                     1100
#define IDC_STATIC5                     1101
#define IDC_STATIC7                     1104
#define IDC_SET_PASSWORD                1106
#define IDC_ADMIN_PERMISSION            1107
#define IDC_USER_PERMISSION             1108
#define IDC_UPDATE_INTERVAL             1110
#define IDC_EVENTS_CHANGE               1111
#define IDC_EVENTS_CROSS_VAL1           1112
#define IDC_ARCH_ON_LESS                1113
#define IDC_EVENTS_CROSS_VAL2           1114
#define IDC_ARCH_ON_GREATER             1115
#define IDC_EVENTS_CROSS_VAL1_SET       1116
#define IDC_EVENTS_CROSS_VAL2_SET       1117
#define IDC_ARCH_ON_LESS_SET            1118
#define IDC_ARCH_ON_GREATER_SET         1119
#define IDC_ARCH_ON_EQUAL               1120
#define IDC_ARCH_ON_LESS_SET2           1121
#define IDC_ARCH_ON_EQUAL_SET           1121
#define IDC_START_ARCHIVE               1125
#define IDC_STOP_ARCHIVE                1126
#define IDC_RESTART_ARCHIVE             1127
#define IDC_GROUP_FORMULA               1128
#define IDC_GROUP_CONNECT               1129
#define IDC_GROUP_DEVICE                1130
#define IDC_STATIC_PORT                 1131
#define IDC_STATIC_TYPE                 1132
#define IDC_STATIC_ADDRESS              1133
#define IDC_STATIC_CHANNEL              1134
#define IDC_EDIT1                       1136
#define IDC_EDIT2                       1137
#define IDC_EDIT3                       1138
#define IDC_EDIT4                       1139
#define IDC_EDIT5                       1140
#define IDC_EDIT6                       1141
#define IDC_EDIT7                       1142
#define IDC_STATIC6                     1143
#define IDC_BROWSE                      1144
#define IDC_IMPORT                      1145
#define ID_ADD_ITEM                     32772
#define ID_ADD_FLDR                     32773
#define ID_DEL_ITEM                     32774
#define ID_ADD_ROUTE                    32775
#define ID_DEL_ROUTE                    32776
#define ID_CHANGE_ROUTE                 32777
#define ID1                             32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        222
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1146
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
