/**********************************************************************
--- Qt Architect generated file ---
File: AckAlarmDlgData.cpp
Last generated: Fri Feb 16 15:09:34 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#include <qt.h>
#include "AckAlarmDlgData.h"
AckAlarmDlgData::AckAlarmDlgData(QWidget *parent, const char *name)
: QDialog(parent, name, TRUE, 208)
{
	QPushButton *qtarch_PushButton_1 = new QPushButton(this, "PushButton_1");
	qtarch_PushButton_1->setGeometry(20, 120, 100, 30);
	qtarch_PushButton_1->setMinimumSize(0, 0);
	qtarch_PushButton_1->setMaximumSize(32767, 32767);
	qtarch_PushButton_1->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_1->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_1->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_1->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_1->setText( tr( "Ok" ) );
	qtarch_PushButton_1->setAutoRepeat( FALSE );
	qtarch_PushButton_1->setAutoResize( FALSE );
	qtarch_PushButton_1->setToggleButton( FALSE );
	qtarch_PushButton_1->setDefault( TRUE );
	qtarch_PushButton_1->setAutoDefault( TRUE );
	qtarch_PushButton_1->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_1, SIGNAL(clicked()), SLOT(accept()));
	QPushButton *qtarch_PushButton_2 = new QPushButton(this, "PushButton_2");
	qtarch_PushButton_2->setGeometry(530, 120, 100, 30);
	qtarch_PushButton_2->setMinimumSize(0, 0);
	qtarch_PushButton_2->setMaximumSize(32767, 32767);
	qtarch_PushButton_2->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_2->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_2->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_2->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_2->setText( tr( "Cancel" ) );
	qtarch_PushButton_2->setAutoRepeat( FALSE );
	qtarch_PushButton_2->setAutoResize( FALSE );
	qtarch_PushButton_2->setToggleButton( FALSE );
	qtarch_PushButton_2->setDefault( FALSE );
	qtarch_PushButton_2->setAutoDefault( FALSE );
	qtarch_PushButton_2->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_2, SIGNAL(clicked()), SLOT(reject()));
	Heading = new QLabel(this, "Label_1");
	Heading->setGeometry(20, 20, 610, 30);
	Heading->setMinimumSize(0, 0);
	Heading->setMaximumSize(32767, 32767);
	Heading->setFocusPolicy(QWidget::NoFocus);
	Heading->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	Heading->setFontPropagation(QWidget::SameFont);
	Heading->setPalettePropagation(QWidget::SameFont);
	#endif
	Heading->setFrameStyle( 50 );
	Heading->setLineWidth( 1 );
	Heading->setMidLineWidth( 0 );
	Heading->QFrame::setMargin( 0 );
	Heading->setText( "" );
	Heading->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	Heading->setMargin( 0 );
	QLabel *qtarch_Label_2 = new QLabel(this, "Label_2");
	qtarch_Label_2->setGeometry(20, 70, 100, 30);
	qtarch_Label_2->setMinimumSize(0, 0);
	qtarch_Label_2->setMaximumSize(32767, 32767);
	qtarch_Label_2->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_2->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_2->setFontPropagation(QWidget::SameFont);
	qtarch_Label_2->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_2->setFrameStyle( 0 );
	qtarch_Label_2->setLineWidth( 1 );
	qtarch_Label_2->setMidLineWidth( 0 );
	qtarch_Label_2->QFrame::setMargin( 0 );
	qtarch_Label_2->setText( tr( "Comment" ) );
	qtarch_Label_2->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_2->setMargin( 0 );
	Comment = new QLineEdit(this, "LineEdit_1");
	Comment->setGeometry(130, 70, 500, 30);
	Comment->setMinimumSize(0, 0);
	Comment->setMaximumSize(32767, 32767);
	Comment->setFocusPolicy(QWidget::StrongFocus);
	Comment->setBackgroundMode(QWidget::PaletteBase);
#if QT_VERSION < 300
	Comment->setFontPropagation(QWidget::SameFont);
	Comment->setPalettePropagation(QWidget::SameFont);
	#endif
	Comment->setText( "" );
	Comment->setMaxLength( 32767 );
	Comment->setFrame( QLineEdit::Normal );
	Comment->setFrame( TRUE );
	Comment->setAlignment( AlignLeft );
	resize(650,170);
	setMinimumSize(0, 0);
	setMaximumSize(32767, 32767);
}
AckAlarmDlgData::~AckAlarmDlgData()
{
}

