/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823PRESENTATION"
 * 	found in "../isoPresentationLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#include <asn_internal.h>

#include "CPtype.h"

static asn_TYPE_member_t asn_MBR_normalmodeparameters_3[] = {
	{ ATF_POINTER, 8, offsetof(struct normalmodeparameters, protocolversion),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Protocolversion,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"protocolversion"
		},
	{ ATF_POINTER, 7, offsetof(struct normalmodeparameters, callingpresentationselector),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Callingpresentationselector,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"callingpresentationselector"
		},
	{ ATF_POINTER, 6, offsetof(struct normalmodeparameters, calledpresentationselector),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Calledpresentationselector,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"calledpresentationselector"
		},
	{ ATF_POINTER, 5, offsetof(struct normalmodeparameters, presentationcontextdefinitionlist),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Presentationcontextdefinitionlist,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"presentationcontextdefinitionlist"
		},
	{ ATF_POINTER, 4, offsetof(struct normalmodeparameters, defaultcontextname),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Defaultcontextname,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"defaultcontextname"
		},
	{ ATF_POINTER, 3, offsetof(struct normalmodeparameters, presentationrequirements),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Presentationrequirements,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"presentationrequirements"
		},
	{ ATF_POINTER, 2, offsetof(struct normalmodeparameters, usersessionrequirements),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Usersessionrequirements,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"usersessionrequirements"
		},
	{ ATF_POINTER, 1, offsetof(struct normalmodeparameters, userdata),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_Userdata,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"userdata"
		},
};
static ber_tlv_tag_t asn_DEF_normalmodeparameters_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_normalmodeparameters_tag2el_3[] = {
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 7, 0, 0 }, /* simplyencodeddata at 76 */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 7, 0, 0 }, /* fullyencodeddata at 78 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* protocolversion at 14 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* callingpresentationselector at 15 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* calledpresentationselector at 16 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* presentationcontextdefinitionlist at 17 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 4, 0, 0 }, /* defaultcontextname at 18 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 5, 0, 0 }, /* presentationrequirements at 19 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 6, 0, 0 } /* usersessionrequirements at 20 */
};
static asn_SEQUENCE_specifics_t asn_SPC_normalmodeparameters_specs_3 = {
	sizeof(struct normalmodeparameters),
	offsetof(struct normalmodeparameters, _asn_ctx),
	asn_MAP_normalmodeparameters_tag2el_3,
	9,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_normalmodeparameters_3 = {
	"normalmodeparameters",
	"normalmodeparameters",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_normalmodeparameters_tags_3,
	sizeof(asn_DEF_normalmodeparameters_tags_3)
		/sizeof(asn_DEF_normalmodeparameters_tags_3[0]) - 1, /* 1 */
	asn_DEF_normalmodeparameters_tags_3,	/* Same as above */
	sizeof(asn_DEF_normalmodeparameters_tags_3)
		/sizeof(asn_DEF_normalmodeparameters_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_normalmodeparameters_3,
	8,	/* Elements count */
	&asn_SPC_normalmodeparameters_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CPtype_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CPtype, modeselector),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Modeselector,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"modeselector"
		},
	{ ATF_POINTER, 1, offsetof(struct CPtype, normalmodeparameters),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_normalmodeparameters_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"normalmodeparameters"
		},
};
static ber_tlv_tag_t asn_DEF_CPtype_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_CPtype_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* modeselector at 6 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 } /* normalmodeparameters at 14 */
};
static uint8_t asn_MAP_CPtype_mmap_1[(2 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7) | (0 << 6)
};
static asn_SET_specifics_t asn_SPC_CPtype_specs_1 = {
	sizeof(struct CPtype),
	offsetof(struct CPtype, _asn_ctx),
	offsetof(struct CPtype, _presence_map),
	asn_MAP_CPtype_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_CPtype_tag2el_1,	/* Same as above */
	2,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_CPtype_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_CPtype = {
	"CPtype",
	"CPtype",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CPtype_tags_1,
	sizeof(asn_DEF_CPtype_tags_1)
		/sizeof(asn_DEF_CPtype_tags_1[0]), /* 1 */
	asn_DEF_CPtype_tags_1,	/* Same as above */
	sizeof(asn_DEF_CPtype_tags_1)
		/sizeof(asn_DEF_CPtype_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CPtype_1,
	2,	/* Elements count */
	&asn_SPC_CPtype_specs_1	/* Additional specs */
};

