/*
 Mango - Open Source M2M - http://mango.serotoninsoftware.com
 Copyright (C) 2006-2011 Serotonin Software Technologies Inc.
 @author Matthew Lohbihler
    
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.serotonin.mango.db.upgrade;

import com.serotonin.mango.Common;
import java.io.OutputStream;
import javax.sql.DataSource;

/**
 * @author Matthew Lohbihler
 */
public class Upgrade1_4_2 extends DBUpgrade {

    private Upgrade1_4_2() {
        super();
    }
    
   @Deprecated
    private Upgrade1_4_2(DataSource dataSource) {
        super(dataSource);
    }

     public static Upgrade1_4_2 getInstance() {
        return new Upgrade1_4_2(Common.ctx.getDatabaseAccess().getDataSource());
    }
    
    @Override
    public void upgrade() throws Exception {
        // Run the script.
        try (OutputStream out = createUpdateLogOutputStream("1_4_2")) {
            // Run the script.
            LOG.info("Running script");
            runScript(script, out);
            
            out.flush();
        }
    }

    @Override
    protected String getNewSchemaVersion() {
        return "1.5.0";
    }

    private static String[] script = {
        "alter table pointViews alter dataPointId null;",
        "alter table scheduledEvents add alias varchar(255);",
        "alter table pointViews add displayControls char(1) default 'Y' not null;",
        "create table staticViews (",
        "  id int not null generated by default as identity (start with 1, increment by 1),",
        "  mangoViewId int not null,",
        "  x int not null,",
        "  y int not null,",
        "  content clob",
        ");",
        "alter table staticViews add constraint staticViewsPk primary key (id);",
        "alter table staticViews add constraint staticViewsFk1 foreign key (mangoViewId) references mangoViews(id);",};
}
