/**********************************************************************
--- Qt Architect generated file ---
File: UnitCfgData.cpp
Last generated: Thu Jan 4 16:05:08 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#include <qt.h>
#include "UnitCfgData.h"
#include <common.h>

UnitCfgData::UnitCfgData(QWidget *parent, const char *name)
: QDialog(parent, name, TRUE, 208)
{
	QFrame *qtarch_Frame_2 = new QFrame(this, "Frame_2");
	qtarch_Frame_2->setGeometry(20, 10, 580, 240);
	qtarch_Frame_2->setMinimumSize(0, 0);
	qtarch_Frame_2->setMaximumSize(32767, 32767);
	qtarch_Frame_2->setFocusPolicy(QWidget::NoFocus);
	qtarch_Frame_2->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Frame_2->setFontPropagation(QWidget::SameFont);
	qtarch_Frame_2->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Frame_2->setFrameStyle( 51 );
	qtarch_Frame_2->setLineWidth( 2 );
	qtarch_Frame_2->setMidLineWidth( 0 );
	qtarch_Frame_2->QFrame::setMargin( 0 );
	QLabel *qtarch_Label_7 = new QLabel(this, "Label_7");
	qtarch_Label_7->setGeometry(30, 30, 70, 30);
	qtarch_Label_7->setMinimumSize(0, 0);
	qtarch_Label_7->setMaximumSize(32767, 32767);
	qtarch_Label_7->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_7->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_7->setFontPropagation(QWidget::SameFont);
	qtarch_Label_7->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_7->setFrameStyle( 0 );
	qtarch_Label_7->setLineWidth( 1 );
	qtarch_Label_7->setMidLineWidth( 0 );
	qtarch_Label_7->QFrame::setMargin( 0 );
	qtarch_Label_7->setText( tr( "Name" ) );
	qtarch_Label_7->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_7->setMargin( 0 );
	Name = new QComboBox(FALSE, this, "ComboBox_4");
	Name->setGeometry(110, 30, 430, 30);
	Name->setMinimumSize(0, 0);
	Name->setMaximumSize(32767, 32767);
	Name->setFocusPolicy(QWidget::StrongFocus);
	Name->setBackgroundMode(QWidget::NoBackground);
#if QT_VERSION < 300
	Name->setFontPropagation(QWidget::SameFont);
	Name->setPalettePropagation(QWidget::SameFont);
	#endif
	Name->setSizeLimit( 10 );
	Name->setAutoResize( FALSE );
	Name->setMaxCount( 2147483647 );
	Name->setAutoCompletion( FALSE );
	connect(Name, SIGNAL(activated(int)), SLOT(SelChanged(int)));
	connect(Name, SIGNAL(highlighted(int)), SLOT(SelChanged(int)));
	QLabel *qtarch_Label_8 = new QLabel(this, "Label_8");
	qtarch_Label_8->setGeometry(30, 70, 80, 30);
	qtarch_Label_8->setMinimumSize(0, 0);
	qtarch_Label_8->setMaximumSize(32767, 32767);
	qtarch_Label_8->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_8->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_8->setFontPropagation(QWidget::SameFont);
	qtarch_Label_8->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_8->setFrameStyle( 0 );
	qtarch_Label_8->setLineWidth( 1 );
	qtarch_Label_8->setMidLineWidth( 0 );
	qtarch_Label_8->QFrame::setMargin( 0 );
	qtarch_Label_8->setText( tr( "Comment" ) );
	qtarch_Label_8->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_8->setMargin( 0 );
	Comment = new QLineEdit(this, "LineEdit_4");
	Comment->setGeometry(110, 70, 430, 30);
	Comment->setMinimumSize(0, 0);
	Comment->setMaximumSize(32767, 32767);
	Comment->setFocusPolicy(QWidget::StrongFocus);
	Comment->setBackgroundMode(QWidget::PaletteBase);
#if QT_VERSION < 300
	Comment->setFontPropagation(QWidget::SameFont);
	Comment->setPalettePropagation(QWidget::SameFont);
	#endif
	Comment->setText(tr(NONE_STR) );
	Comment->setMaxLength( 128 );
	Comment->setFrame( QLineEdit::Normal );
	Comment->setFrame( TRUE );
	Comment->setAlignment( AlignLeft );
	QLabel *qtarch_Label_9 = new QLabel(this, "Label_9");
	qtarch_Label_9->setGeometry(30, 120, 70, 30);
	qtarch_Label_9->setMinimumSize(0, 0);
	qtarch_Label_9->setMaximumSize(32767, 32767);
	qtarch_Label_9->setFocusPolicy(QWidget::NoFocus);
	qtarch_Label_9->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	qtarch_Label_9->setFontPropagation(QWidget::SameFont);
	qtarch_Label_9->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_Label_9->setFrameStyle( 0 );
	qtarch_Label_9->setLineWidth( 1 );
	qtarch_Label_9->setMidLineWidth( 0 );
	qtarch_Label_9->QFrame::setMargin( 0 );
	qtarch_Label_9->setText( tr( "Type" ) );
	qtarch_Label_9->setAlignment( AlignLeft|AlignVCenter|ExpandTabs );
	qtarch_Label_9->setMargin( 0 );
	Enabled = new QCheckBox(this, "CheckBox_5");
	Enabled->setGeometry(110, 180, 170, 30);
	Enabled->setMinimumSize(0, 0);
	Enabled->setMaximumSize(32767, 32767);
	Enabled->setFocusPolicy(QWidget::TabFocus);
	Enabled->setBackgroundMode(QWidget::PaletteBackground);
#if QT_VERSION < 300
	Enabled->setFontPropagation(QWidget::SameFont);
	Enabled->setPalettePropagation(QWidget::SameFont);
	#endif
	Enabled->setText( tr( "Unit Enabled" ) );
	Enabled->setAutoRepeat( FALSE );
	Enabled->setAutoResize( FALSE );
	Enabled->setChecked( FALSE );
	ApplyButton = new QPushButton(this, "PushButton_7");
	ApplyButton->setGeometry(20, 270, 100, 30);
	ApplyButton->setMinimumSize(0, 0);
	ApplyButton->setMaximumSize(32767, 32767);
	ApplyButton->setFocusPolicy(QWidget::TabFocus);
	ApplyButton->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	ApplyButton->setFontPropagation(QWidget::SameFont);
	ApplyButton->setPalettePropagation(QWidget::SameFont);
	#endif
	ApplyButton->setText( tr( "Apply" ) );
	ApplyButton->setAutoRepeat( FALSE );
	ApplyButton->setAutoResize( FALSE );
	ApplyButton->setToggleButton( FALSE );
	ApplyButton->setDefault( FALSE );
	ApplyButton->setAutoDefault( TRUE );
	ApplyButton->setIsMenuButton( FALSE );
	connect(ApplyButton, SIGNAL(clicked()), SLOT(Apply()));
	NewButton = new QPushButton(this, "PushButton_8");
	NewButton->setGeometry(140, 270, 100, 30);
	NewButton->setMinimumSize(0, 0);
	NewButton->setMaximumSize(32767, 32767);
	NewButton->setFocusPolicy(QWidget::TabFocus);
	NewButton->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	NewButton->setFontPropagation(QWidget::SameFont);
	NewButton->setPalettePropagation(QWidget::SameFont);
	#endif
	NewButton->setText( tr( "New..." ) );
	NewButton->setAutoRepeat( FALSE );
	NewButton->setAutoResize( FALSE );
	NewButton->setToggleButton( FALSE );
	NewButton->setDefault( FALSE );
	NewButton->setAutoDefault( TRUE );
	NewButton->setIsMenuButton( FALSE );
	connect(NewButton, SIGNAL(clicked()), SLOT(New()));
	DeleteButton = new QPushButton(this, "PushButton_9");
	DeleteButton->setGeometry(260, 270, 100, 30);
	DeleteButton->setMinimumSize(0, 0);
	DeleteButton->setMaximumSize(32767, 32767);
	DeleteButton->setFocusPolicy(QWidget::TabFocus);
	DeleteButton->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	DeleteButton->setFontPropagation(QWidget::SameFont);
	DeleteButton->setPalettePropagation(QWidget::SameFont);
	#endif
	DeleteButton->setText( tr( "Delete..." ) );
	DeleteButton->setAutoRepeat( FALSE );
	DeleteButton->setAutoResize( FALSE );
	DeleteButton->setToggleButton( FALSE );
	DeleteButton->setDefault( FALSE );
	DeleteButton->setAutoDefault( TRUE );
	DeleteButton->setIsMenuButton( FALSE );
	connect(DeleteButton, SIGNAL(clicked()), SLOT(Delete()));
	QPushButton *qtarch_PushButton_10 = new QPushButton(this, "PushButton_10");
	qtarch_PushButton_10->setGeometry(380, 270, 100, 30);
	qtarch_PushButton_10->setMinimumSize(0, 0);
	qtarch_PushButton_10->setMaximumSize(32767, 32767);
	qtarch_PushButton_10->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_10->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_10->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_10->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_10->setText( tr( "Help" ) );
	qtarch_PushButton_10->setAutoRepeat( FALSE );
	qtarch_PushButton_10->setAutoResize( FALSE );
	qtarch_PushButton_10->setToggleButton( FALSE );
	qtarch_PushButton_10->setDefault( FALSE );
	qtarch_PushButton_10->setAutoDefault( TRUE );
	qtarch_PushButton_10->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_10, SIGNAL(clicked()), SLOT(Help()));
	QPushButton *qtarch_PushButton_11 = new QPushButton(this, "PushButton_11");
	qtarch_PushButton_11->setGeometry(440, 180, 100, 30);
	qtarch_PushButton_11->setMinimumSize(0, 0);
	qtarch_PushButton_11->setMaximumSize(32767, 32767);
	qtarch_PushButton_11->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_11->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_11->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_11->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_11->setText( tr( "Configure..." ) );
	qtarch_PushButton_11->setAutoRepeat( FALSE );
	qtarch_PushButton_11->setAutoResize( FALSE );
	qtarch_PushButton_11->setToggleButton( FALSE );
	qtarch_PushButton_11->setDefault( FALSE );
	qtarch_PushButton_11->setAutoDefault( TRUE );
	qtarch_PushButton_11->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_11, SIGNAL(clicked()), SLOT(Configure()));
	QPushButton *qtarch_PushButton_12 = new QPushButton(this, "PushButton_12");
	qtarch_PushButton_12->setGeometry(500, 270, 100, 30);
	qtarch_PushButton_12->setMinimumSize(0, 0);
	qtarch_PushButton_12->setMaximumSize(32767, 32767);
	qtarch_PushButton_12->setFocusPolicy(QWidget::TabFocus);
	qtarch_PushButton_12->setBackgroundMode(QWidget::PaletteButton);
#if QT_VERSION < 300
	qtarch_PushButton_12->setFontPropagation(QWidget::SameFont);
	qtarch_PushButton_12->setPalettePropagation(QWidget::SameFont);
	#endif
	qtarch_PushButton_12->setText( tr( "Exit" ) );
	qtarch_PushButton_12->setAutoRepeat( FALSE );
	qtarch_PushButton_12->setAutoResize( FALSE );
	qtarch_PushButton_12->setToggleButton( FALSE );
	qtarch_PushButton_12->setDefault( FALSE );
	qtarch_PushButton_12->setAutoDefault( TRUE );
	qtarch_PushButton_12->setIsMenuButton( FALSE );
	connect(qtarch_PushButton_12, SIGNAL(clicked()), SLOT(reject()));
	UnitType = new QComboBox(FALSE, this, "ComboBox_5");
	UnitType->setGeometry(110, 120, 430, 30);
	UnitType->setMinimumSize(0, 0);
	UnitType->setMaximumSize(32767, 32767);
	UnitType->setFocusPolicy(QWidget::StrongFocus);
	UnitType->setBackgroundMode(QWidget::NoBackground);
#if QT_VERSION < 300
	UnitType->setFontPropagation(QWidget::SameFont);
	UnitType->setPalettePropagation(QWidget::SameFont);
	#endif
	UnitType->setSizeLimit( 10 );
	UnitType->setAutoResize( FALSE );
	UnitType->setMaxCount( 2147483647 );
	UnitType->setAutoCompletion( FALSE );
	resize(620,330);
	setMinimumSize(0, 0);
	setMaximumSize(32767, 32767);
}
UnitCfgData::~UnitCfgData()
{
}

