/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE1"
 * 	found in "../isoAcseLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_AEinvocationidentifier_H_
#define	_AEinvocationidentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AEinvocationidentifier */
typedef long	 AEinvocationidentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AEinvocationidentifier;
asn_struct_free_f AEinvocationidentifier_free;
asn_struct_print_f AEinvocationidentifier_print;
asn_constr_check_f AEinvocationidentifier_constraint;
ber_type_decoder_f AEinvocationidentifier_decode_ber;
der_type_encoder_f AEinvocationidentifier_encode_der;
xer_type_decoder_f AEinvocationidentifier_decode_xer;
xer_type_encoder_f AEinvocationidentifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AEinvocationidentifier_H_ */
