CUSTLIBRARIES= $(shell wx-config --libs)

CUSTINCLUDES= $(shell wx-config --cflags) -DWXUSINGDLL -Wno-long-long -Wno-variadic-macros

CUSTOBJECTS= libioDirDialogue.o libioFileDialogue.o

include ../linux.mk



