/**********************************************************************
--- Qt Architect generated file ---
File: Modbus_driverCommandData.h
Last generated: Thu Jan 4 16:13:32 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef Modbus_driverCommandData_included
#define Modbus_driverCommandData_included

#include <qt.h>
#include "valedit.h"

class Modbus_driverCommandData : public QDialog
{
	Q_OBJECT
	public:
	Modbus_driverCommandData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~Modbus_driverCommandData();
	protected slots:
	virtual void Help() =0;
	virtual void OkClicked() =0;
	protected:
	QLabel *Name;
	QLineEdit *Value;
};
#endif // Modbus_driverCommandData_included

