/**********************************************************************
--- Qt Architect generated file ---
File: ReceipeSelectData.h
Last generated: Fri Feb 16 15:11:52 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef ReceipeSelectData_included
#define ReceipeSelectData_included
#include <qt.h>
class ReceipeSelectData : public QDialog
{
	Q_OBJECT
	public:
	ReceipeSelectData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~ReceipeSelectData();
	QListBox *List;
	QPushButton *OkButton;
};
#endif // ReceipeSelectData_included

