/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ACSE1"
 * 	found in "../isoAcseLayer.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Releaseresponsereason_H_
#define	_Releaseresponsereason_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Releaseresponsereason {
	Releaseresponsereason_normal	= 0,
	Releaseresponsereason_notfinished	= 1,
	Releaseresponsereason_userdefined	= 30
} e_Releaseresponsereason;

/* Releaseresponsereason */
typedef long	 Releaseresponsereason_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Releaseresponsereason;
asn_struct_free_f Releaseresponsereason_free;
asn_struct_print_f Releaseresponsereason_print;
asn_constr_check_f Releaseresponsereason_constraint;
ber_type_decoder_f Releaseresponsereason_decode_ber;
der_type_encoder_f Releaseresponsereason_encode_der;
xer_type_decoder_f Releaseresponsereason_decode_xer;
xer_type_encoder_f Releaseresponsereason_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Releaseresponsereason_H_ */
