/**********************************************************************
--- Qt Architect generated file ---
File: Iec101driverCommandData.h
Last generated: Thu Jan 4 16:13:32 2001
DO NOT EDIT!!!  This file will be automatically
regenerated by qtarch.  All changes will be lost.
*********************************************************************/
#ifndef Iec101driverCommandData_included
#define Iec101driverCommandData_included

#include <qt.h>
#include "valedit.h"

class Iec101driverCommandData : public QDialog
{
	Q_OBJECT
	public:
	Iec101driverCommandData(QWidget *parent = NULL, const char *name = NULL);
	virtual ~Iec101driverCommandData();
	protected slots:
	virtual void Help() =0;
	virtual void OkClicked() =0;
	protected:
	QLabel *Name;
	QLineEdit *Value;
};
#endif // Iec101driverCommandData_included

